clc;
clear;

% input time courses (after normalization), which should have been generated by Zaixu's code
data_file = '/project_folder/Sub_id/sbjData.mat';
% decomposition results
decomp_file = '/project_folder/Sub_id/IndividualParcel_folder/final_UV.mat';

data_mat = load(data_file);
decomp_mat = load(decomp_file);

D = data_mat.sbjData{1};
U = decomp_mat.U{1};
V = decomp_mat.V{1};
recon_err = calc_recon_error(D, U, V);
