---
title: "AgeFCMatViz"
author: "Adam"
date: "7/23/2020"
output: html_document
---

```{r}
library(ggplot2)
library(corrplot)
library(circlize)
#library(ggraph)
#library(igraph)
 
### Get in Consensus-reference atlas correspondence
rac<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_yCorrespondence_overscales.csv',stringsAsFactors = F)
scalesvec<-as.numeric(rac[2,])
domnetvec<-as.factor(rac[3,])
netpropvec<-as.numeric(rac[4,])
# 17 network version
rac17<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_y17Correspondence_overscales.csv',stringsAsFactors = F)
scalesvec17<-as.numeric(rac17[2,])
domnetvec17<-as.factor(rac17[3,])
netpropvec17<-as.numeric(rac17[4,])
#### read in transmodality
tm<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_transmodality_overscales.csv',stringsAsFactors = F)
colnames(tm)<-tm[1,]
# aaaand remove it so we got everything in its right place
tm<-tm[-c(1),]
tmvec<-as.numeric(tm)
# use median transmodality value to split relatively bimodal distribution
medtrans<-median(tmvec)
# equivalent vector to be overwritten with binary classification of transmodality
tmclass<-tmvec
for (i in 1:length(tmclass)){
  if (tmvec[i]<= medtrans){
    tmclass[i]='unimodal'
  }else{
    tmclass[i]='transmodal'
  }
}

grid.col = c(Motor = "#3281ab", Visual = "#670068", DA = "#007500", VA = '#b61ad0', FP = "#d77d00", DM = "#c1253c", Limbic = '#f0f9b8')

y7TMorder=c("Motor","Visual","DA","VA","Limbic","FP","DM")

# names pulled from y17vec in BwRsqCentric
grid.col_y17=c(Control_A='#dc8303',Control_B='#8d2049',Control_C='#596a85',DA_A='#2d9a3d',DA_B='#007938',DM_A='#d9e200',DM_B='#bc0943',DM_C='#2b1f67',Limbic_A='#48593a',Limbic_B='#91a967',Somatomotor_A='#4183a8',Somatomotor_B='#00bb89',Temporal_Parietal='#3245a3',VA_A='#9e3ca2',VA_B='#eb75b3',Visual_A='#68126f',Visual_B='#d1001c')

###y17TMorder=c("Somatomotor_A","Somatomotor_B","Visual_B","Visual_A")


Y7vec<-c('Motor','Visual','DA','VA','Limbic','FP','DM')
## needs the big one to be run y17vec<-levels(domnetvec17)
# set yeo colorset
ycolors=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c')
y17colors=c('#dc8303','#8d2049','#596a85','#2d9a3d','#007938','#d9e200','#bc0943','#2b1f67','#48593a','#91a967','#4183a8','#00bb89','#3245a3','#9e3ca2','#eb75b3','#68126f','#d1001c')



col_fun=function(x) ifelse(abs(x)<.0001,"#00000000",
                           ifelse(x<0,"blue","red"))
                           
  
for (K in 2:30){
  K_start=((K-1)*(K))/2
  K_end=(((K-1)*(K))/2)+K-1
  Kind<-K_start:K_end
  # change fc_Mat to fc_ageMat to plot fc matrix of age effects instead
  AgeEfMatFn=paste('/cbica/projects/pinesParcels/results/EffectMats/fc_Mat_K',K,'.csv',sep='')
  AgeEfMat=as.matrix(read.csv(AgeEfMatFn))
  # requires domnetvec to be ran in other rmd
  colnames(AgeEfMat)=domnetvec17[Kind]
  rownames(AgeEfMat)=domnetvec17[Kind]
  # get tmvec to arrange matrix by transmodality
  curTmRank<-order(tmvec[Kind])
  
  # if desired, COMMENT OUT TO OBSERVE ORIGINAL ORDER
  ReArAgeEfMat<-AgeEfMat[curTmRank,curTmRank]
  #ReArAgeEfMat<-AgeEfMat
  
  ReArAgeEfMatThresh<-ReArAgeEfMat
  #ReArAgeEfMatThresh[ReArAgeEfMat > -.1 & ReArAgeEfMat < .1]=0
  corrplot(ReArAgeEfMat,is.corr = F,tl.cex = 2,cl.cex=2,cl.ratio = .3)
  
  #chordDiagram(ReArAgeEfMat,grid.col = grid.col, col = col_fun,symmetric = "TRUE",annotationTrack=c("name","grid"),self.link = 1)
  #title(paste('Age at K =',K))
  
}

#univarite edge mediation
weightvector=AB_EstEdgesvec
chordDf<-data.frame(matrix(nrow = length(weightvector),ncol = 3))
colnames(chordDf)<-c('Y7_1','Y7_2','value')
# values we have, labels need some caressing 
chordDf$value<-weightvector
# plant into chord df
chordDf$Y7_1<-BwAgeDR2TMDifDf$Net1Vec17
chordDf$Y7_2<-BwAgeDR2TMDifDf$Net2Vec17
# replace spaces with '_'
chordDf$Y7_1<-gsub(' ','_',chordDf$Y7_1)
chordDf$Y7_2<-gsub(' ','_',chordDf$Y7_2)
# threshold DF
#chordDf$value[abs(chordDf$value)<0.05]=0
# change colnames to match internet example (no direction in this graph doe)
colnames(chordDf)<-c('from','to','value')
chordDiagramFromDataFrame(chordDf,grid.col = grid.col_y17,col = col_fun,annotationTrack = c("name","grid"))
  title(paste('Univariate AB Path Coefs'))

# pull out increasing with age only
AB_EstEdgesvecPos<-AB_EstEdgesvec
AB_EstEdgesvecPos[AB_EstEdgesvec_agedir<0]<-0
# pull out decreasing with age only
AB_EstEdgesvecNeg<-AB_EstEdgesvec
AB_EstEdgesvecNeg[AB_EstEdgesvec_agedir>0]<-0
weightvector=AB_EstEdgesvec

#plot inc. w/ age
chordDf<-data.frame(matrix(nrow = length(weightvector),ncol = 3))
colnames(chordDf)<-c('Y7_1','Y7_2','value')
# values we have, labels need some caressing 
chordDf$value<-AB_EstEdgesvecPos
# plant into chord df
chordDf$Y7_1<-BwAgeDR2TMDifDf$Net1Vec
chordDf$Y7_2<-BwAgeDR2TMDifDf$Net2Vec
# replace spaces with '_'
chordDf$Y7_1<-gsub(' ','_',chordDf$Y7_1)
chordDf$Y7_2<-gsub(' ','_',chordDf$Y7_2)
# threshold DF
#chordDf$value[abs(chordDf$value)<0.05]=0
# change colnames to match internet example (no direction in this graph doe)
colnames(chordDf)<-c('from','to','value')
chordDiagramFromDataFrame(chordDf,order = y7TMorder,grid.col = grid.col,col = col_fun,annotationTrack = c("name","grid"))
  title(paste('AB Path Coefs: Increasing with Age'))
  
#plot dec. w/ age
chordDf<-data.frame(matrix(nrow = length(weightvector),ncol = 3))
colnames(chordDf)<-c('Y7_1','Y7_2','value')
# values we have, labels need some caressing 
chordDf$value<-AB_EstEdgesvecNeg
# plant into chord df
chordDf$Y7_1<-BwAgeDR2TMDifDf$Net1Vec
chordDf$Y7_2<-BwAgeDR2TMDifDf$Net2Vec
# replace spaces with '_'
chordDf$Y7_1<-gsub(' ','_',chordDf$Y7_1)
chordDf$Y7_2<-gsub(' ','_',chordDf$Y7_2)
# threshold DF
#chordDf$value[abs(chordDf$value)<0.05]=0
# change colnames to match internet example (no direction in this graph doe)
colnames(chordDf)<-c('from','to','value')
chordDiagramFromDataFrame(chordDf,order = y7TMorder,grid.col = grid.col,col = col_fun,annotationTrack = c("name","grid"))
  title(paste('AB Path Coefs: Decreasing with Age'))
  
# scatterplots for comparison  
BwAgeCorTMDifDf$posweights<-AB_EstEdgesvecPos
BwAgeCorTMDifDf$negweights<-AB_EstEdgesvecNeg
ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=posweights,color=Net1Vec)) + geom_text(size=5,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF Mediation') + ggtitle('Edges Increasing With Age')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=posweights,color=Net2Vec),size=5,label="\u25D7",family="Arial Unicode MS")+theme_classic()
ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=negweights,color=Net1Vec)) + geom_text(size=5,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF Mediation') + ggtitle('Edges Decreasing with Age')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=negweights,color=Net2Vec),size=5,label="\u25D7",family="Arial Unicode MS")+theme_classic()

# for univariate mediators, need 4 category horizontal violin:
# Age +, EF + "1"
# Age -, EF - "2"
# Age +, EF - "3"
# Age -, EF + "4"
# so, make a categorical variable for BwAgeCorTMDifDf denoting which cat it is in
BwAgeCorTMDifDf$MediationCategory<-rep(0,dim(BwAgeCorTMDifDf)[1])
BwAgeCorTMDifDf$MediationCategory<-as.factor(BwAgeCorTMDifDf$MediationCategory)
levels(BwAgeCorTMDifDf$MediationCategory)<-c('None','AgeEFPos','AgePosEFNeg','AgeNegEFPos','AgeEFNeg')
for (i in 1:dim(BwAgeCorTMDifDf)[1]){
  # if these edges are sig increasing with age
  if (BwAgeCorTMDifDf$posweights[i] != 0){
    # are they pos. assoc. w/ EF? (is AB positive)
    if (BwAgeCorTMDifDf$posweights[i] > 0){
      BwAgeCorTMDifDf$MediationCategory[i]<-'AgeEFPos'
    } 
    if (BwAgeCorTMDifDf$posweights[i] < 0){
      BwAgeCorTMDifDf$MediationCategory[i]<-'AgePosEFNeg'
    }
  }
  # now handle edges sig decreasing with age
  if (BwAgeCorTMDifDf$negweights[i] != 0){
    # if >0, dec. w/ age inc. w/ EF
    if (BwAgeCorTMDifDf$negweights[i] > 0){
      BwAgeCorTMDifDf$MediationCategory[i]<-'AgeNegEFPos'
    } 
    # if <0, dec w/ age and EF
    if (BwAgeCorTMDifDf$negweights[i] < 0){
      BwAgeCorTMDifDf$MediationCategory[i]<-'AgeEFNeg'
    }
  }
}

ggplot(data=BwAgeCorTMDifDf)+geom_violin(aes(x=tmdifvec,y=MediationCategory),bw=.25)+geom_text(aes(x=tmdifvec,y=MediationCategory,color=Net1Vec),size=5,label="\u25D6",family="Arial Unicode MS")+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=MediationCategory,color=Net2Vec),size=5,label="\u25D7",family="Arial Unicode MS")+theme_classic()
```

```{r}
# pcor pdms
pcorkAllPDM1<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/pcorPDM1_AllEdges.csv',header=F)
pcorkAllPDM2<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/pcorPDM2_AllEdges.csv',header=F)

# PDM1 @ All edges
kAllPDM1<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/pcPDM1_AllEdges.csv',header=F)
kAllPDM2<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/pcPDM2_AllEdges.csv',header=F)
kAllPDM3<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/pcPDM3_AllEdges.csv',header=F)
kAllPDM4<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/pcPDM4_AllEdges.csv',header=F)
kAllPDM5<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/pcPDM5_AllEdges.csv',header=F)
kAllPDM6<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/pcPDM6_AllEdges.csv',header=F)
kAllPDM7<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/pcPDM7_AllEdges.csv',header=F)
kAllPDM8<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/pcPDM8_AllEdges.csv',header=F)

KAcrossNeg<-kAllPDM2+kAllPDM4+kAllPDM5+kAllPDM7+kAllPDM8
KAcrossPos<-kAllPDM1+kAllPDM3+kAllPDM6
### attempt to make generalizeable chord diagram plots for PDMs
# change to be iterative as we move forward
weightvector=KAcrossNeg
# initialize a new dataframe of this size
chordDf<-data.frame(matrix(nrow = dim(weightvector)[1],ncol = 3))
colnames(chordDf)<-c('Y7_1','Y7_2','value')
# values we have, labels need some caressing 
chordDf$value<-weightvector$V1
# plant into chord df
chordDf$Y7_1<-BwAgeDR2TMDifDf$Net1Vec
chordDf$Y7_2<-BwAgeDR2TMDifDf$Net2Vec
# replace spaces with '_'
chordDf$Y7_1<-gsub(' ','_',chordDf$Y7_1)
chordDf$Y7_2<-gsub(' ','_',chordDf$Y7_2)
# threshold DF
#chordDf$value[abs(chordDf$value)<0.05]=0
# change colnames to match internet example (no direction in this graph doe)
colnames(chordDf)<-c('from','to','value')
chordDiagramFromDataFrame(chordDf,grid.col = grid.col, order = y7TMorder,col = col_fun,annotationTrack = c("name","grid"))
  title(paste('Across Negative PDMs'))

# pull in this pairwise plot for comparison
BwAgeCorTMDifDf$posweights<-KAcrossPos$V1
BwAgeCorTMDifDf$negweights<-KAcrossNeg$V1
ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=posweights,color=Net1Vec)) + geom_text(size=5,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('Positive Mediation Weight') + ggtitle('Positive Mediators of EF')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=posweights,color=Net2Vec),size=5,label="\u25D7",family="Arial Unicode MS")+theme_classic()

ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=negweights,color=Net1Vec)) + geom_text(size=5,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('Negative Mediation Weight') + ggtitle('Negative Mediators of EF')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=negweights,color=Net2Vec),size=5,label="\u25D7",family="Arial Unicode MS")+theme_classic()

ggplot(data=BwAgeCorTMDifDf)+geom_violin(aes(x=tmdifvec,y=MediationCategory),bw=.25)+geom_text(aes(x=tmdifvec,y=MediationCategory,color=Net1Vec),size=5,label="\u25D6",family="Arial Unicode MS")+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=MediationCategory,color=Net2Vec),size=5,label="\u25D7",family="Arial Unicode MS")+theme_classic()

ggplot(data=BwAgeCorTMDifDf)+geom_violin(aes(x=tmdifvec,y=MediationCategory),bw=.25)+geom_text(aes(x=tmdifvec,y=MediationCategory,color=Net1Vec),size=5,label="\u25D6",family="Arial Unicode MS")+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=MediationCategory,color=Net2Vec),size=5,label="\u25D7",family="Arial Unicode MS")+theme_classic()

# further parsing of Pos and Neg weights : exlcude if other mediation has larger effect
KAcrossNeg2<-scale(KAcrossNeg)
KAcrossPos2<-scale(KAcrossPos)
KAcrossNeg2[abs(KAcrossNeg2)<abs(KAcrossPos2)]<-0
KAcrossPos2[abs(KAcrossPos2)<abs(KAcrossNeg2)]<-0
# change to be iterative as we move forward
weightvector=KAcrossPos2
# initialize a new dataframe of this size
chordDf<-data.frame(matrix(nrow = dim(weightvector)[1],ncol = 3))
colnames(chordDf)<-c('Y7_1','Y7_2','value')
# values we have, labels need some caressing 
chordDf$value<-weightvector[,1]
# plant into chord df
chordDf$Y7_1<-BwAgeDR2TMDifDf$Net1Vec
chordDf$Y7_2<-BwAgeDR2TMDifDf$Net2Vec
# replace spaces with '_'
chordDf$Y7_1<-gsub(' ','_',chordDf$Y7_1)
chordDf$Y7_2<-gsub(' ','_',chordDf$Y7_2)
# threshold DF
#chordDf$value[abs(chordDf$value)<0.05]=0
# change colnames to match internet example (no direction in this graph doe)
colnames(chordDf)<-c('from','to','value')
chordDiagramFromDataFrame(chordDf,order = y7TMorder, grid.col = grid.col, col = col_fun,annotationTrack = c("name","grid"))
  title(paste('Across Positive PDMs'))
  
# pull in this pairwise plot for comparison
BwAgeCorTMDifDf$posweights<-KAcrossPos2[,1]
BwAgeCorTMDifDf$negweights<-KAcrossNeg2[,1]
ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=posweights,color=Net1Vec)) + geom_text(size=5,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('Positive Mediation Weight') + ggtitle('Positive Mediators of EF')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=posweights,color=Net2Vec),size=5,label="\u25D7",family="Arial Unicode MS")+theme_classic()

ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=negweights,color=Net1Vec)) + geom_text(size=5,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('Negative Mediation Weight') + ggtitle('Negative Mediators of EF')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=negweights,color=Net2Vec),size=5,label="\u25D7",family="Arial Unicode MS")+theme_classic()

#yeo17
ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=posweights,color=Net1Vec17)) + geom_text(size=5,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('Positive Mediation Weight') + ggtitle('Positive Mediators of EF')+scale_color_manual(values=y17colors,limits=y17vec)+geom_text(aes(x=tmdifvec,y=posweights,color=Net2Vec17),size=5,label="\u25D7",family="Arial Unicode MS")+theme_classic()

ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=negweights,color=Net1Vec17)) + geom_text(size=5,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('Negative Mediation Weight') + ggtitle('Negative Mediators of EF')+scale_color_manual(values=y17colors,limits=y17vec)+geom_text(aes(x=tmdifvec,y=negweights,color=Net2Vec17),size=5,label="\u25D7",family="Arial Unicode MS")+theme_classic()

# with PG2 as 3rd dimension
BwAgeCorTMDifDf$PG2Difference<-occdifvec
#plot3d(x=BwAgeCorTMDifDf$tmdifvec,y=BwAgeCorTMDifDf$posweights,z=BwAgeCorTMDifDf$PG2Difference,size = 5)

ggplot(data=BwAgeCorTMDifDf)+geom_violin(aes(x=tmdifvec,y=MediationCategory),bw=.5,size=2)+geom_text(aes(x=tmdifvec,y=MediationCategory,color=Net1Vec),size=5,label="\u25D6",family="Arial Unicode MS",position=position_dodge(0.4))+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=MediationCategory,color=Net2Vec),size=5,label="\u25D7",family="Arial Unicode MS",position=position_dodge(0.4))+theme_classic()
```

```{r}

# PDM1 @ K=7
# @ K=20
k7PDM1<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/PDM1_7.csv',header=F)
k7PDM2<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/PDM2_7.csv',header=F)

### attempt to make generalizeable chord diagram plots for PDMs
# set K
K=7
K_start=((K-1)*(K))/2
K_end=(((K-1)*(K))/2)+K-1
Kind<-K_start:K_end
# change to be iterative as we move forward
weightvector=k7PDM2
# initialize a new dataframe of this size
chordDf<-data.frame(matrix(nrow = dim(weightvector)[1],ncol = 3))
colnames(chordDf)<-c('Y7_1','Y7_2','value')
# values we have, labels need some caressing 
chordDf$value<-weightvector$V1
# get community order in terms of y7
comOrder=domnetvec[Kind]
# get column names utilized
scaleStr=paste('scale',K,'_',sep='')
scaleCols_inds=grep(scaleStr,colnames(masteref))
# combine with edge only and individualized only values
scaleK_bw_indivi_cols_inds<-intersect(indiv_bwcols_ind,scaleCols_inds)
# get column names for parsing
edgenames<-colnames(masteref)[scaleK_bw_indivi_cols_inds]
# parse edge names to get edge #, y7 from, y7 to, and value
scaleStrExtended=paste('scale',K,'_nets',sep='')
splitEdgenames<-unlist(strsplit(edgenames,scaleStrExtended))
# index of Desired Edge Name Sections
DENS<-splitEdgenames[seq(2,380,2)]
# split into the 2 networks constituting the edge
netNums<-unlist(strsplit(DENS,'_and_'))
net1Nums<-netNums[seq(1,379,2)]
net2Nums<-netNums[seq(2,380,2)]
# use domnetvec to get y7 labels, there is probz a way to do this without looping
net1labs<-NULL
net2labs<-NULL
for (i in 1:dim(weightvector)[1]){
  net1labs[i]<-as.character(comOrder[as.numeric(net1Nums[i])])
  net2labs[i]<-as.character(comOrder[as.numeric(net2Nums[i])])
}
# plant into chord df
chordDf$Y7_1<-net1labs
chordDf$Y7_2<-net2labs
# threshold DF
#chordDf$value[abs(chordDf$value)<0.05]=0
# change colnames to match internet example (no direction in this graph doe)
colnames(chordDf)<-c('from','to','value')
chordDiagramFromDataFrame(chordDf,grid.col = grid.col, col = col_fun)
  title(paste('PDM2 K=',K))
```


```{r}
# just derived PCs (pdm.dat.Dt)
k20_svdOutput<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/edges_PCvals.csv',header=F)

# set K
K=20
K_start=((K-1)*(K))/2
K_end=(((K-1)*(K))/2)+K-1
Kind<-K_start:K_end
# change to be iterative as we move forward
weightvector=k20_svdOutput[1,]
# initialize a new dataframe of this size
chordDf<-data.frame(matrix(nrow = dim(weightvector)[2],ncol = 3))
colnames(chordDf)<-c('Y7_1','Y7_2','value')
# values we have, labels need some caressing 
chordDf$value<-t(weightvector)
# get community order in terms of y7
comOrder=domnetvec[Kind]
# get column names utilized
scaleStr=paste('scale',K,'_',sep='')
scaleCols_inds=grep(scaleStr,colnames(masteref))
# combine with edge only and individualized only values
scaleK_bw_indivi_cols_inds<-intersect(indiv_bwcols_ind,scaleCols_inds)
# get column names for parsing
edgenames<-colnames(masteref)[scaleK_bw_indivi_cols_inds]
# parse edge names to get edge #, y7 from, y7 to, and value
scaleStrExtended=paste('scale',K,'_nets',sep='')
splitEdgenames<-unlist(strsplit(edgenames,scaleStrExtended))
# index of Desired Edge Name Sections
DENS<-splitEdgenames[seq(2,380,2)]
# split into the 2 networks constituting the edge
netNums<-unlist(strsplit(DENS,'_and_'))
net1Nums<-netNums[seq(1,379,2)]
net2Nums<-netNums[seq(2,380,2)]
# use domnetvec to get y7 labels, there is probz a way to do this without looping
net1labs<-NULL
net2labs<-NULL
for (i in 1:dim(weightvector)[2]){
  net1labs[i]<-as.character(comOrder[as.numeric(net1Nums[i])])
  net2labs[i]<-as.character(comOrder[as.numeric(net2Nums[i])])
}
# plant into chord df
chordDf$Y7_1<-net1labs
chordDf$Y7_2<-net2labs
# threshold DF
#chordDf$value[abs(chordDf$value)<0.05]=0
# change colnames to match internet example (no direction in this graph doe)
colnames(chordDf)<-c('from','to','value')
chordDiagramFromDataFrame(chordDf,grid.col = grid.col, col = col_fun)
  title(paste('Pc1 K=',K))
  
# check out subject level PC loadings
k20_svdOutput_subjs<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/subj_PCvals.csv',header=F)
```

```{r}
# @ K=20
k20PDM1<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/PDM1_K20.csv',header=F)
k20PDM2<-read.csv('/cbica/projects/pinesParcels/multiscale/scripts/analyses/archive/highDim_mediation/PDM2_K20.csv',header=F)

### attempt to make generalizeable chord diagram plots for PDMs
# set K
K=20
K_start=((K-1)*(K))/2
K_end=(((K-1)*(K))/2)+K-1
Kind<-K_start:K_end
# change to be iterative as we move forward
weightvector=k20PDM1
# initialize a new dataframe of this size
chordDf<-data.frame(matrix(nrow = dim(weightvector)[1],ncol = 3))
colnames(chordDf)<-c('Y7_1','Y7_2','value')
# values we have, labels need some caressing 
chordDf$value<-weightvector$V1
# get community order in terms of y7
comOrder=domnetvec[Kind]
# get column names utilized
scaleStr=paste('scale',K,'_',sep='')
scaleCols_inds=grep(scaleStr,colnames(masteref))
# combine with edge only and individualized only values
scaleK_bw_indivi_cols_inds<-intersect(indiv_bwcols_ind,scaleCols_inds)
# get column names for parsing
edgenames<-colnames(masteref)[scaleK_bw_indivi_cols_inds]
# parse edge names to get edge #, y7 from, y7 to, and value
scaleStrExtended=paste('scale',K,'_nets',sep='')
splitEdgenames<-unlist(strsplit(edgenames,scaleStrExtended))
# index of Desired Edge Name Sections
DENS<-splitEdgenames[seq(2,380,2)]
# split into the 2 networks constituting the edge
netNums<-unlist(strsplit(DENS,'_and_'))
net1Nums<-netNums[seq(1,379,2)]
net2Nums<-netNums[seq(2,380,2)]
# use domnetvec to get y7 labels, there is probz a way to do this without looping
net1labs<-NULL
net2labs<-NULL
for (i in 1:dim(weightvector)[1]){
  net1labs[i]<-as.character(comOrder[as.numeric(net1Nums[i])])
  net2labs[i]<-as.character(comOrder[as.numeric(net2Nums[i])])
}
# plant into chord df
chordDf$Y7_1<-net1labs
chordDf$Y7_2<-net2labs
# threshold DF
#chordDf$value[abs(chordDf$value)<0.05]=0
# change colnames to match internet example (no direction in this graph doe)
colnames(chordDf)<-c('from','to','value')
chordDiagramFromDataFrame(chordDf,grid.col = grid.col, col = col_fun)
  title(paste('PDM1 K=',K))
  
  
# y17 version
# set K
K=20
K_start=((K-1)*(K))/2
K_end=(((K-1)*(K))/2)+K-1
Kind<-K_start:K_end
# change to be iterative as we move forward
weightvector=k20PDM2
# initialize a new dataframe of this size
chordDf<-data.frame(matrix(nrow = dim(weightvector)[1],ncol = 3))
colnames(chordDf)<-c('Y17_1','Y17_2','value')
# values we have, labels need some caressing 
chordDf$value<-weightvector$V1
# get community order in terms of y7
comOrder=domnetvec17[Kind]
# get column names utilized
scaleStr=paste('scale',K,'_',sep='')
scaleCols_inds=grep(scaleStr,colnames(masteref))
# combine with edge only and individualized only values
scaleK_bw_indivi_cols_inds<-intersect(indiv_bwcols_ind,scaleCols_inds)
# get column names for parsing
edgenames<-colnames(masteref)[scaleK_bw_indivi_cols_inds]
# parse edge names to get edge #, y17 from, y17 to, and value
scaleStrExtended=paste('scale',K,'_nets',sep='')
splitEdgenames<-unlist(strsplit(edgenames,scaleStrExtended))
# index of Desired Edge Name Sections
DENS<-splitEdgenames[seq(2,380,2)]
# split into the 2 networks constituting the edge
netNums<-unlist(strsplit(DENS,'_and_'))
net1Nums<-netNums[seq(1,379,2)]
net2Nums<-netNums[seq(2,380,2)]
# use domnetvec to get y17 labels, there is probz a way to do this without looping
net1labs<-NULL
net2labs<-NULL
for (i in 1:dim(weightvector)[1]){
  net1labs[i]<-as.character(comOrder[as.numeric(net1Nums[i])])
  net2labs[i]<-as.character(comOrder[as.numeric(net2Nums[i])])
}
# grep the spaces out so color can map on
net1labs<-gsub(' ','_',net1labs)
net2labs<-gsub(' ','_',net2labs)
# plant into chord df
chordDf$Y17_1<-net1labs
chordDf$Y17_2<-net2labs
# threshold DF
#chordDf$value[abs(chordDf$value)<0.05]=0
# change colnames to match internet example (no direction in this graph doe)
colnames(chordDf)<-c('from','to','value')
chordDiagramFromDataFrame(chordDf,grid.col = grid.col_y17, col = col_fun)+title(paste('PDM2 K=',K,'y17 colors'))
```

```{r}
# plot pdms b/w transmod. dif
scale20tmdif<-ScaleTMDifDf[ScaleTMDifDf$scalevec==20,]

```

```{r}
### For EF
#for (K in 2:30){
for (K in 2:30){
  K_start=((K-1)*(K))/2
  K_end=(((K-1)*(K))/2)+K-1
  Kind<-K_start:K_end
  EF_EfMatFn=paste('/cbica/projects/pinesParcels/results/EffectMats/fc_EF_Mat_K',K,'.csv',sep='')
  EF_EfMat=as.matrix(read.csv(EF_EfMatFn))
  # requires domnetvec to be ran in other rmd
  colnames(EF_EfMat)=domnetvec[Kind]
  rownames(EF_EfMat)=domnetvec[Kind]
  # get tmvec to arrange matrix by transmodality
  curTmRank<-order(tmvec[Kind])
  ReAr_EF_EfMat<-EF_EfMat[curTmRank,curTmRank]
  ReAr_EF_EfMatThresh<-ReAr_EF_EfMat
  ReAr_EF_EfMatThresh[ReAr_EF_EfMat > -.1 & ReAr_EF_EfMat < .1]=0
  corrplot(ReAr_EF_EfMatThresh,is.corr = F,tl.cex = 2,cl.cex=2,cl.ratio = .3)
  title(paste(K))
  chordDiagram(ReAr_EF_EfMatThresh,grid.col = grid.col, col = col_fun,symmetric = "TRUE",annotationTrack=c("name","grid"),self.link = 1)
  title(paste('EF at K =',K))
}
  
# IN ORIG PARCEL ORDER 
for (K in 2:30){
  K_start=((K-1)*(K))/2
  K_end=(((K-1)*(K))/2)+K-1
  Kind<-K_start:K_end
  EF_EfMatFn=paste('/cbica/projects/pinesParcels/results/EffectMats/fc_EF_Mat_K',K,'.csv',sep='')
  EF_EfMat=as.matrix(read.csv(EF_EfMatFn))

  # more stringent threshold
  EF_EfMat[EF_EfMat > -.13 & EF_EfMat < .13]=0
  corrplot(EF_EfMat,is.corr = F,tl.cex = 2,cl.cex=2,cl.ratio = .3)
  title(paste(K))
  #chordDiagram(ReAr_EF_EfMatThresh,grid.col = grid.col, col = col_fun,symmetric = "TRUE",annotationTrack=c("name","grid"),self.link = 1)
  #title(paste(K))
}
```

```{r}
### For Motion
for (K in 2:30){
  # current version is stripped motion model ordered by transmodality
  K_start=((K-1)*(K))/2
  K_end=(((K-1)*(K))/2)+K-1
  Kind<-K_start:K_end
  Mot_EfMatFn=paste('/cbica/projects/pinesParcels/results/EffectMats/fc_Mot_Mat_K',K,'.csv',sep='')
  Mot_EfMat=as.matrix(read.csv(Mot_EfMatFn))
  # requires domnetvec to be ran in other rmd
  colnames(Mot_EfMat)=domnetvec[Kind]
  rownames(Mot_EfMat)=domnetvec[Kind]
  # get tmvec to arrange matrix by transmodality
  curTmRank<-order(Seg_CIplotdf$Patch_GeoDisperse[Kind])
  
  # by distance vector
  ReAr_Mot_EfMat<-Mot_EfMat[curTmRank,curTmRank]
  ReAr_Mot_EfMatThresh<-ReAr_Mot_EfMat
  ReAr_Mot_EfMatThresh[ReAr_Mot_EfMat > -.1 & ReAr_Mot_EfMat < .1]=0
  corrplot(ReAr_Mot_EfMatThresh,is.corr = F,tl.cex = 2,cl.cex=2,cl.ratio = .3)
  title(paste(K))
  
}

```


```{r}
### For EF Group partition values
for (K in 2:30){
  K_start=((K-1)*(K))/2
  K_end=(((K-1)*(K))/2)+K-1
  Kind<-K_start:K_end
  EF_EfMatFn=paste('/cbica/projects/pinesParcels/results/EffectMats/fc_EF_Mat_K',K,'_Gro.csv',sep='')
  EF_EfMat=as.matrix(read.csv(EF_EfMatFn))
  # requires domnetvec to be ran in other rmd
  colnames(EF_EfMat)=domnetvec[Kind]
  rownames(EF_EfMat)=domnetvec[Kind]
  # get tmvec to arrange matrix by transmodality
  curTmRank<-order(tmvec[Kind])
  ReAr_EF_EfMat<-EF_EfMat[curTmRank,curTmRank]
  ReAr_EF_EfMatThresh<-ReAr_EF_EfMat
  ReAr_EF_EfMatThresh[ReAr_EF_EfMat > -.1 & ReAr_EF_EfMat < .1]=0
  corrplot(ReAr_EF_EfMatThresh,is.corr = F,tl.cex = 2,cl.cex=2,cl.ratio = .3)
  title(paste(K))
  
}
  

```

```{r}
# calc age thirds, get subject id's from oldest, middle, and youngest
quantile(masterdf$Age, c(0,.33, .66, 1))
youngids<-masterdf$bblid[masterdf$Age<177]
oldids<-masterdf$bblid[masterdf$Age>212]

# write to cluster for matlab to read
write.table(oldids,paste('/cbica/projects/pinesParcels/results/aggregated_data/OldestThirdIDs.csv',sep=''),sep=',', col.names = F,quote = F,row.names=F)
write.table(youngids,paste('/cbica/projects/pinesParcels/results/aggregated_data/YoungestThirdIDs.csv',sep=''),sep=',', col.names = F,quote = F,row.names=F)


# after matlab processing in AgeThirds_FcMats.m script, load average FC matrices back in, and re-order by transmodality

for (K in c(4,7,13,20)){
  K_start=((K-1)*(K))/2
  K_end=(((K-1)*(K))/2)+K-1
  Kind<-K_start:K_end
  curTmRank<-order(tmvec[Kind])
  
  oldfn=paste('/cbica/projects/pinesParcels/results/EffectMats/fc_oldMat_K',K,'.csv',sep='')
  youngfn=paste('/cbica/projects/pinesParcels/results/EffectMats/fc_youngMat_K',K,'.csv',sep='')
  old=as.matrix(read.csv(oldfn))
  young=as.matrix(read.csv(youngfn))
  
  # Set names of rows and columns to y7 name
  colnames(old)=domnetvec[Kind]
  rownames(old)=domnetvec[Kind]
  colnames(young)=domnetvec[Kind]
  rownames(young)=domnetvec[Kind]
  
  # rearrange from unimodal to transmodal (perserve ordering with fc matrices)
  tmrankedyoung<-young[curTmRank,curTmRank]
  tmrankedold<-old[curTmRank,curTmRank]
  
  # write out averaged fc matrices (averaged across age tertiles)
  write.csv(tmrankedyoung,paste('~/Desktop/multiscale/AvgFC_young_Scale',K,'.csv',sep=''))
  write.csv(tmrankedold,paste('~/Desktop/multiscale/AvgFC_old_Scale',K,'.csv',sep=''))
  
  }



```


```{r}
d1 <- data.frame(from="origin", to=paste("group", seq(1,10), sep=""))
d2 <- data.frame(from=rep(d1$to, each=10), to=paste("subgroup", seq(1,100), sep="_"))
hierarchy <- cbind.data.frame(domnetvec,scalesvec)
 
# create a vertices data.frame. One line per object of our hierarchy, giving features of nodes.
vertices <- data.frame(name = unique(c(as.character(hierarchy$domnetvec), as.character(hierarchy$domnetvec))) ) 
mygraph <- graph_from_data_frame( hierarchy, vertices=vertices )
plot(mygraph, vertex.label="", edge.arrow.size=0, vertex.size=2)
ggraph(mygraph, layout = 'dendrogram', circular = FALSE) + 
  geom_edge_link() +
  theme_void()
ggraph(mygraph, layout = 'dendrogram', circular = TRUE) + 
  geom_edge_diagonal() +
  theme_void()
```

```{r}

# NEEDS TO BE RUN AFTER "WITH THE SMOOTHS OVERLAID" CHUNK IN MAIN RMD

#### attempt and trendlines in corrplot, depends on stuff like the covariates call and vectors from the above chunk

# k number of factors for each df/plot, iterative over scales
# SET K DONT TRY TO RUN THIS OVER ALL Ks AT ONCE
K=4

  

  # will use k index to find approp. spot in NetSplines array
  # scratch that, netsplines array is just segreg. we need MORE
  K_start=((K-1)*(K))/2
  K_end=(((K-1)*(K))/2)+K-1
  Kind<-K_start:K_end
  # scale index
  scaleind<-paste('_scale',K,'_',sep='')
  #pull cols at this scale
  
  
  
  
  
  # load in transmodality ordering to try and emulate unimodal -> tranmodal axis
  curTmRank<-order(tmvec[Kind])
  
  
  
  
  
  # for individualized only
  scaleind<-grep(scaleind,colnames(masterdf))
  scaleindivind<-intersect(scaleind,indiv)
  #make df with rows as subjects and columns as scaleindivind
  # fill it with the subject wise values from each column, then bestow colnames
  scale_df<-masterdf[scaleindivind]
  scale_df$age<-masterdf$Age
  # array for 693 gam values for each scaleindivind value (gammarray)
  gamma_ray<-array(0,c(693,length(scaleindivind)))
  
  
  
  segcols_inscaleindivind<-intersect(scaleindivind,nsegcols)
  wincols_inscaleindivind<-intersect(scaleindivind,wincols)
  bwcols_inscaleindivind<-intersect(scaleindivind,bwcol)
  
  
  # array for total psuedocorrplot
  plotarray<-t(array(as.character(paste('plot_',seq(1:(K*K)),sep='')),c(K,K)))
  segplotvec<-array(as.character(paste('Segplot_',seq(1:K),sep='')),c(K))
  
  for(i in 1:K){
    
    ##### SEGREGATION
    # fill in segregs (K segregs, gam array [1:K])
    # get position of this network in broader scale-specific individualized features index 
    posish<-grep(segcols_inscaleindivind[i],scaleindivind)
    # turn this particular FC feature into a gam
    x<-colnames(masterdf[segcols_inscaleindivind][i])
    form<-as.formula(paste("",x,"", covariates, sep=""))
    igam<-gam(formula = form,data=masterdf)
    # extract spline from igam
    derv<-derivatives(igam,term='Age')
    derv<- derv %>%
    # find where to gray out non-sig trends
    mutate(sig = !(0 >lower & 0 < upper))
    derv$sig_deriv = derv$derivative*derv$sig
    # else {
    #minAgeEst[i]<-min(derv$data[derv$sig==T])
    #maxAgeEst[i]<-max(derv$data[derv$sig==T])
    # changed to color sig deriv only
    #derivInfo[i,]=derv$sig_deriv
    forSpline<-predict(igam, data = masterdf, type = "terms")
    # adding mean val because output values are centered
    gamma_ray[,posish]<-forSpline[,3]+coef(igam)[1]
    # use linear slope from straightdforward age cor to color scheme
    scaledf<-cbind(masterdf$Age,masterdf$Sex,masterdf$Motion,masterdf[,scaleindivind[i]])
    # partial spearmans to extrac age relation
    pspear=pcor(scaledf,method='spearman')$estimate
    linear_segcor<-pspear[4]
    if (all(derv$sig==FALSE)){gamcolor='gray'
    } else if (linear_segcor>0) {gamcolor='blue'
    } else if (linear_segcor<0) {gamcolor='red'
    }
    # With the smooths overlaid
    AgeSpan_plotdf4<-data.frame(tmvec,scalesvec,domnetvec,corVecEst,netpropvec,CIgroupingInd)
    LongAgeSpan_plotdf4<-data.frame(sapply(AgeSpan_plotdf4,rep.int,times=693))
    # port age in
    LongAgeSpan_plotdf4$Age<-masterdf$Age/12
    # ports actual splines in
    LongAgeSpan_plotdf4$SegSplines<-forSpline[,3]+coef(igam)[1]
    # will need to change this to input ggplot as a plot within a ggplot vector
    

    
    # TO INCLUDE SEG
    segplot<-ggplot(LongAgeSpan_plotdf4,aes(Age,SegSplines)) +geom_line(size=8,color=gamcolor) +labs(title=paste('Seg. Scale',K,' Net',i,sep=''), x = 'Age') +theme_classic(base_size = 28)+ xlim(c(8,23))+theme(axis.title.x=element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank(),axis.title.y=element_blank(), axis.text.y=element_blank(),axis.ticks.y=element_blank())
    
    
    # fit Seg to Segvector of plot array
    assign(segplotvec[i],segplot)
    
    #### WITHIN   
    # fill in withins (K withins, gam array [K+1:2K])
    # get position of this network in broader scale-specific individualized features index 
    posish<-grep(wincols_inscaleindivind[i],scaleindivind)
    # turn this particular FC feature into a gam
    x<-colnames(masterdf[wincols_inscaleindivind][i])
    form<-as.formula(paste("",x,"", covariates, sep=""))
    igam<-gam(formula = form,data=masterdf)
    # extract spline from igam
    derv<-derivatives(igam,term='Age')
    derv<- derv %>%
    # find where to omit non-sig trends
    mutate(sig = !(0 >lower & 0 < upper))
    derv$sig_deriv = derv$derivative*derv$sig
    #if (all(derv$sig==FALSE)){minAgeEst[i]=0; maxAgeEst[i]=0
    #} else {
    #minAgeEst[i]<-min(derv$data[derv$sig==T])
    #maxAgeEst[i]<-max(derv$data[derv$sig==T])
    # changed to sig deriv only
    #derivInfo[i,]=derv$sig_deriv
    forSpline<-predict(igam, data = masterdf, type = "terms")
    # adding mean val because output values are centered
    gamma_ray[,posish]<-forSpline[,3]+coef(igam)[1]
    # use linear slope from straightdforward age cor to color scheme
    scaledf<-cbind(masterdf$Age,masterdf$Sex,masterdf$Motion,masterdf[,scaleindivind[posish]])
    # partial spearmans to extract age relation
    pspear=pcor(scaledf,method='spearman')$estimate
    linear_wincor<-pspear[4]
    if (all(derv$sig==FALSE)){gamcolor='gray'
    } else if (linear_wincor>0) {gamcolor='blue'
    } else if (linear_wincor<0) {gamcolor='red'
    }
    # With the smooths overlaid
    AgeSpan_plotdf4<-data.frame(tmvec,scalesvec,domnetvec,corVecEst,netpropvec,CIgroupingInd)
    LongAgeSpan_plotdf4<-data.frame(sapply(AgeSpan_plotdf4,rep.int,times=693))
    # port age in
    LongAgeSpan_plotdf4$Age<-masterdf$Age/12
    # ports actual splines in
    LongAgeSpan_plotdf4$WinSplines<-forSpline[,3]+coef(igam)[1]
    # will need to change this to input ggplot as a plot within a ggplot vector
    winplot<-ggplot(LongAgeSpan_plotdf4,aes(Age,WinSplines)) +geom_line(size=8,color=gamcolor) +labs(title='', x = 'Age') +theme_classic(base_size = 28)+ xlim(c(8,23))+theme(axis.title.x=element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank(),axis.title.y=element_blank(), axis.text.y=element_blank(),axis.ticks.y=element_blank())
    
    # plot specifying title code: title=paste('Net. Win. Scale',K,' Net',i,sep='')
    
    # fit WITHIN to diagonals of plot array
    plotarraywin<-diag(plotarray)
    assign(plotarraywin[i],winplot)
    
    # the big betweenchillada 
    #throw another loop in here, one segreg/win value per net but many b/w conn values
    ###  BETWEEN
    # make off diagonal plot array for filling
    # annoying fix for top triangle where it was counting sequentially over columns instead of rows 
    toptri<-t(plotarray)[lower.tri(plotarray)]
    # and bottom
    bottri<-plotarray[lower.tri(plotarray)]
    for (b in 1:length(bwcols_inscaleindivind)){
    # fill in betweens ( ((K-1)*(K))/2 betweens [2K+1: 2K + (((K-1)*(K))/2))])
    posish<-grep(bwcols_inscaleindivind[b],scaleindivind)
    x<-colnames(masterdf[bwcols_inscaleindivind][b])
    form<-as.formula(paste("",x,"", covariates, sep=""))
    igam<-gam(formula = form,data=masterdf)
    # extract spline from igam
    derv<-derivatives(igam,term='Age')
    derv<- derv %>%
    # find where to omit non-sig trends
    mutate(sig = !(0 >lower & 0 < upper))
    derv$sig_deriv = derv$derivative*derv$sig
    #if (all(derv$sig==FALSE)){minAgeEst[i]=0; maxAgeEst[i]=0
    #} else {
    #minAgeEst[i]<-min(derv$data[derv$sig==T])
    #maxAgeEst[i]<-max(derv$data[derv$sig==T])
    # changed to sig deriv only
    #derivInfo[i,]=derv$sig_deriv
    forSpline<-predict(igam, data = masterdf, type = "terms")
    # adding mean val because output values are centered
    gamma_ray[,posish]<-forSpline[,3]+coef(igam)[1]
    # use linear slope from straightdforward age cor to color scheme
    scaledf<-cbind(masterdf$Age,masterdf$Sex,masterdf$Motion,masterdf[,scaleindivind[posish]])
    # partial spearmans to extract age relation
    pspear=pcor(scaledf,method='spearman')$estimate
    linear_wincor<-pspear[4]
    if (all(derv$sig==FALSE)){gamcolor='gray'
    } else if (linear_wincor>0) {gamcolor='blue'
    } else if (linear_wincor<0) {gamcolor='red'
    }
    # With the smooths overlaid
    AgeSpan_plotdf4<-data.frame(tmvec,scalesvec,domnetvec,corVecEst,netpropvec,CIgroupingInd)
    LongAgeSpan_plotdf4<-data.frame(sapply(AgeSpan_plotdf4,rep.int,times=693))
    # port age in
    LongAgeSpan_plotdf4$Age<-masterdf$Age/12
    # ports actual splines in
    LongAgeSpan_plotdf4$BwSplines<-forSpline[,3]+coef(igam)[1]
    # will need to change this to input ggplot as a plot within a ggplot vector
    bwplot<-ggplot(LongAgeSpan_plotdf4,aes(Age,BwSplines)) +geom_line(size=8,color=gamcolor) +labs(title='', x = 'Age') +theme_classic(base_size = 28)+ xlim(c(8,23))+theme(axis.title.x=element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank(),axis.title.y=element_blank(), axis.text.y=element_blank(),axis.ticks.y=element_blank())   
    # fit BETWEEN to off-diagonals of plot array
    # get top triangle off diagonals
    assign(toptri[b],bwplot)
    assign(bottri[b],bwplot)
    }
  }
  

  
# try to rearrange according to transmodality    
ReArAgeEfMat<-plotarray[curTmRank,curTmRank]
ReArAgeSegVec<-segplotvec[curTmRank]
  
# commented out original order in favor of transmodality-ordered 
#plotvec<-c(print(plotarray,quote = F))
plotvec<-c(print(ReArAgeEfMat,quote = F))


plotveccommas<-paste(plotvec,collapse=",")

# Segregation values hopping on the tail end of this train
#SegStragglerscommas<-paste(ReArAgeSegVec,collapse=",")
#plotveccommas_seg<-paste(plotveccommas,',',SegStragglerscommas,sep='')

#ggarrangecommand<-paste('ggarrange(',plotveccommas_seg,',ncol=K,nrow=K+1)',sep='')
# without seg
ggarrangecommand<-paste('ggarrange(',plotveccommas,',ncol=K,nrow=K)',sep='')
#eval(parse(text=ggarrangecommand)) 

```
