---
title: "BwRSqCentric"
author: "Adam"
date: "9/7/2020"
output: github_document
---

```{r include=FALSE}
knitr::read_chunk('~/cbica/projects/pinesParcels/multiscale/scripts/analyses/correlations_over_scalesplot.R')

correlations_over_scales <- function(correlations,title){
  df<-data.frame(correlations)
  ggplot(df,aes(X1,X2)) + geom_step(size=3)+ylab(expression(rho))+
    theme_minimal(base_size = 35)+
    theme(axis.text=element_text(), axis.title = element_text(),panel.grid.minor = element_blank(), plot.title = element_text())+
    xlab("# of Communities") + scale_x_continuous(breaks=seq(2, 30, 4)) +
    ggtitle(title)+
    geom_hline(aes(yintercept=.098), linetype="dashed", col='#ECB602',size=2.5) +
    geom_hline(aes(yintercept=-.098), linetype="dashed", col='#ECB602',size=2.5)+ylim(c(-.4,.4))
}

corEstVec<-function(x){
  # relevant df
  scaledf<-cbind(as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x)
  # partial spearmans to extrac age relation
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[4]
  return(unlist(corest))
}

# Notice this references master E f, which has 5 fewer subjects
corEstVec_EF<-function(x){
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masteref$F1_Exec_Comp_Cog_Accuracy),as.numeric(masteref$Age),as.numeric(masteref$Sex),masteref$Motion,x))
  # partial spearmans to extrac age relation
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  return(unlist(corest))
}


### aaaand one version to just return the residuals
corResidVec<-function(x){
  # relevant df
  scaledf<-cbind(as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x)
  # partial spearmans to extrac age relation
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  return(unlist(corest))
}

DeltaREstVec<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('Age','Sex','Motion','varofint')
  
  # no-age model (segreg ~ sex + motion)
  noAgeGam<-gam(varofint~Sex+Motion,data=scaledf)
  # age-included model for measuring difference
  AgeGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  AgeR<-sqrt(summary(AgeGam)$r.sq)
  NoageR<-sqrt(summary(noAgeGam)$r.sq)
  dif<-AgeR-NoageR
  
  # flag negative r^2s (possible because adjusted R^2)
  if(dif<0){
    print(paste('negative delta adjusted r^2'))
  }
  
  # partial spearmans to extract age relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[4]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)
  
}

# difference in R2
DeltaR2EstVec<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('Age','Sex','Motion','varofint')
  
  # no-age model (segreg ~ sex + motion)
  noAgeGam<-gam(varofint~Sex+Motion,data=scaledf)
  noAgeSum<-summary(noAgeGam)
  # age-included model for measuring difference
  AgeGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  AgeSum<-summary(AgeGam)
  
  dif<-AgeSum$r.sq-noAgeSum$r.sq
  
  # partial spearmans to extract age relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[4]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)
  
}

# same thing but returning chisq test sig. output for FDR correction instead of hard difference
DeltaPEstVec<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('Age','Sex','Motion','varofint')
  
  # no-age model (segreg ~ sex + motion)
  noAgeGam<-gam(varofint~Sex+Motion,data=scaledf)
  # age-included model for measuring difference
  AgeGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noAgeGam,AgeGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])
  
}
# difference in R2 for EF
EFDeltaR2EstVec<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masteref$F1_Exec_Comp_Cog_Accuracy),as.numeric(masteref$Age),as.numeric(masteref$Sex),masteref$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noEFSum<-summary(noEFGam)
  # age-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  EFSum<-summary(EFGam)
  
  dif<-EFSum$r.sq-noEFSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)
  
}

# same thing but returning chisq test sig. output for FDR correction instead of hard difference
EFDeltaPEstVec<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masteref$F1_Exec_Comp_Cog_Accuracy),as.numeric(masteref$Age),as.numeric(masteref$Sex),masteref$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # age-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noEFGam,EFGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])
  
}

```

```{r include=FALSE}
# need to 
source('~/cbica/projects/pinesParcels/multiscale/scripts/analyses/correlations_over_scalesplot_minor.R')
library(shapes)
library(ggplot2)
library(reshape2)
library(dplyr)
library(ggpubr)
library(vroom)
library(data.table)
library(mgcv)
library(ggpointdensity)
library(ppcor)
library(viridis)
library(vroom)
library(boot)
library(sjPlot)
# load in demo
demo<-read.csv('/cbica/projects/pinesParcels/data/pnc_demo.csv')
ageSex<-data.frame(demo$ageAtScan1,as.factor(demo$sex),demo$scanid,demo$bblid)
subjects<-read.csv('/cbica/projects/pinesParcels/data/participants.txt',header = F)

###M MOTION METRIC M###
Rest_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_RestQAData_20170714.csv")
NBack_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_NBACKQAData_20181001.csv")
Idemo_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_idemo_FinalQA_092817.csv")

motmerge<-merge(Rest_Motion_Data,NBack_Motion_Data,by='bblid')
motmerge<-merge(motmerge,Idemo_Motion_Data,by='bblid')
motmerge$Motion <- (motmerge$restRelMeanRMSMotion + motmerge$nbackRelMeanRMSMotion + motmerge$idemoRelMeanRMSMotion)/3;
motiondf<-data.frame(motmerge$bblid,motmerge$Motion)
colnames(motiondf)<-c('bblid','Motion')
###M                 M###

colnames(subjects)<-c("scanid")
colnames(ageSex)<-c("Age","Sex","scanid","bblid")
df<-merge(subjects,ageSex,by="scanid")
df<-merge(df,motiondf,by='bblid')
# community solutions guaged in this iteration
community_vec<-seq(2,30)
```

```{r include=FALSE}
### it's rounded now bb
fc<-vroom('/cbica/projects/pinesParcels/results/aggregated_data/fc/master_fcfeats_rounded.csv')

# take out row number row
fc<-fc[-c(1)]

# isolate shams (although merge should take them out later)
shams<-fc[694:695,]

# AGE
masterdf<-merge(fc,df,by='bblid')

# indicators of processing stream
ind='ind'
gro='gro'
bts='bts'

# indicators of fc feature type
bwi='_bw_FC_'
wini='_win_FC_'
nsegi='_seg_scale'
gsegi='_globseg_scale'

# indices of said indicators
indiv=grep(ind,colnames(masterdf))
group=grep(gro,colnames(masterdf))
basists=grep(bts,colnames(masterdf))
bwcol=grep(bwi,colnames(masterdf))
wincols=grep(wini,colnames(masterdf))
nsegcols=grep(nsegi,colnames(masterdf))
gsegcols=grep(gsegi,colnames(masterdf))
```

```{r include=FALSE}

GBw=vroom('/cbica/projects/pinesParcels/results/aggregated_data/fc/globalBw_fcfeats.csv')
GWin=vroom('/cbica/projects/pinesParcels/results/aggregated_data/fc/globalWin_fcfeats.csv')

colnames(GBw)<-unlist(GBw[1,])
colnames(GWin)<-unlist(GWin[1,])

# identical parsing as above

GBw<-data.frame(GBw)
GWin<-data.frame(GWin)

# round ridiculous number of decimal points
GBw[] <- lapply(GBw, function(x) {
  if(is.character(x)) round(as.numeric(as.character(x)),digits=3) else x
})
GWin[] <- lapply(GWin, function(x) {
  if(is.character(x)) round(as.numeric(as.character(x)),digits=3) else x
})

# isolate shams (although merge should take them out later)
shams<-fc[694:695,]

# set subjects column to bblid
colnames(GWin)[1]<-'bblid'
colnames(GBw)[1]<-'bblid'
GWindf<-merge(GWin,df,by='bblid')
GBwdf<-merge(GBw,df,by='bblid')

### isolate global columns
gWincols<-grep("globWin",colnames(GWindf))
gBwcols<-grep("globBw",colnames(GBwdf))
#paste("Indices of global segregation columns at ",gsegcols)

### plot mean global seg over scales by age
# 2:30 is ind, 5455:5483 is group
indglobWin<-cbind(GWindf$bblid,GWindf$Age/12,GWindf$Sex,GWindf$Motion,GWindf[,2:30])
indglobBw<-cbind(GBwdf$bblid,GBwdf$Age/12,GBwdf$Sex,GBwdf$Motion,GBwdf[,2:30])

# set colnames
colnames(indglobWin)[1:4]<-c("bblid", "Age","Sex","Motion")
colnames(indglobBw)[1:4]<-c("bblid", "Age","Sex","Motion")
colnames(indglobWin)[5:33]<-as.character(2:30)
colnames(indglobBw)[5:33]<-as.character(2:30)
indglobWin$Sex<-as.factor(indglobWin$Sex)
indglobBw$Sex<-as.factor(indglobBw$Sex)

# regress effect of age out on sex and motion
indglobWin_motSexC<-indglobWin
indglobBw_motSexC<-indglobBw

for (i in 5:33){
  WCLM<-lm(indglobWin[,i]~Motion+Sex,data=indglobWin)
  indglobWin_motSexC[,i]<-WCLM$residuals
  BWCLM<-lm(indglobBw_motSexC[,i]~Motion+Sex,data=indglobBw)
  indglobBw_motSexC[,i]<-BWCLM$residuals
  # add in mean for more interpretable values
  indglobWin_motSexC[,i]<-indglobWin_motSexC[,i]+mean(indglobWin[,i])
  indglobBw_motSexC[,i]<-indglobBw_motSexC[,i]+mean(indglobBw[,i])
}


# melt it
mindglobwin<-melt(indglobWin_motSexC, id=c(1,2,3,4))
mgroglobbw<-melt(indglobBw_motSexC, id=c(1,2,3,4))


WinAll<-ggplot(data=mindglobwin,aes(x=as.numeric(as.character(variable)),y=value,group=bblid,color=Age)) +geom_line(alpha = 0.12)+scale_color_gradientn(colors=c("yellow","purple")) + theme_minimal(base_size = 28)+labs(title="M/S-Regressed Glob. Within - Individ. Partitions") + scale_x_continuous(name ="# of Communitites",  breaks=seq(2, 30, 4))+ylab("Global Within")

BwAll<-ggplot(data=mgroglobbw,aes(x=as.numeric(as.character(variable)),y=value,group=bblid,color=Age)) +geom_line(alpha = 0.12)+scale_color_gradientn(colors=c("yellow","purple")) + theme_minimal(base_size = 28)+labs(title="M/S-Regressed Glob. Bw - Individ. Partitions") + scale_x_continuous(name ="# of Communitites",  breaks=seq(2, 30, 4))+ylab("Global Between")

### Now with motion + sex control
# 29 for scales studied
ind_GWincors<-matrix(0,29,2)
ind_GWincors[,1]<-2:30
ind_GBwcors<-matrix(0,29,2)
ind_GBwcors[,1]<-2:30

for (i in 1:29){
  # i+4 because first column is scanid, second is age, third is sex, 4th is motion
  #print(ggplot(indglobWin_motSexC,aes(Age,indglobWin_motSexC[,i+4])) + geom_point() + geom_smooth() +ylab(paste("Ind Global Win at Scale", i+1)))
  #print(ggplot(indglobBw_motSexC,aes(Age,indglobBw_motSexC[,i+4])) + geom_point() + geom_smooth() +ylab(paste("Ind Global BW at Scale", i+1)))
# relevant df
  Winscaledf<-cbind(indglobWin$Age,indglobWin$Sex,indglobWin$Motion,indglobWin[,i+4])
  Bwscaledf<-cbind(indglobBw$Age,indglobBw$Sex,indglobBw$Motion,indglobBw[,i+4])
  # partial spearmans to extrac age relation
  pspear=pcor(Winscaledf,method='spearman')$estimate
  ind_GWincors[i,2]<-pspear[4]
  pspear=pcor(Bwscaledf,method='spearman')$estimate
  ind_GBwcors[i,2]<-pspear[4]
}


WinCors<-correlations_over_scales(ind_GWincors,"Global WithinCon Age Correlation")

BwCors<-correlations_over_scales(ind_GBwcors,"Global BetweenCon Age Correlation")

### compare explanatory power of scales vs. ratio

# melt dataframe
melted_gBw<-melt(indglobBw,id=c(1,2,3,4))
# factor resets 2 to first factor and so forth, plus 1 to correct
melted_gBw$Scale<-as.numeric(melted_gBw$variable)+1
melted_gBw$bblid<-as.factor(melted_gBw$bblid)
modelr<-gamm(value~Motion+Sex+ti(Age,k=4)+ti(Scale,k=4)+ti(Age,Scale,k=4),random=list(bblid=~1),data=melted_gBw)
model<-gam(value~Motion+Sex+ti(Age,k=4)+ti(Scale,k=4)+ti(Age,Scale,k=4),data=melted_gBw)
# port in this ratio from longer statsnfigs calc.
##ratvec<-withinBetweenClassConVec[2:30]
#make a long format vector for the long format dataframe
# model for age*scale
##ratvec_long<-rep(ratvec,each=693)
##melted_gBw$ratvec<-ratvec_long

# model for age*ratio
##model2r<-gamm(value~Motion+Sex+ti(Age,k=4)+ti(ratvec,k=4)+ti(Age,ratvec,k=4),random=list(bblid=~1),data=melted_gBw)
##model2<-gam(value~Motion+Sex+ti(Age,k=4)+ti(ratvec,k=4)+ti(Age,ratvec,k=4),data=melted_gBw)

# complete model
##model3r<-gamm(value~Motion+Sex+ti(Age,k=4)+ti(ratvec,k=4)+ti(Scale,k=4)+ti(Age,ratvec,k=4)+ti(Age,Scale),random=list(bblid=~1),data=melted_gBw)
```

```{r}

# global average network property relationship to age
#ggarrange(WinAll,WinCors,BwAll,BwCors)
BwAll
BwCors

#### bootstrapping section
# intialize bootstrap CI upper and lower bounds
ind_GBwcors_highCI<-matrix(0,29,2)
ind_GBwcors_highCI[,1]<-2:30
ind_GBwcors_lowCI<-matrix(0,29,2)
ind_GBwcors_lowCI[,1]<-2:30



ind_GBwcors[,1]<-2:30


# write function to return cor - d is combined dataframe (age, sex, motion and glob b/w at one particular scale)
returnCor<-function(d,i){
  # i guess this sets I to the bootstrapped sample 
  d2<-d[i,]
  pspear=pcor(d2,method='spearman')$estimate
  return(pspear[4])
}

returnLmCoef<-function(d,i){
  # i guess this sets I to the bootstrapped sample 
  d2<-d[i,]
  pspear=lm(X1~X2*X3,d2)
  coef(pspear)
}

set.seed(1)
for (i in 1:29){
  print(i)
  Bwscaledf<-cbind(indglobBw$Age,indglobBw$Sex,indglobBw$Motion,indglobBw[,i+4])
  # change to back to 10K for more thorough resamp.
  bootparcor<-boot(Bwscaledf,returnCor,R=10)
  bootCIs<-boot.ci(bootparcor,type='norm')
  ind_GBwcors_highCI[i,2]<-bootCIs$normal[3]
  ind_GBwcors_lowCI[i,2]<-bootCIs$normal[2]
}
correlations_over_scales(ind_GBwcors_highCI,"Global BetweenCon Age Correlation")
correlations_over_scales(ind_GBwcors_lowCI,"Global BetweenCon Age Correlation")

# merge em together for plot
estAndBootStrapped<-data.frame(ind_GBwcors[,1],ind_GBwcors[,2],ind_GBwcors_highCI[,2],ind_GBwcors_lowCI[,2])
colnames(estAndBootStrapped)<-c('Scale','AgeCor','upperCI','lowerCI')
ggplot(data=estAndBootStrapped,aes(x=Scale,y=AgeCor))+geom_line()+geom_line(aes(x=Scale,y=upperCI,color='UpperCI'))+geom_line(aes(x=Scale,y=lowerCI,color='LowerCI'))+theme_classic()+ggtitle('Age x Global B/w Con')

# full model with subj intercept
long_Bwscaledf<-data.frame(indglobBw$bblid,indglobBw$Age,indglobBw$Sex,indglobBw$Motion,indglobBw[,5:33])
melted_Bwscaledf<-melt(long_Bwscaledf,id=c(1,2,3,4))
colnames(melted_Bwscaledf)<-c('bblid','Age','Sex','Motion','Scale','value')
melted_Bwscaledf$Scale<-rep(seq(from=2,to=30),each=693)

globModAge<-lm(value~Age*log(Scale)+Motion+Sex+(1|bblid),melted_Bwscaledf)



```


```{r include=FALSE}
### Get in Consensus-reference atlas correspondence
rac<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_yCorrespondence_overscales.csv',stringsAsFactors = F)
scalesvec<-as.numeric(rac[2,])
domnetvec<-as.factor(rac[3,])
netpropvec<-as.numeric(rac[4,])

# 17 network version
### Get in Consensus-reference atlas correspondence
rac17<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_y17Correspondence_overscales.csv',stringsAsFactors = F)
scalesvec17<-as.numeric(rac17[2,])
domnetvec17<-as.factor(rac17[3,])
netpropvec17<-as.numeric(rac17[4,])


#### read in transmodality
tm<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_transmodality_overscales.csv',stringsAsFactors = F)
colnames(tm)<-tm[1,]
# aaaand remove it
tm<-tm[-c(1),]
tmvec<-as.numeric(tm)

#### read in grad2
occm<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_grad2_overscales.csv',stringsAsFactors = F)
colnames(occm)<-occm[1,]
# aaaand remove it
occm<-occm[-c(1),]
occvec<-as.numeric(occm)

# distribution of transmodality across networks across scales (derived from group consensus)
hist(tmvec,12,xlab="Transmodality",ylab="Count",ylim=c(0,70), main=NULL,col="grey")

# use median transmodality value to split relatively bimodal distribution
medtrans<-median(tmvec)
# equivalent vector to be overwritten with binary classification of transmodality
tmclass<-tmvec
for (i in 1:length(tmclass)){
  if (tmvec[i]<= medtrans){
    tmclass[i]='unimodal'
  }else{
    tmclass[i]='transmodal'
  }
}
```


```{r}

### Using a ton of index combinations 
indiv_bwcols_ind<-intersect(bwcol,indiv)
individ_scalebybw_df<-masterdf[,indiv_bwcols_ind]
indiv_wincols_ind<-intersect(wincols,indiv)
individ_scalebywin_df<-masterdf[,indiv_wincols_ind]
# to later use wincolname -> bwcolname mapping to extrapolate if if network is unimodal or transmodal along bwcol indices
wincolnames<-colnames(individ_scalebywin_df)
bwcolnames<-colnames(individ_scalebybw_df)

# empty array to populate with b/w connectivity age cors (b/w to unimodal, b/w to transmodal, b/w to aggregate, b/w to aggregate p values, and K and N and Modality just to confirm we are matching)
bwAgeCorVecs<-matrix(0,464,6)
# empty array for each nets average b/w con across subjects
bwAvgCon<-matrix(0,693,464)

# loop over connectivities to-unimodal then to-transmodal
modalloopvar=c('unimodal','transmodal')
for (i in 1:2){
  print(modalloopvar[i])
  # index "the other" (dystopian)
  modalloopvar_other=modalloopvar[modalloopvar!=(modalloopvar[i])]
  # extract which of 1:464 network mappings match the modalitity of this loop
  modalindices=which(tmclass %in% modalloopvar[i])
  # loop over each scale
    for (K in 2:30){
    # Make index of where values from this K should go
      K_start=((K-1)*(K))/2
      K_end=(((K-1)*(K))/2)+K-1
      Kind<-K_start:K_end
      bwAgeCorVecs[Kind,4]=K
    
    # index which values are at this scale
    scaleStr=paste('scale',K,'_',sep='')
    scaleCols_inds=grep(scaleStr,colnames(masterdf))
    scaleK_bw_indivi_cols_inds<-intersect(indiv_bwcols_ind,scaleCols_inds)
    # extract within and between colnames at this scale for within->b/w binarized transmodality mapping
    wincolnames_thisScale_inds<-grep((paste('scale',K,'_',sep='')),wincolnames)
    wincolnames_thisScale=wincolnames[wincolnames_thisScale_inds]
    bwcolnames_thisScale_inds<-grep((paste('scale',K,'_',sep='')),bwcolnames)
    bwcolnames_thisScale=bwcolnames[bwcolnames_thisScale_inds]
    
    # This was to double check that the "scale" grepping was selective enough
    # print(paste(scaleStr,'number of features:',length(bwcolnames_thisScale)))
  # one weird trick to get binarized transmodality class vector for same scale (Doctors hate him!)
    # tm naming aligns with wincon naming
    tmclasses_thisScale<-tmclass[wincolnames_thisScale_inds]
    # extract the network number of each network at this scale in same order as tmclasses_thisScale
    wincolNamesSplit<-strsplit(wincolnames_thisScale,"_net")
    wincolNames_net<-sapply(wincolNamesSplit, "[[" , 2)
    # mini matching vectors with network label at this scale in one col and transmodality binarization in the other
    tmMatchingVecs<-cbind(wincolNames_net,tmclasses_thisScale)
    # remove scale number from strings so we're not picking up on those
    bwcolnames_thisScale_split<-strsplit(bwcolnames_thisScale,"nets")
    bwnetnames_thisScale<-wincolNames_net<-sapply(bwcolnames_thisScale_split, "[[" , 2)
    # add another fucking set of underscores to all of these colnames so 1's dont pick up 10s
    bwnetnames_thisScale_extended<-paste('ind_bw_FC_scale',K,'_nets_',bwnetnames_thisScale,'_',sep='')
    # extra goddamn undercores have to go here and be removed later
    bwcolnames_thisScale_split<-strsplit(bwcolnames_thisScale,"nets")
    # to be matched in all-networks-at-this-scale loop
    # now as we descend into the third circle of for-loop hell, we find the guy from man vs.food being eaten alive by cerberus
    for (N in 1:K){
      # generate index for where values for this network at this scale should reside
      # start from K index
      Nind<-Kind[N]
      bwAgeCorVecs[Nind,5]=N
      # get index for this N in terms of masterdf (collapse | to match multiple patterns)
      Ncolname<-grep(as.character(paste('_',N,'_',sep='')),bwnetnames_thisScale_extended,value=T)
      # need to add "_" before and after each number so I can select for '_N_' and not pick up teens digits with 1, 20s with 3, 15 and 25 with 5, etc.
      # determine if this network is transmodal or unimodal
      NModality<-tmMatchingVecs[,2][[N]]
      ########bwAgeCorVecs[Nind,6]<-NModality
      NotNModality<-modalloopvar[modalloopvar!=NModality]
      matchvec<-grep(NModality,tmclasses_thisScale)
      # remove self
      matchvec<-matchvec[matchvec!=N]
      # build index of matching modalities to reference masterdf (collapse | to match multiple patterns)
      matchTruncColName<-grep(as.character(paste('_',matchvec,'_',sep='',collapse="|")),Ncolname,value=T)
      # remove first and last characters now that we are specific
      #matchTruncColName<-sub('.$','',matchTruncColName)
      #matchTruncColName<-sub('.','',matchTruncColName)
      # deal with weird thing where empty space was being grepped because of its aspecificity at coarse scales
      if(length(matchTruncColName)==0){
        matchTruncColName[1]='CANTSEEME'
      }
      match_NetN_scaleK_bw_indivi_cols_ind_within_other_ind<-grep(as.character(paste(matchTruncColName,collapse="|")),bwnetnames_thisScale_extended)
      match_NetN_scaleK_bw_indivi_cols_names<-bwcolnames_thisScale[match_NetN_scaleK_bw_indivi_cols_ind_within_other_ind]
      # deep-sea grepping the whole paste and pipe thing is just to deal with character vectors instead of single patterns
      
      # deal with weird thing where empty space was being grepped because of its aspecificity
      if(length(match_NetN_scaleK_bw_indivi_cols_names)==0){
        match_NetN_scaleK_bw_indivi_cols_names[1]='CANTSEEME'
      }
      #################
      #### NEED TO ADD UNDERSCORE TO AFTERPORTION SO IT DOESNT PICK UP 1_20 when looking for 1_2 #########
      ##########
      #bwcolnames_thisScale<-paste(bwcolnames_thisScale,'_',sep='')
      #match_NetN_scaleK_bw_indivi_cols_names<-paste(match_NetN_scaleK_bw_indivi_cols_names,'_',sep='')
      
      # added a faux '_' to end of column to col names can more selectively match numbers (not picking up on 20 when looking for 2, 2_ and 20_ more distinct)
      match_NetN_scaleK_bw_indivi_cols_ind<-grep(as.character(paste(match_NetN_scaleK_bw_indivi_cols_names,'_',sep='',collapse="|")),paste(colnames(masterdf),'_',sep=''))
    
      ###############
      ######## find opposite modality in this scale ################
      ###############
      
      oppositevec<-grep(NotNModality,tmclasses_thisScale)
      
      # build index of NON-matching modalities to reference masterdf (collapse | to match multiple patterns)
      unmatchTruncColName<-grep(as.character(paste('_',oppositevec,'_',sep='',collapse="|")),Ncolname,value=T)
      # search for string in limited bwcolnames at this scale so as not to invite other scales into this grep party
      # remove first and last characters now that we are specific
      #unmatchTruncColName<-sub('.$','',unmatchTruncColName)
      #unmatchTruncColName<-sub('.','',unmatchTruncColName)
      unmatch_NetN_scaleK_bw_indivi_cols_names<-grep(as.character(paste(unmatchTruncColName,collapse="|")),bwnetnames_thisScale_extended,value=T)
      
      # deep-sea grepping the whole paste and pipe thing is just to deal with character vectors instead of single patterns
      unmatch_NetN_scaleK_bw_indivi_cols_ind_within_other_ind<-grep(as.character(paste(unmatch_NetN_scaleK_bw_indivi_cols_names,collapse="|")),bwnetnames_thisScale_extended)
      unmatch_NetN_scaleK_bw_indivi_cols_names<-bwcolnames_thisScale[unmatch_NetN_scaleK_bw_indivi_cols_ind_within_other_ind]
      unmatch_NetN_scaleK_bw_indivi_cols_ind<-grep(as.character(paste(unmatch_NetN_scaleK_bw_indivi_cols_names,'_',sep='',collapse="|")),paste(colnames(masterdf),'_',sep=''))
      
      
      # doublecheck that they are mutually exclusive (+1 because self-reference gets removed)
    #  if(length(tmclasses_thisScale)!=length(matchvec)+length(oppositevec)+1){
   #     print('You done goofed, internet police are on their way')
     # }
      if(length(tmclasses_thisScale)!=length(match_NetN_scaleK_bw_indivi_cols_ind)+length(unmatch_NetN_scaleK_bw_indivi_cols_ind)+1){
        print('Names dont add up chief')
        paste('match numbas', length(match_NetN_scaleK_bw_indivi_cols_ind), length(match_NetN_scaleK_bw_indivi_cols_names))
        paste('unmatch numbas', length(unmatch_NetN_scaleK_bw_indivi_cols_ind), length(unmatch_NetN_scaleK_bw_indivi_cols_names))
        stopifnot(length(tmclasses_thisScale)==length(match_NetN_scaleK_bw_indivi_cols_ind)+length(unmatch_NetN_scaleK_bw_indivi_cols_ind)+1)
      }
      unmatch_NetN_scaleK_bw_indivi_cols_ind
      # Reset these to NULL for each loop over N for equivalent looping
      
      
      # if it matches the modality being aggregated in the grandparent loop, we wish to only assay its connections to same-modality networks
      if (NModality==modalloopvar[i] && length(matchvec>0)){
        avg_bw_agecor<-NULL
        # get average value of b/w but same modality connectivity
        avg_bw_same<-rowMeans(masterdf[,match_NetN_scaleK_bw_indivi_cols_ind,drop=F])
        # get mean agecor with matching networks
        avg_bw_agecor<-corEstVec(avg_bw_same)
      } else if (NModality!=modalloopvar[i]) {  
        avg_bw_agecor<-NULL
        # get average value of b/w but same modality connectivity
        avg_bw_dif<-rowMeans(masterdf[,unmatch_NetN_scaleK_bw_indivi_cols_ind, drop=F])
        # get mean agecor with non-matching networks
        avg_bw_agecor<-corEstVec(avg_bw_dif)
      } else if (NModality==modalloopvar[i] && (exists("matchvec[1]"))=='FALSE') {
        # easily findable index for cells which should not be filled (i.e., there is no "to unimodal connectivity" for the only unimodal networks at any scale)
        avg_bw_agecor<-999
      }
      # if it does not match the modality of the grandparent loop, we wish go assay its connections to opposite-modality networks
      bwAgeCorVecs[Nind,i]=avg_bw_agecor
    # get average bw network connectivty age correlation for this network at this scale
      both=cbind(masterdf[,match_NetN_scaleK_bw_indivi_cols_ind],masterdf[,unmatch_NetN_scaleK_bw_indivi_cols_ind, drop=F])
      avg_bw=rowMeans(both)
      # for bw-based gams later - convert all b/w cons for a net to avg b/w for each subj
      bwAvgCon[,Nind]=avg_bw
      avg_bw_coarse_agecor<-DeltaR2EstVec(avg_bw)
      avg_bw_coarse_agecorP<-DeltaPEstVec(avg_bw)
      bwAgeCorVecs[Nind,3]=unlist(avg_bw_coarse_agecor)
      bwAgeCorVecs[Nind,4]=unlist(avg_bw_coarse_agecorP)
    }
    # Print out ratio of transmodal to unimodal at this scale
    unilength=length(tmclasses_thisScale[tmclasses_thisScale=='unimodal'])
    translength=length(tmclasses_thisScale[tmclasses_thisScale=='transmodal'])
    print(paste('uni to trans ratio:', unilength/translength))
  }
  
}
bwAgeCorVecs<-data.frame(bwAgeCorVecs)
```

```{r}


# analyze between network connectivities' couplings with age by transmodality
colnames(bwAgeCorVecs)<-c('bw_to_unimodal','bw_to_transmodal','avg_bw','avg_bwP','K','N')
############ analyze contribution of avg b/w network connectivities' age couplings by scale and transmodality #############

#fdr correct p vals
bwAgeCorVecs$avg_bwP<-p.adjust(bwAgeCorVecs$avg_bwP,method='fdr')

bwdf<-data.frame(tmvec,scalesvec,domnetvec,netpropvec,bwAgeCorVecs$avg_bw,bwAgeCorVecs$bw_to_unimodal,bwAgeCorVecs$bw_to_transmodal,bwAgeCorVecs$avg_bwP)

netLM<-lm(bwAgeCorVecs.avg_bw~tmvec+scalesvec,bwdf)

####
# avg b/w
avgbw_age_tm<-ggplot(bwdf,aes(tmvec,bwAgeCorVecs.avg_bw,color=domnetvec,alpha=netpropvec^2)) + geom_point(size=6)+ scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Transmodality") + ylab(expression(paste(Delta,R^2[adj]))) +theme_classic(base_size = 28) + ggtitle('B/w Variance Captured by Age') +guides(alpha=FALSE,color=guide_legend(title="Maximal Y7 Overlap"))+theme(legend.position="top")

avgbw_age_scale<-ggplot(bwdf,aes(tmvec,bwAgeCorVecs.avg_bw,color=scalesvec)) + geom_point(size=6) +labs(title='B/w Variance Captured by Age', x = 'Transmodality', y = expression(paste(Delta,R^2[adj])), color="Topological \nScale")+theme_classic(base_size = 28)+ ylim(-.5,.5)+ scale_colour_gradient(low="#55185D", high="#ECB602")+theme(legend.position="top",legend.key.width = unit(2.5, "cm"))
####

####
# b/w to unimodal
unibw_age_tm<-ggplot(bwdf,aes(tmvec,bwAgeCorVecs.bw_to_unimodal,color=domnetvec,alpha=netpropvec^2)) + geom_point(size=6)+ scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Transmodality") + ylab("AgeBWUCor") +theme_classic(base_size = 28) + ggtitle('Correlation of B/w unimodal con and Age over All Networks')+ ylim(-.5,.5)

unibw_age_scale<-ggplot(bwdf,aes(tmvec,bwAgeCorVecs.bw_to_unimodal,color=scalesvec)) + geom_point(size=6) + xlab("Transmodality") + ylab("AgeBWUCor")+theme_classic(base_size = 28)+ ylim(-.5,.5)
####

####
# b/w to transmodal
transbw_age_tm<-ggplot(bwdf,aes(tmvec,bwAgeCorVecs.bw_to_transmodal,color=domnetvec,alpha=netpropvec^2)) + geom_point(size=6)+ scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Transmodality") + ylab("AgeBWTCor") +theme_classic(base_size = 28) + ggtitle('Correlation of B/w transmodal con and Age over All Networks')+ ylim(-.5,.5)

transbw_age_scale<-ggplot(bwdf,aes(tmvec,bwAgeCorVecs.bw_to_transmodal,color=scalesvec)) + geom_point(size=6) + xlab("Transmodality") + ylab("AgeBWTCor")+theme_classic(base_size = 28)+ ylim(-.5,.5)
####

#ggarrange(avgbw_age_tm,unibw_age_tm,transbw_age_tm,avgbw_age_scale,unibw_age_scale,transbw_age_scale)
#avgbw_age_tm
#unibw_age_tm
#transbw_age_tm
avgbw_age_scale
unibw_age_scale
transbw_age_scale

#17 network version
#bwdf17<-data.frame(tmvec,scalesvec,domnetvec17,netpropvec17,bwAgeCorVecs$avg_bw,bwAgeCorVecs$bw_to_unimodal,bwAgeCorVecs$bw_to_transmodal)

#ggplot(bwdf17,aes(tmvec,bwAgeCorVecs.avg_bw,color=domnetvec17,alpha=netpropvec17^2)) + scale_color_manual(values=c('#dc8303','#8d2049','#596a85','#2d9a3d','#007938','#d9e200','#bc0943','#2b1f67','#48593a','#91a967','#4183a8','#00bb89','#3245a3','#9e3ca2','#eb75b3','#68126f','#d1001c')) + xlab("Transmodality") + ylab(expression(paste(Delta,R^2[adj]))) +theme_classic(base_size = 28) + geom_point(size=4,aes(tmvec,bwAgeCorVecs.avg_bw)) + ggtitle('Age Effect by Transmodality')

# version with fdr p > 0.05 removed
bwdf$bwAgeCorVecs.cavg_bw<-bwdf$bwAgeCorVecs.avg_bw
bwdf$bwAgeCorVecs.cavg_bw[bwdf$bwAgeCorVecs.avg_bwP>0.05]=0

Corrected_avgbw_age_tm<-ggplot(bwdf,aes(tmvec,bwAgeCorVecs.cavg_bw,color=domnetvec,alpha=netpropvec^2)) + geom_point(size=6)+ scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Transmodality") + ylab(expression(paste(Delta,R^2[adj]))) +theme_classic(base_size = 28) + ggtitle('B/w Variance Captured by Age') +guides(alpha=FALSE,color=guide_legend(title="Maximal Y7 Overlap"))+theme(legend.position="top")
```


```{r include=FALSE}
# age effect duration w/ b/w
# long df - replaced indexed master df with bwAvgCon, because bwAvgCon yields network-wise measures vs. pairwise
long_precursor<-data.frame(masterdf$bblid,masterdf$Age,masterdf$Sex,masterdf$Motion,bwAvgCon)
melt_long<-melt(long_precursor,id=c(1,2,3,4))
tmvecRepped<-rep(tmvec,each=693)
domnetvecRepped<-rep(domnetvec,each=693)
melt_long$transmodality<-tmvecRepped
melt_long$dominantYeo<-domnetvecRepped
saveRDS(melt_long,file = '~/Desktop/Long_bblidAgeSexMotionAvgBw.rds')
```


```{r}
# delineate age trajectories of every net.
library(gratia)
library(dplyr)
library(svglite)
library(cowplot)
library(mgcv)
library(viridis)

covariates=" ~s(Age,k=3)+Sex+Motion"   

minAgeEst<-rep(0,length=length(masterdf[,indiv_nsegcols_ind]))
maxAgeEst<-rep(0,length=length(masterdf[,indiv_nsegcols_ind]))

derivInfo<-array(0,dim=c(464,200))
NetSplines<-array(0,dim=c(464,693))                  

#
# borrowing colnames from indiv_nsegcols to keep network/scale ordering/mappings
colnames(bwAvgCon)<-gsub("_seg_","_avgBw_",colnames(masterdf[,indiv_nsegcols_ind]))
bwAvgCondf<-data.frame(bwAvgCon)

#add on covariate columns
bwAvgCondf$Age<-masterdf$Age
bwAvgCondf$Sex<-masterdf$Sex
bwAvgCondf$Motion<-masterdf$Motion

#for i in 464, -3 because age sex and motion columns sit at the end
for (i in 1:(length(bwAvgCondf)-3)){
  # borrowing colnames from indiv_nsegcols to keep network mappings
  x<-colnames(bwAvgCondf[i])
  form<-as.formula(paste("",x,"", covariates, sep=""))
  igam<-gam(formula = form,data=bwAvgCondf)
  derv<-derivatives(igam,term='Age')
  derv<- derv %>%
  mutate(sig = !(0 >lower & 0 < upper))
  derv$sig_deriv = derv$derivative*derv$sig
  if (all(derv$sig==FALSE)){minAgeEst[i]=0; maxAgeEst[i]=0
  } else {
  minAgeEst[i]<-min(derv$data[derv$sig==T])
  maxAgeEst[i]<-max(derv$data[derv$sig==T])
  # changed to sig deriv only 7/10/20
  derivInfo[i,]=derv$sig_deriv
  forSpline<-predict(igam, data = masterdf, type = "terms")
  # adding mean val because output values are centered
  colOfInt<-unlist(bwAvgCondf[,i])
  NetSplines[i,]<-forSpline[,3]+coef(igam)[1]
  
  # set to just print out networks that have an average b/w con of over 0
  #if (mean(colOfInt)>0){
  #  print(paste(x,mean(colOfInt)))
  #}
  }
  
  # set to print deriv duration
  ###cat(sprintf("\nSig change: %1.2f - %1.2f\n",minAgeEst[i],maxAgeEst[i]))
}

# years format
minAgeEst<-minAgeEst/12
maxAgeEst<-maxAgeEst/12

CIgroupingInd<-as.factor(1:464)

#convert to years for more interpretable slope
derivInfo<-derivInfo*12





# get a vector of the agespan split into 200 to match the deriv vals
agerange<-range(masterdf$Age)/12
agerange200<-seq(agerange[1],agerange[2],length.out = 200)

AgeSpan_plotdf2<-data.frame(tmvec,scalesvec,domnetvec,corVecEst,netpropvec,CIgroupingInd)



# needs to be converted to repeat 464 times before progressing to next age bracket
agerange200464<-array(dim=c(200*464,1))
for (i in 1:length(agerange200)){
agerange200464[((464*i)-463):(464*i)]<-rep(agerange200[i],464)
}

# now we need deriv vals of same format, but they will change for every network at every age bracket. Using sig change should take care of whitening out zeros
deriv200464<-array(dim=c(200*464,1))
for (i in 1:length(agerange200)){
deriv200464[((464*i)-463):(464*i)]<-derivInfo[,i]
}

LongAgeSpan_plotdf2<-data.frame(sapply(AgeSpan_plotdf2,rep.int,times=200))
LongAgeSpan_plotdf2$agespans<-agerange200464
LongAgeSpan_plotdf2$derivs<-deriv200464

breaks=c(-.02,-.01,0,0.01,0.02)


# older version
###ggplot(LongAgeSpan_plotdf2,aes(agespans,tmvec,color=derivs,group=CIgroupingInd)) +geom_line(size=10,alpha=.8) +labs(title='Network Segregation Effect Span', x = 'Age', y = 'Transmodality') +theme_classic(base_size = 58)+ xlim(c(8,23))+ scale_colour_gradientn(colours=c('#ff0a0a','#ff9191','white','#8585ff','#0b0bff'),values = c(0,.05,.265,.615,1),breaks=breaks, labels = breaks,name="Change Per Year")+theme(legend.position="top",legend.key.width = unit(4, "cm"))


Bwspan<-ggplot(LongAgeSpan_plotdf2,aes(agespans,tmvec,color=derivs,group=CIgroupingInd)) +geom_line(size=10) +labs(title='External Connectivity Effect Span', x = 'Age', y = 'Transmodality') +theme_classic(base_size = 58)+ xlim(c(8,23))+ scale_colour_gradientn(colours=c('#0b0bff','#8585ff','white','#ff9191','#ff0a0a'),values = c(0,.25,.5,.75,1),breaks=breaks, labels = breaks,limits=c(-.005,0.005),name="Change Per Year")+theme(legend.position="top",legend.key.width = unit(5, "cm"))+ylim(c(min(tmvec),max(tmvec)))





# with yeo color scheme instead
LongAgeSpan_plotdf2$domnetvec<-as.factor(LongAgeSpan_plotdf2$domnetvec)
#LongAgeSpan_plotdf2$derivs[abs(LongAgeSpan_plotdf2$derivs) < 0.002] <- 0


y7ver<-ggplot(LongAgeSpan_plotdf2,aes(agespans,tmvec,color=domnetvec,group=CIgroupingInd,alpha=abs(derivs))) +geom_line(size=10,aes(agespans,tmvec)) +labs(title='External Connectivity Effect Span', x = 'Age', y = 'Transmodality') +theme_classic(base_size = 58)+ xlim(c(8,23))+ scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068'),name="Maximal Y7 Overlap")+scale_alpha_continuous(range=c(0,1))+theme(legend.position="top",legend.key.width = unit(5, "cm"))+ylim(c(min(tmvec),max(tmvec)))
```

```{r}
#b/w EF relations at community level

#subjbehav<-read.csv("/cbica/projects/pinesParcels/data/n713_Behavior_20181219.csv")
subjbehav<-read.csv("~/Downloads/n9498_cnb_factor_scores_fr_20170202.csv")
#ef<-data.frame(subjbehav$F1_Exec_Comp_Cog_Accuracy,subjbehav$bblid)
ef<-data.frame(subjbehav$NAR_F1_Exec_Comp_Cog_Accuracy,subjbehav$bblid)
colnames(ef)<-c('F1_Exec_Comp_Cog_Accuracy','bblid')
# merge in
masteref<-merge(masterdf,ef,by='bblid')


# difference in R^2
BW_R2VecEst<-as.numeric(lapply(bwAvgCondf[,1:464],EFDeltaR2EstVec))
BW_pVecEst<-as.numeric(lapply(bwAvgCondf[,1:464],EFDeltaPEstVec))
corrected<-p.adjust(BW_pVecEst,method='fdr')

# get indes of where fdr p < 0.05 so we can get some of the noisy relations out
cBW_R2VecEst<-BW_R2VecEst
cBW_R2VecEst[corrected>0.05]=0

# with FDR corrections zeroed
cbwR2EFdf<-data.frame(tmvec,scalesvec,domnetvec,netpropvec,cBW_R2VecEst)

fdrzeroed<-ggplot(cbwR2EFdf,aes(tmvec,cBW_R2VecEst,color=domnetvec,alpha=netpropvec^2)) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Transmodality") + ylab(expression(paste(Delta,R^2[adj]))) +theme_classic(base_size = 40) + geom_point(size=7,aes(tmvec,cBW_R2VecEst)) + ggtitle('EF Effect by Transmodality')+guides(alpha=FALSE,color=guide_legend(title="Maximal Y7 Overlap"))+theme(legend.position="top")

# without FDR corrections zeroed
bwR2EFdf<-data.frame(tmvec,scalesvec,domnetvec,netpropvec,BW_R2VecEst)

raw<-ggplot(bwR2EFdf,aes(tmvec,BW_R2VecEst,color=domnetvec,alpha=netpropvec^2)) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Transmodality") + ylab(expression(paste(Delta,R^2[adj]))) +theme_classic(base_size = 40) + geom_point(size=7,aes(tmvec,BW_R2VecEst)) + ggtitle('EF Effect by PG1')+guides(alpha=FALSE,color=guide_legend(title="Maximal Y7 Overlap"))+theme(legend.position="top")

ggplot(bwR2EFdf,aes(tmvec,BW_R2VecEst,color=scalesvec,alpha=netpropvec^2)) + xlab("Transmodality") + ylab(expression(paste(Delta,R^2[adj]))) +theme_classic(base_size = 45) + geom_point(size=7,aes(tmvec,BW_R2VecEst)) + ggtitle('EF Effect by Transmodality')+guides(alpha=FALSE,color=guide_legend(title="Maximal Y7 Overlap"))+theme(legend.position="top")

########### along PG2 instead of 1

# with FDR corrections zeroed
cbwR2EFdf<-data.frame(occvec,scalesvec,domnetvec,netpropvec,cBW_R2VecEst)

fdrzeroed<-ggplot(cbwR2EFdf,aes(occvec,cBW_R2VecEst,color=domnetvec,alpha=netpropvec^2)) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("PG2") + ylab(expression(paste(Delta,R^2[adj]))) +theme_classic(base_size = 45) + geom_point(size=7,aes(occvec,cBW_R2VecEst)) + ggtitle('EF Effect by Transmodality')+guides(alpha=FALSE,color=guide_legend(title="Maximal Y7 Overlap"))+theme(legend.position="top")

# without FDR corrections zeroed
bwR2EFdf<-data.frame(occvec,scalesvec,domnetvec,netpropvec,BW_R2VecEst)

raw<-ggplot(bwR2EFdf,aes(occvec,BW_R2VecEst,color=domnetvec,alpha=netpropvec^2)) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("PG2") + ylab(expression(paste(Delta,R^2[adj]))) +theme_classic(base_size = 40) + geom_point(size=7,aes(occvec,BW_R2VecEst)) + ggtitle('EF Effect by PG2')+guides(alpha=FALSE,color=guide_legend(title="Maximal Y7 Overlap"))+theme(legend.position="top")

ggplot(bwR2EFdf,aes(occvec,BW_R2VecEst,color=scalesvec,alpha=netpropvec^2)) + xlab("PG2") + ylab(expression(paste(Delta,R^2[adj]))) +theme_classic(base_size = 45) + geom_point(size=7,aes(occvec,BW_R2VecEst)) + ggtitle('EF Effect by PG2')+guides(alpha=FALSE,color=guide_legend(title="Partition Resolution"))+theme(legend.position="top")

# scale by pg2 interaction in EF relation
netLM<-lm(BW_R2VecEst~occvec*scalesvec,bwR2EFdf)
plot_model(netLM,type='int')
tab_model(netLM)

```
```{r}
# Framework for pairwise age patterns
# Transmodality Dif and Age-relation
indiv_bwcols_ind<-intersect(bwcol,indiv)
individ_scalebybw_df<-masterdf[,indiv_bwcols_ind]

# to later use wincolname -> bwcolname mapping to extrapolate if if network is unimodal or transmodal along bwcol indices
wincolnames<-colnames(individ_scalebywin_df)
bwcolnames<-colnames(individ_scalebybw_df)

# initialize empty tm difference vector and age effect vector - 10/9/20: EF vector 
# I guess append is just terribly slow. replace these with proper-length initializations
tmdifvec=rep(0,length(colnames(individ_scalebybw_df)))
ageEfvec=rep(0,length(colnames(individ_scalebybw_df)))
ageEfPvec=rep(0,length(colnames(individ_scalebybw_df)))
motionEfvec=rep(0,length(colnames(individ_scalebybw_df)))
motioncorvec<-rep(0,length(colnames(individ_scalebybw_df)))
EFEfvec=rep(0,length(colnames(individ_scalebybw_df)))
EFEfPvec=rep(0,length(colnames(individ_scalebybw_df)))
noAge_EFEfVec=rep(0,length(colnames(individ_scalebybw_df)))
noAge_EFEfPVec=rep(0,length(colnames(individ_scalebybw_df)))
Net1Vec=rep(0,length(colnames(individ_scalebybw_df)))
Net2Vec=rep(0,length(colnames(individ_scalebybw_df)))
Net1Vec17=rep(0,length(colnames(individ_scalebybw_df)))
Net2Vec17=rep(0,length(colnames(individ_scalebybw_df)))
ageDR2vec=rep(0,length(colnames(individ_scalebybw_df)))
ageDR2Pvec=rep(0,length(colnames(individ_scalebybw_df)))
EFDR2vec=rep(0,length(colnames(individ_scalebybw_df)))
EFDR2Pvec=rep(0,length(colnames(individ_scalebybw_df)))


# make a scale vector to match transmodality difference values
# this is to look at how finer scales confer networks that are less different
scalevec=rep(0,length(colnames(individ_scalebybw_df)))


# quick write of colnames for bw features for all scales as sep. files for matlab reading

for (k in 2:30){
    # index which values are at this scale
    scaleStr=paste('scale',k,'_',sep='')
    scaleCols_inds=grep(scaleStr,colnames(masterdf))
    scaleK_bw_indivi_cols_inds<-intersect(indiv_bwcols_ind,scaleCols_inds)
    # print colnames
    scalebwcolnames<-colnames(masterdf[scaleK_bw_indivi_cols_inds])
  # write list of b/w col names for matching in matlab
    write.table(scalebwcolnames,paste('/cbica/projects/pinesParcels/results/aggregated_data/Scale',k,'_Ind_bwColnames.csv',sep=''),sep=',', col.names = F,quote = F,row.names=F)
}    


#### This measures all the pairwise distances for the plots
## for all b/w cols - 10/9/20: EF added in.
for (i in 1:length(colnames(individ_scalebybw_df))){
    print(i)
    # extract column name. Will parse column name to determine nature of #connection
    curcolname<-colnames(individ_scalebybw_df)[i]
    splitname<-unlist(strsplit(curcolname,'_'))
    scalefield=splitname[4]
    net1field=splitname[5]
    net2field=splitname[7]
    # doctor up scale and net1field so they are exclusively the value of #interest
    scale=as.numeric(unlist(strsplit(scalefield,'e'))[2])
    net1=unlist(strsplit(net1field,'s'))[2]
    net2=net2field 
    # helping phriendly index
    K_start=((scale-1)*(scale))/2
    K_end=(((scale-1)*(scale))/2)+scale-1
    Kind<-K_start:K_end
    # get TM values of both nets at this scale
    tm1=tmvec[Kind[as.numeric(net1)]]
    tm2=tmvec[Kind[as.numeric(net2)]]
    # absolute value as directionality is meaningless here
    tmdif=abs(tm1-tm2)
    # get position in master df of this column (need to use \b for exact matches #only)
    curcolnameexact<-paste('\\',curcolname,'\\b',sep='')
    colindex<-grep(curcolnameexact,colnames(masterdf))
    # get Age relation controlling for sex and motion
    pcordf<-cbind(masterdf$Age,masterdf$Sex,masterdf$Motion,masterdf[,colindex])
    
    # additional section for EF. col index should not change as EF is tagged onto end
    # get EF relation controlling for sex and motion and age
    EFpcordf<-cbind(masteref$F1_Exec_Comp_Cog_Accuracy,masteref$Age,masteref$Sex,masteref$Motion,masterdf[,colindex])
    # get EF relation controlling for sex and motion
    EFpcordf2<-cbind(masteref$F1_Exec_Comp_Cog_Accuracy,masteref$Sex,masteref$Motion,masteref[,colindex])
    
    # partial spearmans to extract age relation
    pspear=pcor(pcordf,method='spearman')$estimate
    pspearval=pcor(pcordf,method='spearman')$p.value
    # save to respective vectors
    tmdifvec[i]<-tmdif
    ageEfvec[i]<-pspear[4]
    ageEfPvec[i]<-pspearval[4]
    motionEfvec[i]<-pspear[3,4]
    motioncorvec[i]<-cor.test(masterdf[,colindex],masterdf$Motion)$estimate
    # accompanying scalevec so we can look at the typical transmodality #difference at each scale
    scalevec[i]=scale
    
    # additional section for EF
    # partial spearmans to extrac age relation
    pspear=pcor(EFpcordf,method='spearman')$estimate
    pspearval=pcor(EFpcordf,method='spearman')$p.value
    EFEfvec[i]<-pspear[5]
    EFEfPvec[i]<-pspearval[5]
    
    pspear=pcor(EFpcordf2,method='spearman')$estimate
    noAge_EFEfVec[i]<-pspear[4]
    pspearval=pcor(EFpcordf2,method='spearman')$p.value
    noAge_EFEfPVec[i]<-pspearval[4]
    
    # record communities assayed in terms of yeo7
    y7lab1=domnetvec[Kind[as.numeric(net1)]]
    y7lab2=domnetvec[Kind[as.numeric(net2)]]
    y17lab1=domnetvec17[Kind[as.numeric(net1)]]
    y17lab2=domnetvec17[Kind[as.numeric(net2)]]
    Net1Vec[i]<-as.character(y7lab1)
    Net2Vec[i]<-as.character(y7lab2)
    Net1Vec17[i]<-as.character(y17lab1)
    Net2Vec17[i]<-as.character(y17lab2)
    
    # delta r2 for age, EF
    ageDR2vec[i]<-DeltaR2EstVec(masterdf[,colindex])
    ageDR2Pvec[i]<-DeltaPEstVec(masterdf[,colindex])
    EFDR2vec[i]<-EFDeltaR2EstVec(masterdf[,colindex])
    EFDR2Pvec[i]<-EFDeltaPEstVec(masterdf[,colindex])
}

# fdr correct pvectors, together
concatpvecs<-c(ageEfPvec,EFEfPvec,noAge_EFEfPVec)
correctconcatpvecs<-p.adjust(concatpvecs,method='fdr')
chunksize=length(correctconcatpvecs)/3
fdr_ageEfPvec<-correctconcatpvecs[1:chunksize]
fdr_EFEfPvec<-correctconcatpvecs[(chunksize+1):(2*chunksize)]
fdr_noAge_EFEfPVec<-correctconcatpvecs[((2*chunksize)+1):(3*chunksize)]
## ^^ masks for developmentally facilitated vs. devel. conflicted


## merged vectors
BwAgeCorTMDifDf<-data.frame(tmdifvec,ageEfvec,noAge_EFEfVec,EFEfvec,scalevec,Net1Vec,Net2Vec,Net1Vec17,Net2Vec17,fdr_ageEfPvec,fdr_EFEfPvec,fdr_noAge_EFEfPVec)

nonthresh<-ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageEfvec)) + geom_point(alpha=.07,size=5) + xlab('Transmodality Difference') + ylab('Age Partial Correlation') + ggtitle('Pairwise Between-Network Age-FC Relations')+geom_smooth(method='lm', formula= y~x,color='black',size=2)

nonthreshEF<-ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=EFEfvec)) + geom_point(alpha=.07,size=5) + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network EF-FC Relations')+geom_smooth(method='lm', formula= y~x,color='black',size=2)

thresh<-ggplot(BwAgeCorTMDifDf[fdr_ageEfPvec<0.05,],aes(x=tmdifvec,y=ageEfvec)) + geom_point(alpha=.07,size=5) + xlab('Transmodality Difference') + ylab('Age Partial Correlation') + ggtitle('Pairwise Between-Network Age-FC Relations: FDR Thresh.')

ggarrange(nonthresh,thresh)

# combine scalevec and transmodality dif vec for transmodality difference
ScaleTMDifDf<-data.frame(tmdifvec,scalevec)
ScaleTMDifMeanVec<-rep(0,29)
for (K in 2:30){
  # Pull out values at this scale
  ScaleDF<-ScaleTMDifDf[ScaleTMDifDf$scalevec==K,]
  # Average Values at this scale (K-1 because 1st scale is 2)
  ScaleTMDifMeanVec[K-1]=mean(ScaleDF$tmdifvec)
  }
    
plot(ScaleTMDifMeanVec)

ggplot(ScaleTMDifDf,aes(x=scalevec,y=tmdifvec)) + geom_point(alpha=.1,size=2) +xlab('Number of Communities') + ylab('B/W Transmodality Difference')


# distribution of modal dissimilarity over scales
ggplot(data = BwAgeCorTMDifDf, aes(x = factor(scalevec), y = tmdifvec)) +
  geom_violin(alpha = .8) +
  geom_boxplot(width=0.1)+
  geom_point(size = 1, alpha = 0.8) +
  raincloud_theme+theme_classic()
```

```{r}
# section to index age-aligned and age-mitigated EF b/w features
ageAligned<-as.matrix(rep(0,dim(BwAgeCorTMDifDf)[1]))
ageMitigated<-as.matrix(rep(0,dim(BwAgeCorTMDifDf)[1]))
ageAligned_stringent<-as.matrix(rep(0,dim(BwAgeCorTMDifDf)[1]))
ageMitigated_stringent<-as.matrix(rep(0,dim(BwAgeCorTMDifDf)[1]))


for (feat in 1:dim(BwAgeCorTMDifDf)[1]){
  # if age and EF trend are aligned (- - or + +) and EF effect survives FDR
  if (BwAgeCorTMDifDf$ageEfvec[feat]*BwAgeCorTMDifDf$noAge_EFEfVec[feat] > 0){
    ageAligned[feat]=1
        # if the no-age-control EF effect survives FDR, stringent gets a boolean "yes"
    # no-age-control chosen because age-facilitated should show EF sig w/o reger. out age
    if (BwAgeCorTMDifDf$fdr_noAge_EFEfPVec[feat] < 0.05 ){
      ageAligned_stringent[feat]=1
  } 
  }

  # if age and EF trend are opposed, age-control chosen because age-mitigated should show EF sig w/ reger. out age
  if (BwAgeCorTMDifDf$ageEfvec[feat]*BwAgeCorTMDifDf$EFEfvec[feat] < 0) {
    ageMitigated[feat]=1
      if (BwAgeCorTMDifDf$fdr_EFEfPvec[feat] < 0.05 ){
      ageMitigated_stringent[feat]=1
      }
  }
    # if the EF effect survives FDR, stringent gets a boolean "yes"
    # age-control chosen because age-mitigated only vis. after reger. out age

  # if pure age effect did not survive FDR, exclude from stringent logical masks
  if (BwAgeCorTMDifDf$fdr_ageEfPvec[feat] > 0.05){
    ageMitigated_stringent[feat]=0
    ageAligned_stringent[feat]=0
  }
  
}

Y7vec<-c('Motor','Visual','DA','VA','Limbic','FP','DM')
y17vec<-levels(domnetvec17)
# set yeo colorset
ycolors=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c')
y17colors=c('#dc8303','#8d2049','#596a85','#2d9a3d','#007938','#d9e200','#bc0943','#2b1f67','#48593a','#91a967','#4183a8','#00bb89','#3245a3','#9e3ca2','#eb75b3','#68126f','#d1001c')

ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=noAge_EFEfVec,color=Net1Vec)) + geom_text(size=5,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network EF-FC Relations')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=noAge_EFEfVec,color=Net2Vec),size=5,label="\u25D7",family="Arial Unicode MS")+theme_classic()

# remove rows to get age aligned and age mitigaged dfs
ageAligned<-as.logical(ageAligned)
ageMitigated<-as.logical(ageMitigated)
ageAligneddf<-BwAgeCorTMDifDf[c(ageAligned),]
ageMitigateddf<-BwAgeCorTMDifDf[c(ageMitigated),]
# thresholding
ageAligned_stringent<-as.logical(ageAligned_stringent)
ageMitigated_stringent<-as.logical(ageMitigated_stringent)
ageAligneddf_stringent<-BwAgeCorTMDifDf[c(ageAligned_stringent),]
ageMitigateddf_stringent<-BwAgeCorTMDifDf[c(ageMitigated_stringent),]


agF_y7<-ggplot(ageAligneddf,aes(x=tmdifvec,y=noAge_EFEfVec,color=Net1Vec)) + geom_text(size=10,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-aligned EF-FC Relations')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=noAge_EFEfVec,color=Net2Vec),size=10,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)+ylim(-.3,.3)+geom_smooth(method='lm', formula= y~x,color='gray82',size=2)

agM_y7<-ggplot(ageMitigateddf,aes(x=tmdifvec,y=EFEfvec,color=Net1Vec)) + geom_text(size=10,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-mitigated EF-FC Relations')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=EFEfvec,color=Net2Vec),size=10,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)+ylim(-.4,.4)+geom_smooth(method='lm', formula= y~x,color='gray82',size=2)

agM_y7_age_relations<-ggplot(ageMitigateddf,aes(x=tmdifvec,y=ageEfvec,color=Net1Vec)) + geom_text(size=10,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('Age Partial Correlation') + ggtitle('Pairwise Between-Network EF-Age-mitigated Age-FC Relations')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=ageEfvec,color=Net2Vec),size=10,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)+ylim(-.4,.4)+geom_smooth(method='lm', formula= y~x,color='gray82',size=2)

# more thresholding
agF_y7_thresh<-ggplot(ageAligneddf_stringent,aes(x=tmdifvec,y=noAge_EFEfVec,color=Net1Vec)) + geom_text(size=10,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-aligned EF-FC Relations')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=noAge_EFEfVec,color=Net2Vec),size=10,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)+ylim(-.3,.3)

agM_y7_thresh<-ggplot(ageMitigateddf_stringent,aes(x=tmdifvec,y=EFEfvec,color=Net1Vec)) + geom_text(size=10,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-mitigated EF-FC Relations')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=EFEfvec,color=Net2Vec),size=10,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)+ylim(-.3,.3)

# yeo17

agF_y17<-ggplot(ageAligneddf_stringent,aes(x=tmdifvec,y=noAge_EFEfVec,color=Net1Vec17)) + geom_text(size=10,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-aligned EF-FC Relations: Yeo17')+scale_color_manual(values=y17colors,limits=y17vec)+geom_text(aes(x=tmdifvec,y=noAge_EFEfVec,color=Net2Vec17),size=10,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)+ylim(-.3,.3)

agM_y17<-ggplot(ageMitigateddf_stringent,aes(x=tmdifvec,y=EFEfvec,color=Net1Vec17)) + geom_text(size=10,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-mitigated EF-FC Relations: Yeo17')+scale_color_manual(values=y17colors,limits=y17vec)+geom_text(aes(x=tmdifvec,y=EFEfvec,color=Net2Vec17),size=10,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)+ylim(-.3,.3)

ggarrange(agF_y7,agM_y7,agF_y7_thresh,agM_y7_thresh,agF_y17,agM_y17,nrow=3,ncol=2)

AgeVsEFEffects_agF<-ggplot(BwAgeCorTMDifDf,aes(x=noAge_EFEfVec,y=ageEfvec,color=Net1Vec)) + geom_text(size=7,label="\u25D6",family="Arial Unicode MS") + xlab('EF Partial Correlation') + ylab('Age Partial Correlation') + ggtitle('Age vs. EF effects - no age control')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=noAge_EFEfVec,y=ageEfvec,color=Net2Vec),size=7,label="\u25D7",family="Arial Unicode MS")+theme_minimal()+theme(legend.position = "none")
AgeVsEFEffects_agM<-ggplot(BwAgeCorTMDifDf,aes(x=EFEfvec,y=ageEfvec,color=Net1Vec)) + geom_text(size=7,label="\u25D6",family="Arial Unicode MS") + xlab('EF Partial Correlation') + ylab('Age Partial Correlation') + ggtitle('Age vs. Age-controlled EF effects')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=EFEfvec,y=ageEfvec,color=Net2Vec),size=7,label="\u25D7",family="Arial Unicode MS")+theme_minimal()+theme(legend.position = "none")
```

```{r}
##### global plots
##### plot average at each scale
####AA_corvec<-rep(0,29)
####AM_corvec<-rep(0,29)
####both_corvec<-rep(0,29)
#######both_corvec_age<-rep(0,29)
####for (K in 2:30){
####  AA_K<-ageAligneddf[ageAligneddf$scalevec==K,]
####  AM_K<-ageMitigateddf[ageMitigateddf$scalevec==K,]
####  both<-BwAgeCorTMDifDf[BwAgeCorTMDifDf$scalevec==K,]
####  AA_corvec[K-1]<-mean(AA_K$noAge_EFEfVec)
####  AM_corvec[K-1]<-mean(AM_K$EFEfvec)
####  both_corvec[K-1]<-mean(both$EFEfvec)
#######  both_corvec_age[K-1]<-mean(both$ageEfvec)
####}
####
####plot(AA_corvec)
####plot(AM_corvec)
####plot(both_corvec)
####aa_plotCols<-cbind(seq(2:30),c(AA_corvec))
####am_plotCols<-cbind(seq(2:30),c(AM_corvec))
####both_plotCols<-cbind(seq(2:30),c(both_corvec))
##### average correlations
####correlations_over_scales(aa_plotCols,"Average b/w EF Cor: Age-Aligned")
####correlations_over_scales(am_plotCols,"Average b/w EF Cor: Age-Mitigated")
####correlations_over_scales(both_plotCols,"Average b/w EF Cor")
### now do with average value for parallelism
### note - bottom section of this chunk is the valid one: averaging correlations of all nets within scales != averaging b/w cons within scales and correlating
#use age mitig. and age facilitated indices to extract corresp. values from indiv_bwcols_ind
# initialize 
winScaleAvgbwVal_agF<-matrix(0,693,29)
winScaleAvgbwVal_agM<-matrix(0,693,29)
winScaleAvgbwVal<-matrix(0,693,29)
# for each scale
for (K in 2:30){
  # use logical indices of age aligned and age mitigated in tandem with scale index
  AgeAli_K<- scalevec==K & ageAligned=='TRUE'
  AgeMit_K<- scalevec==K & ageMitigated=='TRUE'
  both<-scalevec==K
  
  # annoying tidbit to deal with thrown error on K=2 (can't rowmean on 1 column)
  if (K==2){
    winScaleAvgbwVal[,K-1]<-masterdf[,indiv_bwcols_ind[both]]
    winScaleAvgbwVal_agF[,K-1]<-masterdf[,indiv_bwcols_ind[AgeAli_K]]
    # another annoying bit of logic to deal with age-mitig. not being present at all scales
    if (sum(AgeMit_K[scalevec==K] != 0)){
      winScaleAvgbwVal_agM[,K-1]<-masterdf[,indiv_bwcols_ind[AgeMit_K]]
    } else {
      winScaleAvgbwVal_agM[,K-1]=rep(0,693)
    }
  # if K not equal to 2
  } else {
  # use bwcol ind to get corresponding positions in masterdf
  # extract matrix of b/w conns for everyone at this scale, rowmean it
  winScaleAvgbwVal_agF[,K-1]<-rowMeans(masterdf[,indiv_bwcols_ind[AgeAli_K]])
  winScaleAvgbwVal[,K-1]<-rowMeans(masterdf[,indiv_bwcols_ind[both]])
  # another annoying bit of logic to deal with age-mitig. not being present at all scales
    if (sum(AgeMit_K[scalevec==K] != 0)){
      # if there is only one feature, no row meaning
      if (sum(AgeMit_K[scalevec==K]) == 1){
      winScaleAvgbwVal_agM[,K-1]<-masterdf[,indiv_bwcols_ind[AgeMit_K]]
      } else {
      # row means if there are multiple columns
        winScaleAvgbwVal_agM[,K-1]<-winScaleAvgbwVal_agM[,K-1]<-rowMeans(masterdf[,indiv_bwcols_ind[AgeMit_K]])
      }
    # if there are no mitig. features at this scale, fill in with 0
    } else {
      winScaleAvgbwVal_agM[,K-1]=rep(0,693)
    }
  }
}
# there's gotta be a more efficient way to do that. Anyways, now repeat correlation analyses on "global" b/w values
### use the "global" b/w values to evaluate global scale-dependency
# global
indglobbw<-data.frame(cbind(masteref$bblid,masteref$Age/12,masteref$Sex,masteref$Motion,masteref$F1_Exec_Comp_Cog_Accuracy,winScaleAvgbwVal))
colnames(indglobbw)[1:5]<-c('bblid','Age','Sex','Motion','EF')
ind_bwcors<-matrix(0,29,2)
ind_bwcors[,1]<-2:30
for (i in 1:29){
  # relevant df
  scaledf<-cbind(indglobbw$EF,indglobbw$Age,indglobbw$Sex,indglobbw$Motion,indglobbw[,i+5])
  # partial spearmans to extrac age relation
  pspear=pcor(scaledf,method='spearman')$estimate
  ind_bwcors[i,2]<-pspear[5]
}
indEFcor2<-correlations_over_scales(ind_bwcors,"Global B/w-EF Correlation")
### age facilitated
indglobbw<-data.frame(cbind(masteref$bblid,masteref$Age/12,masteref$Sex,masteref$Motion,masteref$F1_Exec_Comp_Cog_Accuracy,winScaleAvgbwVal_agF))
colnames(indglobbw)[1:5]<-c('bblid','Age','Sex','Motion','EF')
ind_bwcors<-matrix(0,29,2)
ind_bwcors[,1]<-2:30
for (i in 1:29){
  # relevant df, age removed here (age facilitated while controlling for age doesn't make sense)
  scaledf<-cbind(indglobbw$EF,indglobbw$Sex,indglobbw$Motion,indglobbw[,i+5])
  # partial spearmans to extrac age relation
  pspear=pcor(scaledf,method='spearman')$estimate
  ind_bwcors[i,2]<-pspear[4]
}
indEFcor_agF<-correlations_over_scales(ind_bwcors,"Global B/w-EF: Age-Facil.")
### age mitigated
indglobbw<-data.frame(cbind(masteref$bblid,masteref$Age/12,masteref$Sex,masteref$Motion,masteref$F1_Exec_Comp_Cog_Accuracy,winScaleAvgbwVal_agM))
colnames(indglobbw)[1:5]<-c('bblid','Age','Sex','Motion','EF')
ind_bwcors<-matrix(0,29,2)
ind_bwcors[,1]<-2:30
for (i in 1:29){
  # relevant df
  scaledf<-cbind(indglobbw$EF,indglobbw$Age,indglobbw$Sex,indglobbw$Motion,indglobbw[,i+5])
  # partial spearmans to extrac age relation
  pspear=pcor(scaledf,method='spearman')$estimate
  ind_bwcors[i,2]<-pspear[5]
}
indEFcor_agM<-correlations_over_scales(ind_bwcors,"Global B/w-EF: Age-Mitig.")
######## for age instead of EF
# just for global age
indglobbw<-data.frame(cbind(masteref$bblid,masteref$Age/12,masteref$Sex,masteref$Motion,winScaleAvgbwVal))
colnames(indglobbw)[1:4]<-c('bblid','Age','Sex','Motion')
ind_bwcors<-matrix(0,29,2)
ind_bwcors[,1]<-2:30
for (i in 1:29){
  # relevant df
  scaledf<-cbind(indglobbw$Age,indglobbw$Sex,indglobbw$Motion,indglobbw[,i+4])
  # partial spearmans to extrac age relation
  pspear=pcor(scaledf,method='spearman')$estimate
  ind_bwcors[i,2]<-pspear[4]
}
indAgecor<-correlations_over_scales(ind_bwcors,"B/w Community Connectivity - Age Correlation")
######### do age subsets
#8-13
indglobbw<-data.frame(cbind(masteref$bblid,masteref$Age/12,masteref$Sex,masteref$Motion,winScaleAvgbwVal))
colnames(indglobbw)[1:4]<-c('bblid','Age','Sex','Motion')
indglobbw<-indglobbw[indglobbw$Age<13,]
ind_bwcors<-matrix(0,29,2)
ind_bwcors[,1]<-2:30
for (i in 1:29){
  # relevant df
  scaledf<-cbind(indglobbw$Age,indglobbw$Sex,indglobbw$Motion,indglobbw[,i+4])
  # partial spearmans to extrac age relation
  pspear=pcor(scaledf,method='spearman')$estimate
  ind_bwcors[i,2]<-pspear[4]
}
youngAgecor<-correlations_over_scales(ind_bwcors,"B/w Community Connectivity - Age Correlation: 8-13")
#13-18
indglobbw<-data.frame(cbind(masteref$bblid,masteref$Age/12,masteref$Sex,masteref$Motion,winScaleAvgbwVal))
colnames(indglobbw)[1:4]<-c('bblid','Age','Sex','Motion')
indglobbw<-indglobbw[indglobbw$Age>13,]
indglobbw<-indglobbw[indglobbw$Age<18,]
ind_bwcors<-matrix(0,29,2)
ind_bwcors[,1]<-2:30
for (i in 1:29){
  # relevant df
  scaledf<-cbind(indglobbw$Age,indglobbw$Sex,indglobbw$Motion,indglobbw[,i+4])
  # partial spearmans to extrac age relation
  pspear=pcor(scaledf,method='spearman')$estimate
  ind_bwcors[i,2]<-pspear[4]
}
midAgecor<-correlations_over_scales(ind_bwcors,"B/w Community Connectivity - Age Correlation: 13-18")
#18-23
indglobbw<-data.frame(cbind(masteref$bblid,masteref$Age/12,masteref$Sex,masteref$Motion,winScaleAvgbwVal))
colnames(indglobbw)[1:4]<-c('bblid','Age','Sex','Motion')
indglobbw<-indglobbw[indglobbw$Age>18,]
ind_bwcors<-matrix(0,29,2)
ind_bwcors[,1]<-2:30
for (i in 1:29){
  # relevant df
  scaledf<-cbind(indglobbw$Age,indglobbw$Sex,indglobbw$Motion,indglobbw[,i+4])
  # partial spearmans to extrac age relation
  pspear=pcor(scaledf,method='spearman')$estimate
  ind_bwcors[i,2]<-pspear[4]
}
oldAgecor<-correlations_over_scales(ind_bwcors,"B/w Community Connectivity - Age Correlation: 18-23")
```
```{r}
# make same plots but with delta r^2 instead of correlation to account for non-linearity
# just for global age
indglobbw<-data.frame(cbind(masteref$bblid,masteref$Age/12,masteref$Sex,masteref$Motion,winScaleAvgbwVal))
colnames(indglobbw)[1:4]<-c('bblid','Age','Sex','Motion')
ind_bw_dr2<-matrix(0,29,2)
ind_bw_dr2[,1]<-2:30
#for (i in 1:29){
#  ind_bw_dr2[i,2]<-DeltaR2EstVec_ageSubset(indglobbw,(i+4))
#}
#indAgedr2<-dr2_over_scales(ind_bw_dr2,'B/w Community Connectivity - Age Effect')
########## do age subsets
##8-13
#indglobbw<-data.frame(cbind(masteref$bblid,masteref$Age/12,masteref$Sex,masteref$Motion,winScaleAvgbwVal))
#colnames(indglobbw)[1:4]<-c('bblid','Age','Sex','Motion')
#indglobbw<-indglobbw[indglobbw$Age<13,]
#ind_bw_dr2<-matrix(0,29,2)
#ind_bw_dr2[,1]<-2:30
#for (i in 1:29){
#  ind_bw_dr2[i,2]<-DeltaR2EstVec_ageSubset(indglobbw,(i+4))
#}
#youngAgedr2<-dr2_over_scales(ind_bw_dr2,"B/w Community Connectivity - Age Effect: 8-13")
##13-18
#indglobbw<-data.frame(cbind(masteref$bblid,masteref$Age/12,masteref$Sex,masteref$Motion,winScaleAvgbwVal))
#colnames(indglobbw)[1:4]<-c('bblid','Age','Sex','Motion')
#indglobbw<-indglobbw[indglobbw$Age>13,]
#indglobbw<-indglobbw[indglobbw$Age<18,]
#ind_bw_dr2<-matrix(0,29,2)
#ind_bw_dr2[,1]<-2:30
#for (i in 1:29){
#  ind_bw_dr2[i,2]<-DeltaR2EstVec_ageSubset(indglobbw,(i+4))
#}
#midAgedr2<-dr2_over_scales(ind_bw_dr2,"B/w Community Connectivity - Age Effect: 13-18")
##18-23
#indglobbw<-data.frame(cbind(masteref$bblid,masteref$Age/12,masteref$Sex,masteref$Motion,winScaleAvgbwVal))
#colnames(indglobbw)[1:4]<-c('bblid','Age','Sex','Motion')
#indglobbw<-indglobbw[indglobbw$Age>18,]
#ind_bw_dr2<-matrix(0,29,2)
#ind_bw_dr2[,1]<-2:30
#for (i in 1:29){
#  ind_bw_dr2[i,2]<-DeltaR2EstVec_ageSubset(indglobbw,(i+4))
#}
#oldAgedr2<-dr2_over_scales(ind_bw_dr2,"B/w Community Connectivity - Age Effect: 18-23")
```

```{r}
# section to make a table of 
#| ef + age + | ef + age - | EF + no age
#| ef - age + | ef - age - | EF - no age

#fdr'ed EF
fdrEFDr2Ps<-p.adjust(EFDR2Pvec,method='fdr')

# index of features surviving FDR
EFsurvivors<-which(fdrEFDr2Ps<0.05)
EFsurivor_EF_Effects<-EFDR2vec[EFsurvivors]
EFsurivor_Age_Effects<-ageDR2vec[EFsurvivors]
# index of positive and negative EF relations
EFpos<-which(EFDR2vec>0)
EFneg<-which(EFDR2vec<0)

# index of features surviving (and dying) with age FDR
#fdr'ed Age
fdrAgeDr2Ps<-p.adjust(ageDR2Pvec,method='fdr')
AgeSurvivors<-which(fdrAgeDr2Ps<0.05)
AgeCausalties<-which(fdrAgeDr2Ps>0.05)

# index of positive and negative Age relations
Agepos<-which(ageDR2vec>0)
Ageneg<-which(ageDR2vec<0)

# get number of features surviving fdr positively associated with EF, pos w/ age
posEposA<-intersect(intersect(intersect(EFpos,Agepos),EFsurvivors),AgeSurvivors)
# get number of features surviving fdr negatively associated with EF, pos w/ age
negEposA<-intersect(intersect(intersect(EFneg,Agepos),EFsurvivors),AgeSurvivors)
# get number of features surviving fdr positively associated with EF, neg w/ age
posEnegA<-intersect(intersect(intersect(EFpos,Ageneg),EFsurvivors),AgeSurvivors)
# get number of features surviving fdr negatively associated with EF, neg w/ age
negEnegA<-intersect(intersect(intersect(EFneg,Ageneg),EFsurvivors),AgeSurvivors)
# get number of features surviving fdr positively associated with EF, no relation w/ age
posEnoA<-intersect(intersect(EFpos,EFsurvivors),AgeCausalties)
# get number of features surviving fdr negatively associated with EF, no relation w/ age
negEnoA<-intersect(intersect(EFneg,EFsurvivors),AgeCausalties)

paste("positive Age, pos EF edges:", length(posEposA))
paste("positive Age, neg EF edges:", length(negEposA))
paste("negative Age, pos EF edges:", length(posEnegA))
paste("negative Age, neg EF edges:", length(negEnegA))
paste("Age-unrelated pos EF edges:", length(posEnoA))
paste("Age-unrelated, neg EF edges:", length(negEnoA))

# plot em!
## merged vectors
BwAgeDR2TMDifDf<-data.frame(tmdifvec,scalevec,Net1Vec,Net2Vec,Net1Vec17,Net2Vec17,ageDR2vec,EFDR2vec)

posEposAy7<-ggplot(BwAgeDR2TMDifDf[posEposA,],aes(x=tmdifvec,y=EFDR2vec,color=Net1Vec)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF+ Age+')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=Net2Vec),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

negEposAy7<-ggplot(BwAgeDR2TMDifDf[negEposA,],aes(x=tmdifvec,y=EFDR2vec,color=Net1Vec)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF- Age+')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=Net2Vec),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

posEnegAy7<-ggplot(BwAgeDR2TMDifDf[posEnegA,],aes(x=tmdifvec,y=EFDR2vec,color=Net1Vec)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF+ Age-')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=Net2Vec),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

negEnegAy7<-ggplot(BwAgeDR2TMDifDf[negEnegA,],aes(x=tmdifvec,y=EFDR2vec,color=Net1Vec)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF- Age-')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=Net2Vec),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

posEnoAy7<-ggplot(BwAgeDR2TMDifDf[posEnoA,],aes(x=tmdifvec,y=EFDR2vec,color=Net1Vec)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF+ No Age')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=Net2Vec),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

negEnoAy7<-ggplot(BwAgeDR2TMDifDf[negEnoA,],aes(x=tmdifvec,y=EFDR2vec,color=Net1Vec)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF- No Age')+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=Net2Vec),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

############## 17 coloration
posEposAy17<-ggplot(BwAgeDR2TMDifDf[posEposA,],aes(x=tmdifvec,y=EFDR2vec,color=Net1Vec17)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF+ Age+')+scale_color_manual(values=y17colors,limits=y17vec)+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=Net2Vec17),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

negEposAy17<-ggplot(BwAgeDR2TMDifDf[negEposA,],aes(x=tmdifvec,y=EFDR2vec,color=Net1Vec17)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF- Age+')+scale_color_manual(values=y17colors,limits=y17vec)+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=Net2Vec17),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

posEnegAy17<-ggplot(BwAgeDR2TMDifDf[posEnegA,],aes(x=tmdifvec,y=EFDR2vec,color=Net1Vec17)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF+ Age-')+scale_color_manual(values=y17colors,limits=y17vec)+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=Net2Vec17),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

negEnegAy17<-ggplot(BwAgeDR2TMDifDf[negEnegA,],aes(x=tmdifvec,y=EFDR2vec,color=Net1Vec17)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF- Age-')+scale_color_manual(values=y17colors,limits=y17vec)+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=Net2Vec17),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

posEnoAy17<-ggplot(BwAgeDR2TMDifDf[posEnoA,],aes(x=tmdifvec,y=EFDR2vec,color=Net1Vec17)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF+ No Age')+scale_color_manual(values=y17colors,limits=y17vec)+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=Net2Vec17),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

negEnoAy17<-ggplot(BwAgeDR2TMDifDf[negEnoA,],aes(x=tmdifvec,y=EFDR2vec,color=Net1Vec17)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF- No Age')+scale_color_manual(values=y17colors,limits=y17vec)+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=Net2Vec17),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)


############## Scale coloration

posEposAs<-ggplot(BwAgeDR2TMDifDf[posEposA,],aes(x=tmdifvec,y=EFDR2vec,color=scalevec)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF+ Age+')+scale_color_gradientn(colours = rainbow(5))+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=scalevec),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

negEposAs<-ggplot(BwAgeDR2TMDifDf[negEposA,],aes(x=tmdifvec,y=EFDR2vec,color=scalevec)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF- Age+')+scale_color_gradientn(colours = rainbow(5))+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=scalevec),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

posEnegAs<-ggplot(BwAgeDR2TMDifDf[posEnegA,],aes(x=tmdifvec,y=EFDR2vec,color=scalevec)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF+ Age-')+scale_color_gradientn(colours = rainbow(5))+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=scalevec),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

negEnegAs<-ggplot(BwAgeDR2TMDifDf[negEnegA,],aes(x=tmdifvec,y=EFDR2vec,color=scalevec)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF- Age-')+scale_color_gradientn(colours = rainbow(5))+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=scalevec),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

posEnoAs<-ggplot(BwAgeDR2TMDifDf[posEnoA,],aes(x=tmdifvec,y=EFDR2vec,color=scalevec)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF+ No Age')+scale_color_gradientn(colours = rainbow(5))+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=scalevec),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

negEnoAs<-ggplot(BwAgeDR2TMDifDf[negEnoA,],aes(x=tmdifvec,y=EFDR2vec,color=scalevec)) + geom_text(size=9,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('EF delta r^2') + ggtitle('EF- No Age')+scale_color_gradientn(colours = rainbow(5))+geom_text(aes(x=tmdifvec,y=EFDR2vec,color=scalevec),size=9,label="\u25D7",family="Arial Unicode MS")+theme_classic()+xlim(0,12)

#megaPosEf<-ggarrange(posEposAy7,posEnegAy7,posEnoAy7,posEposAy17,posEnegAy17,posEnoAy17,posEposAs,posEnegAs,posEnoAs)
#megaNegEf<-ggarrange(negEposAy7,negEnegAy7,negEnoAy7,negEposAy17,negEnegAy17,negEnoAy17,negEposAs,negEnegAs,negEnoAs)
```


```{r}
# for high dimensional mediation
# save X - Age
zage=((masteref$Age-mean(masteref$Age)))/(sd(masteref$Age))
write.table(zage,'/cbica/projects/pinesParcels/data/aggregated_data/X.csv',sep=',',row.names = F,col.names = F)
# save Y - EF
zage=((masteref$Age-mean(masteref$Age)))/(sd(masteref$Age))
write.table(masteref$F1_Exec_Comp_Cog_Accuracy,'/cbica/projects/pinesParcels/data/aggregated_data/Y.csv',sep=',',row.names = F,col.names = F)

# extract edges - starting with scale20
# get indices of edges
bwi='_bw_FC_'
ind='ind'
# indices of said indicators, this time in masteref as double check
indiv=grep(ind,colnames(masteref))
bwcol=grep(bwi,colnames(masteref))
# get indices of edges and individualized values
indiv_bwcols_ind<-intersect(bwcol,indiv)

####set K
k=4
####

# grep out edges at this scale
scaleStr=paste('scale',k,'_',sep='')
scaleCols_inds=grep(scaleStr,colnames(masteref))
# combine with edge only and individualized only values
scaleK_bw_indivi_cols_inds<-intersect(indiv_bwcols_ind,scaleCols_inds)
# z score edges
edges<-masteref[colnames(masteref)[scaleK_bw_indivi_cols_inds]]
for (i in 1:length(edges)){
  edges[,i]<-((edges[,i]-mean(edges[,i])))/(sd(edges[,i]))
}
# same M - edges
write.table(edges,'/cbica/projects/pinesParcels/data/aggregated_data/M.csv',sep=',',row.names = F,col.names = F)
```

```{r}
# make scale-specific plots
# scale ordering for visibility of coarse scales
BwAgeCorTMDifDf_rev<- BwAgeCorTMDifDf[seq(dim(BwAgeCorTMDifDf)[1],1),]

ggplot(BwAgeCorTMDifDf_rev,aes(x=tmdifvec,y=ageEfvec,color=scalevec)) + geom_point(size=3)+scale_color_viridis(option='inferno') + xlab('Transmodality Difference') + ylab('Age Partial Correlation') + ggtitle('Pairwise Between-Network Age FC Relations: Scale')+theme_classic()

ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageEfvec,color=scalevec)) + geom_point(size=3)+scale_color_viridis(option='inferno') + xlab('Transmodality Difference') + ylab('Age Partial Correlation')  + ggtitle('Pairwise Between-Network Age FC Relations: Scale')+theme_classic()

ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=EFEfvec,color=scalevec)) + geom_point(size=3) + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-mitigated EF-FC Relations')+scale_color_viridis(option='inferno')+theme_classic()+xlim(0,12)

# scale-colored plots
agF_sc<-ggplot(BwAgeCorTMDifDf_rev,aes(x=tmdifvec,y=noAge_EFEfVec,color=scalevec)) + geom_point(size=10) + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-aligned EF-FC Relations: Yeo17')+scale_color_viridis(option='inferno')+theme_classic()

agM_sc<-ggplot(BwAgeCorTMDifDf_rev,aes(x=tmdifvec,y=EFEfvec,color=scalevec)) + geom_point(size=10) + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-controlled EF-FC Relations: Yeo17')+scale_color_viridis(option='inferno')+theme_classic()

ggarrange(agF_sc,agM_sc)


```

```{r}
# animations to show coarse-medium scale effect
library(gganimate)
agF_sc2<-ggplot(ageAligneddf[1:47,],aes(x=tmdifvec,y=noAge_EFEfVec,color=scalevec)) + geom_point(size=10) + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-aligned EF-FC Relations: Yeo17')+scale_color_viridis(option='inferno')+theme_classic()

agF_anim<-agF_sc2 + transition_states(as.integer(scalevec), state_length = 3)

agM_sc2<-ggplot(ageMitigateddf[1:50,],aes(x=tmdifvec,y=EFEfvec,color=scalevec)) + geom_point(size=10) + xlab('Transmodality Difference') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-mitigated EF-FC Relations: Yeo17')+scale_color_viridis(option='inferno')+theme_classic()

agM_anim<-agM_sc2 + transition_states(as.integer(scalevec), state_length = 3)

#agF_anim
#agM_anim

#anim_save('~/multiscale/age-facilitated_scaleEffect_EF.gif',animation=agF_anim)
#anim_save('~/multiscale/age-mitigated_scaleEffect_EF.gif',animation=agF_anim)
```

```{r}
### control for covariates prior to feature writeout for python

# intialize feature matrix for age-facil
ageFacilFeats<-matrix(0,693,dim(ageAligneddf)[1])
# for age-mitig
ageMitigFeats<-matrix(0,693,dim(ageMitigateddf)[1])
# for age-combined
bothFeats<-matrix(0,693,dim(individ_scalebybw_df)[2])

# for each b/w feature
for (featNum in 1:dim(individ_scalebybw_df)[2]){
  # if age-facil, no control for age
  if (ageAligned[featNum]==1){
    # make dataframe for gamming, b/w feature sex motion and scale
    tempDf<-data.frame(individ_scalebybw_df[,featNum],masterdf$Sex,masterdf$Motion,scalevec[featNum])
    colnames(tempDf)<-c('bwFeature','Sex','Motion','Scale')
    # not using scale for now
    tempLm<-lm(bwFeature~Sex+Motion,data=tempDf)
    # plug residuals into feature matrix
    bothFeats[,featNum]<-tempLm$residuals
  # if age-mitig, control for age
  } else if (ageAligned[featNum]==0){
    # make dataframe for gamming, b/w feature sex motion and scale
    tempDf<-data.frame(individ_scalebybw_df[,featNum],masterdf$Age,masterdf$Sex,masterdf$Motion,scalevec[featNum])
    colnames(tempDf)<-c('bwFeature','Age','Sex','Motion','Scale')
    # not using scale for now
    tempGam<-gam(bwFeature~s(Age,k=4)+Sex+Motion,data=tempDf)
    # plug residuals into feature matrix
    bothFeats[,featNum]<-tempLm$residuals
  }
}

# sep out ageFacil and ageMitig
ageFacilFeats<-bothFeats[,ageAligned]
ageMitigFeats<-bothFeats[,ageMitigated]

# combine feature matrices with EF scores
ageFacilFeats<-cbind(ageFacilFeats,masteref$F1_Exec_Comp_Cog_Accuracy)
ageMitigFeats<-cbind(ageMitigFeats,masteref$F1_Exec_Comp_Cog_Accuracy)
bothFeats<-cbind(bothFeats,masteref$F1_Exec_Comp_Cog_Accuracy)

# write em out to cubic
#write.table(ageFacilFeats,'/cbica/projects/pinesParcels/results/EffectVecs/AgeFacilFeats',sep=',', col.names = F,quote = F,row.names=F)
#write.table(ageMitigFeats,'/cbica/projects/pinesParcels/results/EffectVecs/AgeMitigFeats',sep=',', col.names = F,quote = F,row.names=F)
#write.table(bothFeats,'/cbica/projects/pinesParcels/results/EffectVecs/AgeFacilAndMitigFeats',sep=',', col.names = F,quote = F,row.names=F)
```

```{r}
# czech out the predicted EF values
predEFcsv<-read.csv('/cbica/projects/pinesParcels/data/aggregated_data/SubjPreds_agFagM.csv',header=F)
predEF_agFcsv<-read.csv('/cbica/projects/pinesParcels/data/aggregated_data/SubjPreds_agF.csv',header=F)
predEF_agMcsv<-read.csv('/cbica/projects/pinesParcels/data/aggregated_data/SubjPreds_agM.csv',header=F)

# convert to average predicted EF over all folds
predEF<-predEFcsv[,1]/predEFcsv[,2]
predEF_agF<-predEF_agFcsv[,1]/predEF_agFcsv[,2]
predEF_agM<-predEF_agMcsv[,1]/predEF_agMcsv[,2]

plot(masteref$Age,predEF_agM)
cor.test(masteref$Age,predEF_agM,method='spearman')
```

```{r}
######### Look at between-distance relations

## grab matlab-generated euclidean distance vector, match to age effect vector
distance_array=array(dim=c(length(colnames(individ_scalebybw_df)),2))

# make a between over scales vector to keep track of where each between feature sits in the whole multiscale combination
bw_over_scales=NULL
bw_start=0
bw_end=0


for (k in 2:30){
    # index which values are at this scale
    scaleStr=paste('scale',k,'_',sep='')
    scaleCols_inds=grep(scaleStr,colnames(masterdf))
    scaleK_bw_indivi_cols_inds<-intersect(indiv_bwcols_ind,scaleCols_inds)

    # load in distance file for this scale
    disfp=paste('/cbica/projects/pinesParcels/results/aggregated_data/Scale',k,'_Ind_bwColnames_andDist.csv',sep='')
    distancedf<-read.csv(disfp)
    # check to make sure name in file is the same as the corresponding bw col from masterdf
    if (identical((colnames(masterdf)[scaleK_bw_indivi_cols_inds]),distancedf$bwcolscell_1)){
      print('bw column names match')}
    print(k)
    
    # helping phriendly index
    bw_start=bw_end+1
    bw_end=bw_start+((k)*(k-1)/2)-1
    Bwind<-bw_start:bw_end
    
    distance_array[Bwind,1]<-colnames(masterdf)[scaleK_bw_indivi_cols_inds]
    distance_array[Bwind,2]<-distancedf$bwcolscell_2
    
}  

# Add in pairwise distance between communities, motion-FC relation
BwAgeCorTMDifDf<-data.frame(tmdifvec,ageEfvec,as.numeric(distance_array[,2]),motionEfvec,motioncorvec)

colnames(BwAgeCorTMDifDf)<-c('TMDif','AgeEf','EucDist','MotionEf','MotionCor')

# Artificial 0s exist where 2 communities do not exist on the same hemisphere, mask em out
BwAgeCorDistance_nonZero<-BwAgeCorTMDifDf[BwAgeCorTMDifDf$EucDist!=0,]

ggplot(data=BwAgeCorDistance_nonZero,aes(x=EucDist,y=AgeEf)) + geom_point(alpha=.07,size=3) + xlab('Euclid. Dist.') + ylab('Age #Correlation') + ggtitle('Pairwise Between-Network Age-FC Relations')

ggplot(data=BwAgeCorDistance_nonZero,aes(x=EucDist,y=MotionEf)) + geom_point(alpha=.07,size=3) + xlab('Euclid. Dist.') + ylab('Motion Partial Correlation') + ggtitle('Pairwise Between-Network Motion-FC Relations')

ggplot(data=BwAgeCorDistance_nonZero,aes(x=EucDist,y=MotionCor)) + geom_point(alpha=.07,size=3) + xlab('Euclid. Dist.') + ylab('Motion  Correlation') + ggtitle('Pairwise Between-Network Motion-FC Relations')

### some of the b/w EF effects by transmodality distance
BwAgeCorTMDifDf<-data.frame(tmdifvec,ageEfvec,noAge_EFEfVec,EFEfvec,scalevec,Net1Vec,Net2Vec,Net1Vec17,Net2Vec17,fdr_ageEfPvec,fdr_EFEfPvec,fdr_noAge_EFEfPVec,as.numeric(distance_array[,2]))

# fix name of last column
colnames(BwAgeCorTMDifDf)[13]<-'EucDist'

# remove rows to get age aligned and age mitigaged dfs
ageAligned<-as.logical(ageAligned)
ageMitigated<-as.logical(ageMitigated)
ageAligneddf<-BwAgeCorTMDifDf[c(ageAligned),]
ageMitigateddf<-BwAgeCorTMDifDf[c(ageMitigated),]
# thresholding
ageAligned_stringent<-as.logical(ageAligned_stringent)
ageMitigated_stringent<-as.logical(ageMitigated_stringent)
ageAligneddf_stringent<-BwAgeCorTMDifDf[c(ageAligned_stringent),]
ageMitigateddf_stringent<-BwAgeCorTMDifDf[c(ageMitigated_stringent),]

# with euclidean distance instead of transmodality dif
# 0 distances repr. networks on different hemis (cannot calc.)
agF_y17_euc<-ggplot(ageAligneddf_stringent,aes(x=EucDist,y=noAge_EFEfVec,color=Net1Vec17)) + geom_text(size=10,label="\u25D6",family="Arial Unicode MS") + xlab('Euclidean Distance') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-aligned EF-FC Relations: Yeo17')+scale_color_manual(values=y17colors,limits=y17vec)+geom_text(aes(x=EucDist,y=noAge_EFEfVec,color=Net2Vec17),size=10,label="\u25D7",family="Arial Unicode MS")+theme_classic()+ylim(-.3,.3)+xlim(30,250)

# 0 distances repr. networks on different hemis (cannot calc.)
agM_y17_euc<-ggplot(ageMitigateddf_stringent,aes(x=EucDist,y=EFEfvec,color=Net1Vec17)) + geom_text(size=10,label="\u25D6",family="Arial Unicode MS") + xlab('Euclidean Distance') + ylab('EF Partial Correlation') + ggtitle('Pairwise Between-Network Age-mitigated EF-FC Relations: Yeo17')+scale_color_manual(values=y17colors,limits=y17vec)+geom_text(aes(x=EucDist,y=EFEfvec,color=Net2Vec17),size=10,label="\u25D7",family="Arial Unicode MS")+theme_classic()+ylim(-.3,.3)+xlim(30,250)


```

```{r}
# seperate out types of pairwise connections to see if unimodal networks reach out over larger transmodality gaps to integrate over age (if transmodality is a measure of how "DMN" a region is, it will underestimate intrinsic differences between things like motor and visual if they are equally "non-dmn" )

# make a vector of each y7 network so i can loop over it instead of makingn 7 different loops
Y7vec<-c('Motor','Visual','DA','VA','Limbic','FP','DM')
# set yeo colorset
ycolors=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c')

#
## for all y7 nets
#for (y in 1:7){
#  # net looked at in this iteration
#  print(Y7vec[y])
#  tmdifvec=NULL
#  ageEfvec=NULL
#  # isolate this net by getting indices of where it is in the 464 vector
#  curY7NetInd<-grep(Y7vec[y],domnetvec)
#  # for all b/w cols
#  for (i in 1:length(colnames(individ_scalebybw_df))){
#      #print(i)
#      # extract column name. Will parse column name to determine nature of #connection
#      curcolname<-colnames(individ_scalebybw_df)[i]
#      splitname<-unlist(strsplit(curcolname,'_'))
#      scalefield=splitname[4]
#      net1field=splitname[5]
#      net2field=splitname[7]
#      # doctor up scale and net1field so they are exclusively the value of #interestx
#      scale=as.numeric(unlist(strsplit(scalefield,'e'))[2])
#      net1=unlist(strsplit(net1field,'s'))[2]
#      net2=net2field 
#      # helping phriendly index
#      K_start=((scale-1)*(scale))/2
#      K_end=(((scale-1)*(scale))/2)+scale-1
#      Kind<-K_start:K_end
#      # ONLY include if one network is equal to currently indexed Y7 network
#      y7lab1=domnetvec[Kind[as.numeric(net1)]]
#      y7lab2=domnetvec[Kind[as.numeric(net2)]]
#      if (y7lab1 == Y7vec[y] || y7lab2 == Y7vec[y]){
#      # get TM values of both nets at this scale
#      tm1=tmvec[Kind[as.numeric(net1)]]
#      tm2=tmvec[Kind[as.numeric(net2)]]
#      # absolute value as directionality is meaningless here
#      tmdif=abs(tm1-tm2)
#      # get position in master df of this column (need to use \b for exact #matches only)
#      curcolnameexact<-paste('\\',curcolname,'\\b',sep='')
#      colindex<-grep(curcolnameexact,colnames(masterdf))
#      # get Age relation controlling for sex and motion
#      pcordf<-cbind(masterdf$Age,masterdf$Sex,masterdf$Motion,masterdf[,colindex#])
#      # partial spearmans to extrac age relation
#      pspear=pcor(pcordf,method='spearman')$estimate
#      # save both to respective vectors
#      tmdifvec<-append(tmdifvec,tmdif)
#      ageEfvec<-append(ageEfvec,pspear[4])
#      }
#  }
#  # merged vectors
#  BwAgeCorTMDifDf<-data.frame(tmdifvec,ageEfvec)
#  print(ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageEfvec)) + #geom_point(alpha=.17,size=5) + xlab('Transmodality Difference') +  ylim(-.4,.4) #+xlim(-.1,13)+ ylab('Age Correlation') + ggtitle(paste('Pairwise Between-Network #Age-FC Relations - ',Y7vec[y]))) 
#}

# for all y7 nets (EXCLUSIVE VERSION)
#### make a vector of variables that can become plots
###pointwise_bwplotvec<-t(array(as.character(paste('plot_',seq(1:7),sep='')),c(1,7)))
###for (y in 1:7){
###  # net looked at in this iteration
###  print(Y7vec[y])
###  # color used for this iter
###  itercolor=ycolors[y]
###  tmdifvec=NULL
###  ageEfvec=NULL
###  # isolate this net by getting indices of where it is in the 464 vector
###  curY7NetInd<-grep(Y7vec[y],domnetvec)
###  # for all b/w cols
###  for (i in 1:length(colnames(individ_scalebybw_df))){
###      #print(i)
###      # extract column name. Will parse column name to determine nature of connection
###      curcolname<-colnames(individ_scalebybw_df)[i]
###      splitname<-unlist(strsplit(curcolname,'_'))
###      scalefield=splitname[4]
###      net1field=splitname[5]
###      net2field=splitname[7]
###      # doctor up scale and net1field so they are exclusively the value of interestx
###      scale=as.numeric(unlist(strsplit(scalefield,'e'))[2])
###      net1=unlist(strsplit(net1field,'s'))[2]
###      net2=net2field 
###      # helping phriendly index
###      K_start=((scale-1)*(scale))/2
###      K_end=(((scale-1)*(scale))/2)+scale-1
###      Kind<-K_start:K_end
###      # ONLY exclude if one network is equal to currently indexed Y7 network ( manipulate ###here to run on all)
###      y7lab1=domnetvec[Kind[as.numeric(net1)]]
###      y7lab2=domnetvec[Kind[as.numeric(net2)]]
###      if (y7lab1 != Y7vec[y] && y7lab2 != Y7vec[y]){
###      # get TM values of both nets at this scale
###      tm1=tmvec[Kind[as.numeric(net1)]]
###      tm2=tmvec[Kind[as.numeric(net2)]]
###      # absolute value as directionality is meaningless here
###      tmdif=abs(tm1-tm2)
###      # get position in master df of this column (need to use \b for exact matches only)
###      curcolnameexact<-paste('\\',curcolname,'\\b',sep='')
###      colindex<-grep(curcolnameexact,colnames(masterdf))
###      # get Age relation controlling for sex and motion
###      pcordf<-cbind(masterdf$Age,masterdf$Sex,masterdf$Motion,masterdf[,colindex])
###      # partial spearmans to extrac age relation
###      pspear=pcor(pcordf,method='spearman')$estimate
###      # save both to respective vectors
###      tmdifvec<-append(tmdifvec,tmdif)
###      ageEfvec<-append(ageEfvec,pspear[4])
###      }
###  }
###  # get correlation
###  correl=cor.test(tmdifvec,ageEfvec)
###  cor_of_int=round(correl$estimate,3)
###  # merged vectors
###  BwAgeCorTMDifDf<-data.frame(tmdifvec,ageEfvec)
###  bwplot<-ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageEfvec)) + geom_point(alpha=.17,size=5)+ 
###  geom_smooth(method='lm',linetype="dashed",color=itercolor,size=2) + xlab('Transmodality ###Difference') +  ylim(-.4,.4) +xlim(-.1,13)+ ylab('Age Correlation') + ###ggtitle(paste('B/w-Network Age-FC Relations - ',Y7vec[y], ' ###excluded',sep=''))+geom_text(x=11,y=.3,label=paste('r =', cor_of_int))
###  
###assign(pointwise_bwplotvec[y],bwplot)
###
###}
###
####ggarrange(plot_1,plot_2,plot_3,plot_4,plot_5,plot_6,plot_7)
###
###ggarrange(plot_1,plot_7)

```

```{r}
# Section to do this with half circles. corresp. to colors of involved y7 nets
# get vector of net1 membership
# get vector of net2 membership

# for all y7 nets
for (y in 1:7){
  # net looked at in this iteration
  print(Y7vec[y])
  # isolate this net by getting indices of where it is in the 464 vector
  curY7NetInd<-grep(Y7vec[y],domnetvec)
  # initialize vectors
  tmdifvec=NULL
  ageEfvec=NULL
  Net2Memb=NULL
  # for all b/w cols
  for (i in 1:length(colnames(individ_scalebybw_df))){
      #print(i)
      # extract column name. Will parse column name to determine nature of #connection
      curcolname<-colnames(individ_scalebybw_df)[i]
      splitname<-unlist(strsplit(curcolname,'_'))
      scalefield=splitname[4]
      net1field=splitname[5]
      net2field=splitname[7]
      # doctor up scale and net1field so they are exclusively the value of #interestx
      scale=as.numeric(unlist(strsplit(scalefield,'e'))[2])
      net1=unlist(strsplit(net1field,'s'))[2]
      net2=net2field 
      # helping phriendly index
      K_start=((scale-1)*(scale))/2
      K_end=(((scale-1)*(scale))/2)+scale-1
      Kind<-K_start:K_end
      # ONLY include if one network is equal to currently indexed Y7 network
      y7lab1=domnetvec[Kind[as.numeric(net1)]]
      y7lab2=domnetvec[Kind[as.numeric(net2)]]
      if (y7lab1 == Y7vec[y] || y7lab2 == Y7vec[y]){
      # get TM values of both nets at this scale
      tm1=tmvec[Kind[as.numeric(net1)]]
      tm2=tmvec[Kind[as.numeric(net2)]]
      # absolute value as directionality is meaningless here
      tmdif=abs(tm1-tm2)
     # get position in master df of this column (need to use \b for exact #matches only)
      curcolnameexact<-paste('\\',curcolname,'\\b',sep='')
      colindex<-grep(curcolnameexact,colnames(masterdf))
      # get Age relation controlling for sex and motion
      pcordf<-cbind(masterdf$Age,masterdf$Sex,masterdf$Motion,masterdf[,colindex])
      # partial spearmans to extrac age relation
      pspear=pcor(pcordf,method='spearman')$estimate
      # save both to respective vectors
      tmdifvec<-append(tmdifvec,tmdif)
      ageEfvec<-append(ageEfvec,pspear[4])
      if (Y7vec[y]==y7lab1){
        Net2Memb<-append(Net2Memb,as.character(y7lab2))
      }else{
          Net2Memb<-append(Net2Memb,as.character(y7lab1))
        }
      }
  } 
  
  # merged vectors
  BwAgeCorTMDifDf<-data.frame(tmdifvec,ageEfvec,factor(Net2Memb,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM")))
  colnames(BwAgeCorTMDifDf)<-c('tmdifvec','ageEfVec','Net2Memb')
  print(ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageEfvec,color=Net2Memb)) + geom_point(alpha=.27,size=3)+ scale_color_manual(values=ycolors) + xlab('Transmodality Difference') +  ylim(-.4,.4) +xlim(-.1,13)+ ylab('Age Correlation') + ggtitle(paste('Pairwise Between-Network Age-FC Relations - ',Y7vec[y]))+theme_minimal())
  
}


# can use this unicode half circle thing to get each dot on one plot with dual-colored halves

#ggplot(BwAgeCorTMDifDf[1:10,],aes(x=tmdifvec,y=ageEfvec)) + geom_text(size=5,label="\u25D6",family="Arial Unicode MS") + xlab('Transmodality Difference') + ylab('Age Partial Correlation') + ggtitle('Pairwise Between-Network Age-FC Relations')+geom_text(size=5,label="\u25D7",family="Arial Unicode MS",color='blue')
```



```{r}
library(gamm4)

# unitary model of community-level EF and b/w con
# melt bwAvgCondf[,1:464] with idcols for age, sex, motion, scale, and bblid (for random intercept)
to_be_melted<-data.frame(cbind(masteref$bblid,as.numeric(masteref$F1_Exec_Comp_Cog_Accuracy),as.numeric(masteref$Age),as.numeric(masteref$Sex),masteref$Motion,bwAvgCondf[,1:464]))

# get the long format
Melted_clevel_ef<-melt(to_be_melted,id=c(1,2,3,4,5))
colnames(Melted_clevel_ef)<-c('bblid','EF','Age','Sex','Motion','ObsoleteColName','AvgBetweenCon')


### create vector of scales using colnames from ,bwAvgCondf[,1:464]
# initialize
scalesvector<-vector()

# use the column names to determine the scale each b/w network con feature is at
for (cn in 1:length(colnames(bwAvgCondf[,1:464]))){
  splitColName<-strsplit((colnames(bwAvgCondf[,1:464]))[cn],split='scale')
  ScaleNet<-strsplit(unlist(splitColName)[2],split='_net')
  scale<-as.numeric(unlist(ScaleNet)[1])
  scalesvector[cn]<-scale
}

# each value needs to be repeated 693 times 
repScalesVector=rep(scalesvector,each=693)

# tag onto long format df
Melted_clevel_ef$Scale<-repScalesVector


# get non-numeric variables into proper format
Melted_clevel_ef$bblid<-as.factor(Melted_clevel_ef$bblid)
Melted_clevel_ef$Sex<-as.factor(Melted_clevel_ef$Sex)

# finally, run the model with GAMM
simplif_EF_mod<-gamm(AvgBetweenCon~s(Age,k=3)+Sex+Motion+log(Scale)+EF*log(Scale), random=list(bblid=~1),data=Melted_clevel_ef,REML=T)
summary(simplif_EF_mod$lme)
summary(simplif_EF_mod$gam)
# run it with gamm4 for checkin
simplif_EF_mod4<-gamm4(AvgBetweenCon~s(Age)+Sex+Motion+log(Scale)+EF*log(Scale),data=Melted_clevel_ef,random=~(1|bblid),REML=T)
summary(simplif_EF_mod4$gam)
```

```{r}
#EF for global level
# pull out EF aligned with bblid for merging into indglobBw
EFmerger<-data.frame(masteref$F1_Exec_Comp_Cog_Accuracy,masteref$bblid)
colnames(EFmerger)<-c('EF','bblid')
indglobBw_EF<-merge(EFmerger,indglobBw,by='bblid')
# melt df to get model of global seg as function of scale
to_be_melteddf<-data.frame(cbind(indglobBw_EF$bblid,indglobBw_EF$EF,indglobBw_EF$Age,indglobBw_EF$Sex,indglobBw_EF$Motion,indglobBw_EF[,6:34]))
melteddf<-melt(to_be_melteddf,id=c('indglobBw_EF.bblid','indglobBw_EF.EF','indglobBw_EF.Age','indglobBw_EF.Sex','indglobBw_EF.Motion'))
# replace x2...x30 with appropriate length scalesvec
colnames(melteddf)<-c('bblid','EF','Age','Sex','Motion','Scale','value')
melteddf$Scale<-as.numeric(rep(seq(from=2,to=30),each=693))
melteddf$bblid<-as.factor(melteddf$bblid)
# manually log transform scale
melteddf$Scale<-log(melteddf$Scale)

# fit model across scales
GlobalBwEF_model<-glmer(value~Scale*Age*EF+Sex+Motion+(1|bblid),melteddf)
plot_model(GlobalBwEF_model,type='int')
```

```{r}
# years format
minAgeEst<-minAgeEst/12
maxAgeEst<-maxAgeEst/12

CIgroupingInd<-as.factor(1:464)

#convert to years for more interpretable slope
derivInfo<-derivInfo*12





# get a vector of the agespan split into 200 to match the deriv vals
agerange<-range(masterdf$Age)/12
agerange200<-seq(agerange[1],agerange[2],length.out = 200)

AgeSpan_plotdf2<-data.frame(tmvec,scalesvec,domnetvec,corVecEst,netpropvec,CIgroupingInd)



# needs to be converted to repeat 464 times before progressing to next age bracket
agerange200464<-array(dim=c(200*464,1))
for (i in 1:length(agerange200)){
agerange200464[((464*i)-463):(464*i)]<-rep(agerange200[i],464)
}

# now we need deriv vals of same format, but they will change for every network at every age bracket. Using sig change should take care of whitening out zeros
deriv200464<-array(dim=c(200*464,1))
for (i in 1:length(agerange200)){
deriv200464[((464*i)-463):(464*i)]<-derivInfo[,i]
}

LongAgeSpan_plotdf2<-data.frame(sapply(AgeSpan_plotdf2,rep.int,times=200))
LongAgeSpan_plotdf2$agespans<-agerange200464
LongAgeSpan_plotdf2$derivs<-deriv200464

breaks=c(-.005,0.005)


# older version
###ggplot(LongAgeSpan_plotdf2,aes(agespans,tmvec,color=derivs,group=CIgroupingInd)) +geom_line(size=10,alpha=.8) +labs(title='Network Segregation Effect Span', x = 'Age', y = 'Transmodality') +theme_classic(base_size = 58)+ xlim(c(8,23))+ scale_colour_gradientn(colours=c('#ff0a0a','#ff9191','white','#8585ff','#0b0bff'),values = c(0,.05,.265,.615,1),breaks=breaks, labels = breaks,name="Change Per Year")+theme(legend.position="top",legend.key.width = unit(4, "cm"))


bwspan<-ggplot(LongAgeSpan_plotdf2,aes(agespans,tmvec,color=derivs,group=CIgroupingInd)) +geom_line(size=13,alpha=.8) +labs(title='External Connectivity Age Effect Span', x = 'Age', y = 'Transmodality') +theme_classic(base_size = 58)+ xlim(c(8,23))+ scale_colour_gradientn(colours=c('#0b0bff','#8585ff','white','#ff9191','#ff0a0a'),values = c(0,.25,.5,.75,1),breaks=breaks, labels = breaks,limits=c(-.005,0.005),name="Change Per Year")+theme(legend.position="top",legend.key.width = unit(5, "cm"))





# with yeo color scheme instead
LongAgeSpan_plotdf2$domnetvec<-as.factor(LongAgeSpan_plotdf2$domnetvec)
#LongAgeSpan_plotdf2$derivs[abs(LongAgeSpan_plotdf2$derivs) < 0.002] <- 0


y7ver<-ggplot(LongAgeSpan_plotdf2,aes(agespans,tmvec,color=domnetvec,group=CIgroupingInd,alpha=abs(derivs))) +geom_line(size=13,aes(agespans,tmvec)) +labs(title='Network Segregation Effect Manifestation', x = 'Age', y = 'Transmodality') +theme_classic(base_size = 58)+ xlim(c(8,23))+ scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068'),name="Maximal Y7 Overlap")+scale_alpha_continuous(range=c(0,1))+theme(legend.position="none",legend.key.width = unit(5, "cm"))

```

```{r}
# summary models for global level
Gbw~Age+Motion+scale+Age*log(scale) # is scale*age sig? yes
Gbw~EF+Motion+scale+Age*log(scale)
# summary models for community level
Cbw~Age+Motion+log(scale)+Age*log(scale)+PG1
Cbw~Age+Motion+log(scale)+Age*log(scale)+PG2
# summary models for nodal level
Nbw~Age+Motion+log(scale)+Age*log(Scale)+PG1
Nbw~Age+Motion+log(scale)+Age*log(scale)+PG2
```

```{r}
#### spatial props
# Both patch inf
LHpi<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/numPatches_LH_allscales.csv')
RHpi<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/numPatches_RH_allscales.csv')

# Both Patch distance info (Geodesic)
piGD<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/NetworkGeoDistr.csv')
# Euclidean distance info
piED<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/NetworkEucDistr.csv')


# bwAgeCorVecs is starting point, length 464 for each network
bwdf$LH_patchnum<-LHpi$patchnum_over_scalesL
bwdf$RH_patchnum<-RHpi$patchnum_over_scalesR
bwdf$Tot_patchnum<-bwdf$LH_patchnum+bwdf$RH_patchnum
bwdf$Transmodality<-tmvec
bwdf$bw_avg<-bwdf$bwAgeCorVecs.avg_bw

patchTM<-ggplot(bwdf,aes(Tot_patchnum,Transmodality,color=domnetvec,alpha=netpropvec^2))+ geom_point(size=5,aes(Tot_patchnum,Transmodality)) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + ylab("Transmodality") + xlab("Total Patch number") +theme_classic(base_size = 28)+guides(alpha=FALSE,color=FALSE)+theme(legend.position="top",legend.title = element_blank(),axis.title.x=element_blank(), axis.text.x=element_blank(),axis.title.y=element_blank(), axis.text.y=element_blank())

patchAgeBw<-ggplot(bwdf,aes(Tot_patchnum,bw_avg,color=domnetvec,alpha=netpropvec^2)) + geom_point(size=5,aes(Tot_patchnum,bw_avg))+ scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Total Number of Patches") + ylab("AgeBwDeltaR") +theme_classic(base_size = 28)+ ylim(-.2,.2)+guides(alpha=FALSE,color=FALSE)+theme(legend.position="top",legend.title = element_blank(),axis.title.x=element_blank(), axis.text.x=element_blank(),axis.title.y=element_blank(), axis.text.y=element_blank())

# the distance duo
bwdf$Patch_GeoDisperse<-piGD$nwise_geods
bwdf$Patch_EucDisperse<-piED$nwise_eucs

geodAgeBw<-ggplot(bwdf,aes(Patch_GeoDisperse,bw_avg,color=domnetvec,alpha=netpropvec^2)) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Geodesic Dispersion") + ylab("AgeBwDeltaR^2") +theme_classic(base_size = 28) + geom_point(size=5,aes(Patch_GeoDisperse,bw_avg))+guides(alpha=FALSE,color=FALSE)+theme(legend.position="top",legend.title = element_blank(),axis.title.x=element_blank(), axis.text.x=element_blank(),axis.title.y=element_blank(), axis.text.y=element_blank())

eucAgeBw<-ggplot(bwdf,aes(Patch_EucDisperse,bw_avg,color=domnetvec,alpha=netpropvec^2)) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Euclidean Dispersion") + ylab("AgeBwDeltaR") +theme_classic(base_size = 28) + geom_point(size=5,aes(Patch_EucDisperse,bw_avg)) +guides(alpha=FALSE,color=FALSE)+theme(legend.position="top",legend.title = element_blank(),axis.title.x=element_blank(), axis.text.x=element_blank(),axis.title.y=element_blank(), axis.text.y=element_blank())

geodTM<-ggplot(bwdf,aes(Patch_GeoDisperse,Transmodality,color=domnetvec,alpha=netpropvec^2))+ geom_point(size=5,aes(Patch_GeoDisperse,Transmodality)) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + ylab("Transmodality") + xlab("Geodesic Dispersion") +theme_classic(base_size = 28)+guides(alpha=FALSE,color=FALSE)+theme(legend.position="top",legend.title = element_blank(),axis.title.x=element_blank(), axis.text.x=element_blank(),axis.title.y=element_blank(), axis.text.y=element_blank())

eucTM<-ggplot(bwdf,aes(Patch_EucDisperse,Transmodality,color=domnetvec,alpha=netpropvec^2))+ geom_point(size=5,aes(Patch_EucDisperse,Transmodality)) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + ylab("Transmodality") + xlab("Euclidean Dispersion") +theme_classic(base_size = 28)+guides(alpha=FALSE,color=FALSE)+theme(legend.position="top",legend.title = element_blank(),axis.title.x=element_blank(), axis.text.x=element_blank(),axis.title.y=element_blank(), axis.text.y=element_blank())
```

```{r}
# effects of transmodality above and beyond dispersion
bw_tm_dispersion<-lm(bw_avg~Transmodality+Patch_GeoDisperse+Patch_EucDisperse+Tot_patchnum,data=bwdf)
```