---
title: "Edge-level-EF"
author: "Adam"
date: "1/19/2021"
output: github_document
---

```{r, message=FALSE}
#libraries
library(vroom)
library(mgcv)
library(ggplot2)
library(hexbin)
library(ggExtra)
library(tidyverse)
library(Metrics)
```

```{r}
### This script both writes out EF and FC values for ridge (scikit-learn), and reads the resulting predictions back in for visualization


###########
# pre-ridge
###########
```

```{r}
### load in demograhics
demo<-read.csv('/cbica/projects/pinesParcels/data/pnc_demo.csv')
ageSex<-data.frame(demo$ageAtScan1,as.factor(demo$sex),demo$scanid,demo$bblid)
subjects<-read.csv('/cbica/projects/pinesParcels/data/participants.txt',header = F)
# get EF in here
subjbehav<-read.csv("~/Downloads/n9498_cnb_factor_scores_fr_20170202.csv")
ef<-data.frame(subjbehav$NAR_F1_Exec_Comp_Cog_Accuracy,subjbehav$bblid)
efSoc<-data.frame(subjbehav$NAR_F2_Social_Cog_Accuracy,subjbehav$bblid)
efMem<-data.frame(subjbehav$NAR_F3_Memory_Accuracy,subjbehav$bblid)

### Collapse Motion metric 
# read in
Rest_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_RestQAData_20170714.csv")
NBack_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_NBACKQAData_20181001.csv")
Idemo_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_idemo_FinalQA_092817.csv")
# combine
motmerge<-merge(Rest_Motion_Data,NBack_Motion_Data,by='bblid')
motmerge<-merge(motmerge,Idemo_Motion_Data,by='bblid')
motmerge$Motion <- (motmerge$restRelMeanRMSMotion + motmerge$nbackRelMeanRMSMotion + motmerge$idemoRelMeanRMSMotion)/3;
motiondf<-data.frame(motmerge$bblid,motmerge$Motion)
colnames(motiondf)<-c('bblid','Motion')

### combine non-fMR data
colnames(subjects)<-c("scanid")
colnames(ageSex)<-c("Age","Sex","scanid","bblid")
df<-merge(subjects,ageSex,by="scanid")
df<-merge(df,motiondf,by='bblid')

### community solutions gauged in this iteration
community_vec<-seq(2,30)

# big load - output of fc_to_csv.m (all coupling/FC data, pre-organized)
fc<-vroom('/cbica/projects/pinesParcels/results/aggregated_data/fc/master_fcfeats_rs_rounded.csv')
# First row gotta go
fc<-fc[-c(1)]
# isolate shams
shams<-fc[694:695,]
# Merge with non-fMR data into master data frame
masterdf<-merge(fc,df,by='bblid')
# add EF
subjbehav<-read.csv("~/Downloads/n9498_cnb_factor_scores_fr_20170202.csv")
ef<-data.frame(subjbehav$NAR_F1_Exec_Comp_Cog_Accuracy,subjbehav$bblid)
colnames(ef)<-c('F1_Exec_Comp_Cog_Accuracy','bblid')
colnames(efSoc)<-c('F2_Social_Cog_Accuracy','bblid')
colnames(efMem)<-c('F3_Memory_Accuracy','bblid')
# merge in
masteref<-merge(masterdf,ef,by='bblid')
masterefSoc<-merge(masterdf,efSoc,by='bblid')
masterefMem<-merge(masterdf,efMem,by='bblid')

```

```{r}
# parse fields of interest 


# for parsing individualized partition values
ind='ind'

# for parsing specifically network edges
bwi='_bw_FC_'
wini='_win_FC_'
nsegi='_seg_scale'

# indices of said indicators
indiv=grep(ind,colnames(masterdf))
bwcol=grep(bwi,colnames(masterdf))
wincols=grep(wini,colnames(masterdf))
nsegcols=grep(nsegi,colnames(masterdf))

### Using index combinations, get to dataframe of interest
indiv_bwcols_ind<-intersect(bwcol,indiv)
individ_scalebybw_df<-masterdf[,indiv_bwcols_ind]
bwcolnames<-colnames(individ_scalebybw_df)
indiv_nsegcols_ind<-intersect(nsegcols,indiv)
indiv_wincols_ind<-intersect(wincols,indiv)
individ_scalebywin_df<-masterdf[,indiv_wincols_ind]
# to later use wincolname -> bwcolname mapping to extrapolate if if network is unimodal or transmodal along bwcol indices
wincolnames<-colnames(individ_scalebywin_df)
```

```{r}
# combine age, motion, and EF scores with edges
AgeMotEF<-cbind(masterdf[,indiv_bwcols_ind],masteref$Age,masteref$Motion,masteref$F1_Exec_Comp_Cog_Accuracy)
# write out for scikit learn
write.table(AgeMotEF,'/cbica/projects/pinesParcels/results/EffectVecs/rs_AgeMotEF',sep=',', col.names = F,quote = F,row.names=F)

# use source activate mv_preds to load in required python libraries
# run penal_regresFC_AgeEFIndep.py
```

```{r}
# SOCIAL EF
# combine age, motion, and EF scores with edges
AgeMotEFSoc<-cbind(masterefSoc[,indiv_bwcols_ind],masterefSoc$Age,masterefSoc$Motion,masterefSoc$F2_Social_Cog_Accuracy)
# write out for scikit learn
write.table(AgeMotEFSoc,'/cbica/projects/pinesParcels/results/EffectVecs/AgeMotEFSoc',sep=',', col.names = F,quote = F,row.names=F)

# use source activate mv_preds to load in required python libraries
# run penal_regresFC_AgeEFIndep.py
```

```{r}
# MEMORY EF
# combine age, motion, and EF scores with edges
AgeMotEFMem<-cbind(masterefMem[,indiv_bwcols_ind],masterefMem$Age,masterefMem$Motion,masterefMem$F3_Memory_Accuracy)
# write out for scikit learn
write.table(AgeMotEFMem,'/cbica/projects/pinesParcels/results/EffectVecs/AgeMotEFMem',sep=',', col.names = F,quote = F,row.names=F)

# use source activate mv_preds to load in required python libraries
# run penal_regresFC_AgeEFIndep.py
```


```{r}
###########
# post-scikit-ridge
###########
```

```{r}
# load in subject predictions. First column is sum of predicted EF from every instance in which this subject was randomly allocated to the testing 1/3rd. Second column is the number of times the subject was allocated to the testing 1.3rd.
predEF_AIcsv<-read.csv('/cbica/projects/pinesParcels/data/aggregated_data/SubjPreds_AI.csv',header=F)

# convert to average predicted EF over all folds
predEF_AI<-predEF_AIcsv[,1]/predEF_AIcsv[,2]
# average "observed", AKA, average EF after regressing out motion and age over folds
obsEF_AI<-predEF_AIcsv[,3]/predEF_AIcsv[,2]

# pred ef vs. age. There should be no relationship if regressing Age out of EF scores worked.
plot(masteref$Age,predEF_AI)
cor.test(masteref$Age,predEF_AI)

# pred ef vs. ef. There should be a relationship if our model was able to predict EF in unseen subjects.
plot(obsEF_AI,predEF_AI)

# save the real predicted vs. observed correlation for plotting relative to null distribution
predObsCor<-cor.test(obsEF_AI,predEF_AI)$estimate

# median absolute error also of interest.
mae(obsEF_AI,predEF_AI)

# get permutation prediction vs. observed correlations from permutation writeout
predEF_AIpermutCors<-read.csv('/cbica/projects/pinesParcels/data/aggregated_data/PermutPreds_AI.csv',header=F)

# get predicted vs observed over iterations to confirm average prediction (correlation)
predEF_allIters<-read.csv('/cbica/projects/pinesParcels/data/aggregated_data/Predicted_Obs_Cors.csv',header=F)
# average correlation of predicted vs. observed, slightly lower than correlation of average predicted vs. average observed
mean(predEF_allIters$V1)

# Figure 6 flag
plotdf<-data.frame(obsEF_AI,predEF_AI)
```

```{r, fig.width=4,fig.height=3}
# edge-EF pred. permutation vs. observed
ggplot(predEF_AIpermutCors,aes(x=V1))+geom_density(size=1.5)+geom_vline(xintercept = predObsCor,size=2,color='#BC3754')+theme_classic(base_size=18)+ylab('')+xlab('')+guides(y="none")+scale_x_continuous(breaks=c(-.3,0,.3,.6),limits=c(-.35,.6))

```


```{r, fig.width=12,fig.height=10}
ggplot(plotdf,aes(x=obsEF_AI,y=predEF_AI)) +geom_point(size=2,alpha=.6)+geom_smooth(method='lm',color='black',size=2)+theme_classic(base_size=25) + xlab("Observed") + ylab("Predicted")+ggtitle('Executive Function')
```

```{r}
#### SOCIAL EF


# load in subject predictions. First column is sum of predicted EF from every instance in which this subject was randomly allocated to the testing 1/3rd. Second column is the number of times the subject was allocated to the testing 1.3rd.
predEF_AIcsv_Soc<-read.csv('/cbica/projects/pinesParcels/data/aggregated_data/SubjPreds_AI_Soc.csv',header=F)

# convert to average predicted EF over all folds
predEF_AI_Soc<-predEF_AIcsv_Soc[,1]/predEF_AIcsv_Soc[,2]
# average "observed", AKA, average EF after regressing out motion and age over folds
obsEF_AI_Soc<-predEF_AIcsv_Soc[,3]/predEF_AIcsv_Soc[,2]

# pred ef vs. age. There should be no relationship if regressing Age out of EF scores worked.
plot(masterefSoc$Age,predEF_AI_Soc)
cor.test(masterefSoc$Age,predEF_AI_Soc)

# pred ef vs. ef. There should be a relationship if our model was able to predict EF in unseen subjects.
plot(obsEF_AI_Soc,predEF_AI_Soc)

# save the real predicted vs. observed correlation for plotting relative to null distribution
predObsCor_Soc<-cor.test(obsEF_AI_Soc,predEF_AI_Soc)$estimate

# median absolute error also of interest.
mae(obsEF_AI_Soc,predEF_AI_Soc)

# get permutation prediction vs. observed correlations from permutation writeout
predEF_AIpermutCors_Soc<-read.csv('/cbica/projects/pinesParcels/data/aggregated_data/PermutPreds_AI_Soc.csv',header=F)

# get predicted vs observed over iterations to confirm average prediction (correlation)
predEF_allIters_Soc<-read.csv('/cbica/projects/pinesParcels/data/aggregated_data/Predicted_Obs_Cors_Soc.csv',header=F)
# average correlation of predicted vs. observed, slightly lower than correlation of average predicted vs. average observed
mean(predEF_allIters_Soc$V1)

# Figure 6 flag
plotdf_Soc<-data.frame(obsEF_AI_Soc,predEF_AI_Soc)
```

```{r, fig.width=4,fig.height=3}
# edge-EF pred. permutation vs. observed
ggplot(predEF_AIpermutCors_Soc,aes(x=V1))+geom_density(size=1.5)+geom_vline(xintercept = predObsCor_Soc,size=2,color='#BC3754')+theme_classic(base_size=18)+ylab('')+xlab('')+guides(y="none")+scale_x_continuous(breaks=c(-.3,0,.3,.6),limits=c(-.35,.6))

```


```{r, fig.width=12,fig.height=10}
ggplot(plotdf_Soc,aes(x=obsEF_AI_Soc,y=predEF_AI_Soc)) +geom_point(size=2,alpha=.6)+geom_smooth(method='lm',color='black',size=2)+theme_classic(base_size=25) + xlab("Observed") + ylab("Predicted")+ggtitle('Executive Function (Social)')
```


```{r}

#### MEMORY EF

# load in subject predictions. First column is sum of predicted EF from every instance in which this subject was randomly allocated to the testing 1/3rd. Second column is the number of times the subject was allocated to the testing 1.3rd.
predEF_AIcsv_Mem<-read.csv('/cbica/projects/pinesParcels/data/aggregated_data/SubjPreds_AI_Mem.csv',header=F)

# convert to average predicted EF over all folds
predEF_AI_Mem<-predEF_AIcsv_Mem[,1]/predEF_AIcsv_Mem[,2]
# average "observed", AKA, average EF after regressing out motion and age over folds
obsEF_AI_Mem<-predEF_AIcsv_Mem[,3]/predEF_AIcsv_Mem[,2]

# pred ef vs. age. There should be no relationship if regressing Age out of EF scores worked.
plot(masterefMem$Age,predEF_AI_Mem)
cor.test(masterefMem$Age,predEF_AI_Mem)

# pred ef vs. ef. There should be a relationship if our model was able to predict EF in unseen subjects.
plot(obsEF_AI_Mem,predEF_AI_Mem)

# save the real predicted vs. observed correlation for plotting relative to null distribution
predObsCor_Mem<-cor.test(obsEF_AI_Mem,predEF_AI_Mem)$estimate

# median absolute error also of interest.
mae(obsEF_AI_Mem,predEF_AI_Mem)

# get permutation prediction vs. observed correlations from permutation writeout
predEF_AIpermutCors_Mem<-read.csv('/cbica/projects/pinesParcels/data/aggregated_data/PermutPreds_AI_Mem.csv',header=F)

# get predicted vs observed over iterations to confirm average prediction (correlation)
predEF_allIters_Mem<-read.csv('/cbica/projects/pinesParcels/data/aggregated_data/Predicted_Obs_Cors_Mem.csv',header=F)
# average correlation of predicted vs. observed, slightly lower than correlation of average predicted vs. average observed
mean(predEF_allIters_Mem$V1)

# Figure 6 flag
plotdf_Mem<-data.frame(obsEF_AI_Mem,predEF_AI_Mem)
```

```{r, fig.width=4,fig.height=3}
# edge-EF pred. permutation vs. observed
ggplot(predEF_AIpermutCors_Mem,aes(x=V1))+geom_density(size=1.5)+geom_vline(xintercept = predObsCor_Mem,size=2,color='#BC3754')+theme_classic(base_size=18)+ylab('')+xlab('')+guides(y="none")+scale_x_continuous(breaks=c(-.3,0,.3,.6),limits=c(-.35,.6))

```


```{r, fig.width=12,fig.height=10}
ggplot(plotdf_Mem,aes(x=obsEF_AI_Mem,y=predEF_AI_Mem)) +geom_point(size=2,alpha=.6)+geom_smooth(method='lm',color='black',size=2)+theme_classic(base_size=25) + xlab("Observed") + ylab("Predicted")+ggtitle('Executive Function (Memory)')
```