---
title: "NetPatch_SpatialProps"
author: "Adam"
date: "6/28/2020"
output: html_document
---

```{r setup, include=FALSE}
library(shapes)
library(ggplot2)
library(reshape2)
library(dplyr)
library(ggpubr)
library(vroom)
library(mgcv)
library(ggpointdensity)
```

```{r}
# basic info loads
# load in demo
demo<-read.csv('/cbica/projects/pinesParcels/data/pnc_demo.csv')
age<-data.frame(demo$ageAtScan1,demo$scanid)
subjects<-read.csv('/cbica/projects/pinesParcels/data/participants.txt',header = F)
# Need to determine best qa file
##qa<-read.csv('~/Desktop/multiscale/n1601_RestQAData_20170318.csv')
colnames(subjects)<-c("scanid")
colnames(age)<-c("Age","scanid")
df<-merge(subjects,age,by="scanid")

# community solutions guaged in this iteration
community_vec<-seq(2,30)

# bblids got rounded in matlab csvwrite in this iteration, plug ids directly in
bblids<-read.delim('/cbica/projects/pinesParcels/data/bblids.txt',header=F)
```

```{r}
# big info loads
fc<-vroom('/cbica/projects/pinesParcels/results/aggregated_data/fc/master_fcfeats.csv')

# set colnames to matlab-printed colnames
colnames(fc)<-fc[1,]
# aaaand remove it
fc<-fc[-c(1),]

# round ridiculous number of decimal points
fc[] <- lapply(fc, function(x) {
  if(is.character(x)) round(as.numeric(as.character(x)),digits=3) else x
})

# isolate shams (although merge should take them out later)
shams<-fc[694:695,]

### merge FC with subj info
colnames(fc)[1]<-'bblid'
# AGE
masterdf<-merge(fc,demo,by='bblid')


################### And Motion

Rest_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_RestQAData_20170714.csv")
NBack_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_NBACKQAData_20181001.csv")
Idemo_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_idemo_FinalQA_092817.csv")

motmerge<-merge(Rest_Motion_Data,NBack_Motion_Data,by='bblid')
motmerge<-merge(motmerge,Idemo_Motion_Data,by='bblid')
motmerge$Motion <- (motmerge$restRelMeanRMSMotion + motmerge$nbackRelMeanRMSMotion + motmerge$idemoRelMeanRMSMotion)/3;
motiondf<-data.frame(motmerge$bblid,motmerge$Motion)
colnames(motiondf)<-c('bblid','Motion')
masterdf<-merge(masterdf,motiondf,by='bblid')

### isolate global segreg columns
gsegcols<-grep("globseg",colnames(masterdf))
```

```{r}
# Both patch inf
LHpi<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/numPatches_LH_allscales.csv')
RHpi<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/numPatches_RH_allscales.csv')

# Both Patch distance info (Geodesic)
piGD<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/NetworkGeoDistr.csv')
# Euclidean distance info
piED<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/NetworkEucDistr.csv')

```


```{r}
# the meat
### analyze relation of transmodality to segregation over scales
### Get in Consensus-reference atlas correspondence
rac<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_yCorrespondence_overscales.csv',stringsAsFactors = F)
scalesvec<-as.numeric(rac[2,])
domnetvec<-as.factor(rac[3,])
netpropvec<-as.numeric(rac[4,])

#### read in transmodality
tm<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_transmodality_overscales.csv',stringsAsFactors = F)
colnames(tm)<-tm[1,]
# aaaand remove it
tm<-tm[-c(1),]
tmvec<-as.numeric(tm)

# distribution of transmodality across networks across scales (derived from group consensus)
hist(tmvec,12,xlab="Transmodality",ylab="Count",ylim=c(0,70), main=NULL,col="grey")

# use median transmodality value to split relatively bimodal distribution
medtrans<-median(tmvec)
# equivalent vector to be overwritten with binary classification of transmodality
tmclass<-tmvec
for (i in 1:length(tmclass)){
  if (tmvec[i]<= medtrans){
    tmclass[i]='unimodal'
  }else{
    tmclass[i]='transmodal'
  }
}

############ analyze contribution of W/IN network connectivities' age couplings by scale and transmodality #############
indiv_wincols_ind<-intersect(wincols,indiv)
individ_scalebywin_df<-masterdf[,indiv_wincols_ind]
# ensure 464 length (number of scale by net withincon features)
length(individ_scalebywin_df)

# will needs these functions throughout
corconfinfvecupper<-function(x){
  confinf<-cor.test(x,masterdf$ageAtScan1)[9]
  return(unlist(confinf)[1])
}
corconfinfveclower<-function(x){
  confinf<-cor.test(x,masterdf$ageAtScan1)[9]
  return(unlist(confinf)[2])
}
corEstVec<-function(x){
  corest<-cor.test(x,masterdf$ageAtScan1)[4]
  return(unlist(corest))
}
corEstVec_EF<-function(x){
  corest<-cor.test(x,masterdf$EF)[4]
  return(unlist(corest))
}


confvecupper<-as.numeric(lapply(masterdf[,indiv_wincols_ind],corconfinfvecupper))
confveclower<-as.numeric(lapply(masterdf[,indiv_wincols_ind],corconfinfveclower))
corVecEst<-as.numeric(lapply(masterdf[,indiv_wincols_ind],corEstVec))
confveclower_d<-data.frame(tmvec,confveclower,scalesvec,domnetvec,netpropvec,corVecEst)
confvecupper_d<-data.frame(tmvec,confvecupper,scalesvec,domnetvec,netpropvec,corVecEst)
confvecdf<-data.frame(confveclower_d = confveclower_d, confvecupper_d  = confvecupper_d)

# augment dataframe for CI range plot
CIgroupingInd<-as.factor(1:464)
confveclower_d[,7]<-CIgroupingInd
confvecupper_d[,7]<-CIgroupingInd
#corVecEst_d[,6]<-CIgroupingInd
colnames(confveclower_d)[2]<-"CIbounds"
colnames(confvecupper_d)[2]<-"CIbounds"
win_CIplotdf<-data.frame(rbind(confveclower_d,confvecupper_d))
# range of interest until we work out K=2 and K=3
indofint<-6:464
indofint<-append(indofint,(470:928))

# plot it
Win_age_tm<-ggplot(win_CIplotdf[indofint,],aes(tmvec,CIbounds,color=domnetvec,alpha=netpropvec^2,group=V7)) + geom_line(size=1) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Transmodality") + ylab("AgeWithinCor") +theme_classic(base_size = 28) + geom_point(size=4,aes(tmvec,corVecEst)) + ggtitle('Correlation of Within Network Connectivity and Age over All Networks')+ ylim(-.5,.5)

# check for scale-specific effects
Win_age_scale<-ggplot(win_CIplotdf[indofint,],aes(tmvec,corVecEst,color=scalesvec)) + geom_point(size=4) + xlab("Transmodality") + ylab("AgeWinCor")+theme_classic(base_size = 28)+ ylim(-.5,.5)+ ggtitle('Correlation of Within Network Connectivity and Age over All Networks')
```

```{r}
### The sauce

# pull out scale x network segregation for individualized maps
indiv_nsegcols_ind<-intersect(nsegcols,indiv)
indiv_scalebynet_df<-masterdf[,indiv_nsegcols_ind]
# ensure 464 length (number of scale by net features)
length(indiv_scalebynet_df)

confvecupper<-as.numeric(lapply(masterdf[,indiv_nsegcols_ind],corconfinfvecupper))
confveclower<-as.numeric(lapply(masterdf[,indiv_nsegcols_ind],corconfinfveclower))
corVecEst<-as.numeric(lapply(masterdf[,indiv_nsegcols_ind],corEstVec))

confveclower_d<-data.frame(tmvec,confveclower,scalesvec,domnetvec,netpropvec,corVecEst)
confvecupper_d<-data.frame(tmvec,confvecupper,scalesvec,domnetvec,netpropvec,corVecEst)
confvecdf<-data.frame(confveclower_d = confveclower_d, confvecupper_d  = confvecupper_d)

# augment dataframe for CI range plot
CIgroupingInd<-as.factor(1:464)
confveclower_d[,7]<-CIgroupingInd
confvecupper_d[,7]<-CIgroupingInd
#corVecEst_d[,6]<-CIgroupingInd
colnames(confveclower_d)[2]<-"CIbounds"
colnames(confvecupper_d)[2]<-"CIbounds"
Seg_CIplotdf<-data.frame(rbind(confveclower_d,confvecupper_d))
```

```{r}

## the slow
Seg_CIplotdf$LH_patchnum<-LHpi$patchnum_over_scalesL
Seg_CIplotdf$RH_patchnum<-RHpi$patchnum_over_scalesR
Seg_CIplotdf$Tot_patchnum<-Seg_CIplotdf$LH_patchnum+Seg_CIplotdf$RH_patchnum

ggplot(Seg_CIplotdf,aes(tmvec,Tot_patchnum,color=domnetvec,alpha=netpropvec^2,group=V7))+ geom_point(size=4,aes(tmvec,Tot_patchnum)) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Transmodality") + ylab("Total Patch number") +theme_classic(base_size = 28)

ggplot(Seg_CIplotdf,aes(tmvec,Tot_patchnum,color=scalesvec,group=V7))+ geom_point(size=4,aes(tmvec,Tot_patchnum)) +theme_classic(base_size = 28)

ggplot(Seg_CIplotdf,aes(Tot_patchnum,corVecEst,color=domnetvec,alpha=netpropvec^2,group=V7)) + geom_point(size=4,aes(Tot_patchnum,corVecEst))+ scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Total Number of Patches") + ylab("AgeSegregCor") +theme_classic(base_size = 28)+ ylim(-.5,.5)

ggplot(Seg_CIplotdf,aes(Tot_patchnum,corVecEst))+ geom_pointdensity(size=4)+ xlab("Transmodality") + ylab("Total Patch number")

ggplot(Seg_CIplotdf,aes(tmvec,CIbounds,color=domnetvec,alpha=netpropvec^2,group=V7)) + geom_line(size=1) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Transmodality") + ylab("AgeSegregCor") +theme_classic(base_size = 28) + geom_point(size=4,aes(tmvec,corVecEst)) + ggtitle('Correlation of Network Segregation and Age over All Networks')+ ylim(-.5,.5)

ggplot(Seg_CIplotdf,aes(scalesvec,Tot_patchnum, color=domnetvec,alpha=netpropvec^2,group=V7)) + geom_point(size=4,aes(scalesvec,Tot_patchnum),position="jitter")+ scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + ylab("Total Number of Patches") + xlab("Scale") +theme_classic(base_size = 28)
```


```{r}
# the distance duo
Seg_CIplotdf$Patch_GeoDisperse<-piGD$nwise_geods
Seg_CIplotdf$Patch_EucDisperse<-piED$nwise_eucs
Seg_CIplotdf$Patch_Disperse<-Seg_CIplotdf$Patch_GeoDisperse+Seg_CIplotdf$Tot_patchnum

ggplot(Seg_CIplotdf,aes(Patch_Disperse,CIbounds,color=domnetvec,alpha=netpropvec^2,group=V7)) + geom_line(size=1) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Geodesic dispersion") + ylab("AgeSegregCor") +theme_classic(base_size = 28) + geom_point(size=4,aes(Patch_Disperse,corVecEst)) + ggtitle('Correlation of Network Segregation and Age over All Networks')+ ylim(-.5,.5)

ggplot(Seg_CIplotdf,aes(Tot_patchnum,Patch_GeoDisperse,color=domnetvec,alpha=netpropvec^2,group=V7)) + geom_point(size=4,aes(Tot_patchnum,Patch_GeoDisperse))+ scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Total Number of Patches") + ylab("Geodesic Dispersion") +theme_classic(base_size = 28)

ggplot(Seg_CIplotdf,aes(Tot_patchnum,Patch_GeoDisperse)) + geom_point(size=4,aes(Tot_patchnum,Patch_GeoDisperse),color='purple',alpha=.1) + xlab("Total Number of Patches") + ylab("Geodesic Dispersion") +theme_classic(base_size = 28)


ggplot(Seg_CIplotdf,aes(tmvec,Patch_GeoDisperse,color=domnetvec,alpha=netpropvec^2,group=V7))+ geom_point(size=8,aes(tmvec,Patch_GeoDisperse)) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Transmodality") + ylab("Geodesic Dispersion") +theme_classic(base_size = 28)

ggplot(Seg_CIplotdf,aes(tmvec,Patch_EucDisperse,color=domnetvec,alpha=netpropvec^2,group=V7))+ geom_point(size=8,aes(tmvec,Patch_EucDisperse)) + scale_color_manual(values=c('#007500','#c1253c','#d77d00','#b8cf86','#3281ab','#b61ad0','#670068')) + xlab("Transmodality") + ylab("Euclidean Dispersion") +theme_classic(base_size = 28)
```