---
title: "Network-level-EF"
author: "Adam"
date: "1/19/2021"
output: github_document
---

```{r}
# Welcome to the network-level executive function (EF) effects markdown. Here, we'll analyze cognitive relations that are observed for individual functional networks, and second-order relationships depicting the distribution of EF effects across different kinds of networks. 

# More specifically, this markdown contains the analyses neccessary for figures 6A and 6D. 
```

```{r, message=FALSE}
#libraries

library(gratia)
library(ggplot2)
library(reshape2)
library(dplyr)
library(ggpubr)
library(vroom)
library(data.table)
library(mgcv)
library(ppcor)
library(viridis)
```

```{r}
# functions for cognitive relation calculations

# difference in R2 for EF
EFDeltaR2EstVec<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masteref$F1_Exec_Comp_Cog_Accuracy),as.numeric(masteref$Age),as.numeric(masteref$Sex),masteref$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  # no-EF model (b.w. ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noEFSum<-summary(noEFGam)
  # EF-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  EFSum<-summary(EFGam)
  
  dif<-EFSum$r.sq-noEFSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)
  
}

# same thing but returning chisq test sig. output for FDR correction instead of hard difference
EFDeltaPEstVec<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masteref$F1_Exec_Comp_Cog_Accuracy),as.numeric(masteref$Age),as.numeric(masteref$Sex),masteref$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # EF-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noEFGam,EFGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])
  
}

# bootstrap version: resampled df instead of master df
EFDeltaR2EstVec_RS<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(resampDF$F1_Exec_Comp_Cog_Accuracy),as.numeric(resampDF$Age),as.numeric(resampDF$Sex),resampDF$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  
  # no-EF model (b.w. ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noEFSum<-summary(noEFGam)
  # EF-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  EFSum<-summary(EFGam)
  
  dif<-EFSum$r.sq-noEFSum$r.sq
  
  # partial spearmans to extract age relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)
  
}

```

```{r}
# # # # # adding equivalent functions for other factor scores

# difference in R2 for Social Cog
EFDeltaR2EstVec_Soc<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masteref$F2_Social_Cog_Accuracy),as.numeric(masteref$Age),as.numeric(masteref$Sex),masteref$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  # no-EF model (b.w. ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noEFSum<-summary(noEFGam)
  # EF-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  EFSum<-summary(EFGam)
  
  dif<-EFSum$r.sq-noEFSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)
  
}

# same thing but returning chisq test sig. output for FDR correction instead of hard difference
EFDeltaPEstVec_Soc<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masteref$F2_Social_Cog_Accuracy),as.numeric(masteref$Age),as.numeric(masteref$Sex),masteref$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # EF-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noEFGam,EFGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])
  
}

# bootstrap version: resampled df instead of master df
EFDeltaR2EstVec_RS_Soc<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(resampDF$F2_Social_Cog_Accuracy),as.numeric(resampDF$Age),as.numeric(resampDF$Sex),resampDF$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  
  # no-EF model (b.w. ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noEFSum<-summary(noEFGam)
  # EF-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  EFSum<-summary(EFGam)
  
  dif<-EFSum$r.sq-noEFSum$r.sq
  
  # partial spearmans to extract age relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)
  
}

### ### ### ### ### ###
### Memory scores, F3
### ### ### ### ### ### 

EFDeltaR2EstVec_Mem<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masteref$F3_Memory_Accuracy),as.numeric(masteref$Age),as.numeric(masteref$Sex),masteref$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  # no-EF model (b.w. ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noEFSum<-summary(noEFGam)
  # EF-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  EFSum<-summary(EFGam)
  
  dif<-EFSum$r.sq-noEFSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)
  
}

# same thing but returning chisq test sig. output for FDR correction instead of hard difference
EFDeltaPEstVec_Mem<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masteref$F3_Memory_Accuracy),as.numeric(masteref$Age),as.numeric(masteref$Sex),masteref$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # EF-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noEFGam,EFGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])
  
}

# bootstrap version: resampled df instead of master df
EFDeltaR2EstVec_RS_Mem<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(resampDF$F3_Memory_Accuracy),as.numeric(resampDF$Age),as.numeric(resampDF$Sex),resampDF$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  
  # no-EF model (b.w. ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noEFSum<-summary(noEFGam)
  # EF-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  EFSum<-summary(EFGam)
  
  dif<-EFSum$r.sq-noEFSum$r.sq
  
  # partial spearmans to extract age relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)
  
}
```

```{r}
# load 'erry thang - Next 4 chunks are equivalent to load-in and distillation from network-level age



### load in demograhics
demo<-read.csv('/cbica/projects/pinesParcels/data/pnc_demo.csv')
ageSex<-data.frame(demo$ageAtScan1,as.factor(demo$sex),demo$scanid,demo$bblid)
subjects<-read.csv('/cbica/projects/pinesParcels/data/participants.txt',header = F)
# get EF in here
subjbehav<-read.csv("~/Downloads/n9498_cnb_factor_scores_fr_20170202.csv")
ef<-data.frame(subjbehav$NAR_F1_Exec_Comp_Cog_Accuracy,subjbehav$bblid)

### Collapse Motion metric 
# read in
Rest_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_RestQAData_20170714.csv")
NBack_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_NBACKQAData_20181001.csv")
Idemo_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_idemo_FinalQA_092817.csv")
# combine
motmerge<-merge(Rest_Motion_Data,NBack_Motion_Data,by='bblid')
motmerge<-merge(motmerge,Idemo_Motion_Data,by='bblid')
motmerge$Motion <- (motmerge$restRelMeanRMSMotion + motmerge$nbackRelMeanRMSMotion + motmerge$idemoRelMeanRMSMotion)/3;
motiondf<-data.frame(motmerge$bblid,motmerge$Motion)
colnames(motiondf)<-c('bblid','Motion')

### combine non-fMR data
colnames(subjects)<-c("scanid")
colnames(ageSex)<-c("Age","Sex","scanid","bblid")
df<-merge(subjects,ageSex,by="scanid")
df<-merge(df,motiondf,by='bblid')

### community solutions guaged in this iteration
community_vec<-seq(2,30)

# big load - output of fc_to_csv.m (all coupling/FC data, pre-organized)
fc<-vroom('/cbica/projects/pinesParcels/results/aggregated_data/fc/master_fcfeats_rounded.csv')
# First row gotta go
fc<-fc[-c(1)]
# isolate shams
shams<-fc[694:695,]
# Merge with non-fMR data into master data frame
masterdf<-merge(fc,df,by='bblid')
# add EF
subjbehav<-read.csv("~/Downloads/n9498_cnb_factor_scores_fr_20170202.csv")
ef<-data.frame(subjbehav$NAR_F1_Exec_Comp_Cog_Accuracy,subjbehav$bblid)
Soc<-data.frame(subjbehav$NAR_F2_Social_Cog_Accuracy,subjbehav$bblid)
Mem<-data.frame(subjbehav$NAR_F3_Memory_Accuracy,subjbehav$bblid)
colnames(ef)<-c('F1_Exec_Comp_Cog_Accuracy','bblid')
colnames(Soc)<-c('F2_Social_Cog_Accuracy','bblid')
colnames(Mem)<-c('F3_Memory_Accuracy','bblid')
# merge in
masteref<-merge(masterdf,ef,by='bblid')
masteref<-merge(masteref,Soc,by='bblid')
masteref<-merge(masteref,Mem,by='bblid')
```

```{r}
### Get in Consensus-reference atlas correspondence
rac<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_yCorrespondence_overscales.csv',stringsAsFactors = F)
scalesvec<-as.numeric(rac[2,])
domnetvec<-as.factor(rac[3,])
netpropvec<-as.numeric(rac[4,])
# 17 network version
rac17<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_y17Correspondence_overscales.csv',stringsAsFactors = F)
scalesvec17<-as.numeric(rac17[2,])
domnetvec17<-as.factor(rac17[3,])
netpropvec17<-as.numeric(rac17[4,])

#### read in transmodality
tm<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_transmodality_overscales.csv',stringsAsFactors = F)
colnames(tm)<-tm[1,]
# aaaand remove it so we got everything in its right place
tm<-tm[-c(1),]
tmvec<-as.numeric(tm)
# use median transmodality value to split relatively bimodal distribution
medtrans<-median(tmvec)
# equivalent vector to be overwritten with binary classification of transmodality
tmclass<-tmvec
for (i in 1:length(tmclass)){
  if (tmvec[i]<= medtrans){
    tmclass[i]='unimodal'
  }else{
    tmclass[i]='transmodal'
  }
}
```

```{r}
# parse fields of interest 


# indicators of processing stream
ind='ind'
gro='gro'
bts='bts'

# indicators of fc feature type
bwi='_bw_FC_'
wini='_win_FC_'
nsegi='_seg_scale'
#gsegi='_globseg_scale'

# indices of said indicators
indiv=grep(ind,colnames(masterdf))
#group=grep(gro,colnames(masterdf))
#basists=grep(bts,colnames(masterdf))
bwcol=grep(bwi,colnames(masterdf))
wincols=grep(wini,colnames(masterdf))
nsegcols=grep(nsegi,colnames(masterdf))
#gsegcols=grep(gsegi,colnames(masterdf))

### Using index combinations, get to dataframe of interest
indiv_bwcols_ind<-intersect(bwcol,indiv)
individ_scalebybw_df<-masterdf[,indiv_bwcols_ind]
bwcolnames<-colnames(individ_scalebybw_df)
indiv_nsegcols_ind<-intersect(nsegcols,indiv)
indiv_wincols_ind<-intersect(wincols,indiv)
individ_scalebywin_df<-masterdf[,indiv_wincols_ind]
# to later use wincolname -> bwcolname mapping to extrapolate if if network is unimodal or transmodal along bwcol indices
wincolnames<-colnames(individ_scalebywin_df)
```

```{r}
# get average between-network connectivity of each network (average over each network's edges at each scale)



# empty array for each nets average b/w con across subjects
bwAvgCon<-matrix(0,693,464)
# loop over connectivities to-unimodal then to-transmodal
modalloopvar=c('unimodal','transmodal')
for (i in 1:2){
  print(modalloopvar[i])
  # index "the other"
  modalloopvar_other=modalloopvar[modalloopvar!=(modalloopvar[i])]
  # extract which of 1:464 network mappings match the modalitity of this loop
  modalindices=which(tmclass %in% modalloopvar[i])
  # loop over each scale
    for (K in 2:30){
    # Make index of where values from this K should go
      K_start=((K-1)*(K))/2
      K_end=(((K-1)*(K))/2)+K-1
      Kind<-K_start:K_end
    
    # index which values are at this scale
    scaleStr=paste('scale',K,'_',sep='')
    scaleCols_inds=grep(scaleStr,colnames(masterdf))
    scaleK_bw_indivi_cols_inds<-intersect(indiv_bwcols_ind,scaleCols_inds)
    # extract within and between colnames at this scale for within->b/w binarized transmodality mapping
    wincolnames_thisScale_inds<-grep((paste('scale',K,'_',sep='')),wincolnames)
    wincolnames_thisScale=wincolnames[wincolnames_thisScale_inds]
    bwcolnames_thisScale_inds<-grep((paste('scale',K,'_',sep='')),bwcolnames)
    bwcolnames_thisScale=bwcolnames[bwcolnames_thisScale_inds]
    
    # This was to double check that the "scale" grepping was selective enough
    # print(paste(scaleStr,'number of features:',length(bwcolnames_thisScale)))
  # one weird trick to get binarized transmodality class vector for same scale (Doctors hate him!)
    # tm naming aligns with wincon naming
    tmclasses_thisScale<-tmclass[wincolnames_thisScale_inds]
    # extract the network number of each network at this scale in same order as tmclasses_thisScale
    wincolNamesSplit<-strsplit(wincolnames_thisScale,"_net")
    wincolNames_net<-sapply(wincolNamesSplit, "[[" , 2)
    # mini matching vectors with network label at this scale in one col and transmodality binarization in the other
    tmMatchingVecs<-cbind(wincolNames_net,tmclasses_thisScale)
    # remove scale number from strings so we're not picking up on those
    bwcolnames_thisScale_split<-strsplit(bwcolnames_thisScale,"nets")
    bwnetnames_thisScale<-wincolNames_net<-sapply(bwcolnames_thisScale_split, "[[" , 2)
    # add another fucking set of underscores to all of these colnames so 1's dont pick up 10s
    bwnetnames_thisScale_extended<-paste('ind_bw_FC_scale',K,'_nets_',bwnetnames_thisScale,'_',sep='')
    # extra goddamn undercores have to go here and be removed later
    bwcolnames_thisScale_split<-strsplit(bwcolnames_thisScale,"nets")
    # to be matched in all-networks-at-this-scale loop
    # now as we descend into the third circle of for-loop hell, we find the guy from man vs.food being eaten alive by cerberus
    for (N in 1:K){
      # generate index for where values for this network at this scale should reside
      # start from K index
      Nind<-Kind[N]
      # get index for this N in terms of masterdf (collapse | to match multiple patterns)
      Ncolname<-grep(as.character(paste('_',N,'_',sep='')),bwnetnames_thisScale_extended,value=T)
      # need to add "_" before and after each number so I can select for '_N_' and not pick up teens digits with 1, 20s with 3, 15 and 25 with 5, etc.
      # determine if this network is transmodal or unimodal
      NModality<-tmMatchingVecs[,2][[N]]
      NotNModality<-modalloopvar[modalloopvar!=NModality]
      matchvec<-grep(NModality,tmclasses_thisScale)
      # remove self
      matchvec<-matchvec[matchvec!=N]
      # build index of matching modalities to reference masterdf (collapse | to match multiple patterns)
      matchTruncColName<-grep(as.character(paste('_',matchvec,'_',sep='',collapse="|")),Ncolname,value=T)
      # remove first and last characters now that we are specific
      #matchTruncColName<-sub('.$','',matchTruncColName)
      #matchTruncColName<-sub('.','',matchTruncColName)
      # deal with weird thing where empty space was being grepped because of its aspecificity at coarse scales
      if(length(matchTruncColName)==0){
        matchTruncColName[1]='CANTSEEME'
      }
      match_NetN_scaleK_bw_indivi_cols_ind_within_other_ind<-grep(as.character(paste(matchTruncColName,collapse="|")),bwnetnames_thisScale_extended)
      match_NetN_scaleK_bw_indivi_cols_names<-bwcolnames_thisScale[match_NetN_scaleK_bw_indivi_cols_ind_within_other_ind]
      # deep-sea grepping the whole paste and pipe thing is just to deal with character vectors instead of single patterns
      
      # deal with weird thing where empty space was being grepped because of its aspecificity
      if(length(match_NetN_scaleK_bw_indivi_cols_names)==0){
        match_NetN_scaleK_bw_indivi_cols_names[1]='CANTSEEME'
      }

      # added a faux '_' to end of column to col names can more selectively match numbers (not picking up on 20 when looking for 2, 2_ and 20_ more distinct)
      match_NetN_scaleK_bw_indivi_cols_ind<-grep(as.character(paste(match_NetN_scaleK_bw_indivi_cols_names,'_',sep='',collapse="|")),paste(colnames(masterdf),'_',sep=''))
    
  
      oppositevec<-grep(NotNModality,tmclasses_thisScale)
      
      # build index of NON-matching modalities to reference masterdf (collapse | to match multiple patterns)
      unmatchTruncColName<-grep(as.character(paste('_',oppositevec,'_',sep='',collapse="|")),Ncolname,value=T)
      # search for string in limited bwcolnames at this scale so as not to invite other scales into this grep party
      # remove first and last characters now that we are specific
      #unmatchTruncColName<-sub('.$','',unmatchTruncColName)
      #unmatchTruncColName<-sub('.','',unmatchTruncColName)
      unmatch_NetN_scaleK_bw_indivi_cols_names<-grep(as.character(paste(unmatchTruncColName,collapse="|")),bwnetnames_thisScale_extended,value=T)
      
      # deep-sea grepping the whole paste and pipe thing is just to deal with character vectors instead of single patterns
      unmatch_NetN_scaleK_bw_indivi_cols_ind_within_other_ind<-grep(as.character(paste(unmatch_NetN_scaleK_bw_indivi_cols_names,collapse="|")),bwnetnames_thisScale_extended)
      unmatch_NetN_scaleK_bw_indivi_cols_names<-bwcolnames_thisScale[unmatch_NetN_scaleK_bw_indivi_cols_ind_within_other_ind]
      unmatch_NetN_scaleK_bw_indivi_cols_ind<-grep(as.character(paste(unmatch_NetN_scaleK_bw_indivi_cols_names,'_',sep='',collapse="|")),paste(colnames(masterdf),'_',sep=''))
      
      
      # doublecheck that they are mutually exclusive (+1 because self-reference gets removed)
    #  if(length(tmclasses_thisScale)!=length(matchvec)+length(oppositevec)+1){
   #     print('You done goofed, internet police are on their way')
     # }
      if(length(tmclasses_thisScale)!=length(match_NetN_scaleK_bw_indivi_cols_ind)+length(unmatch_NetN_scaleK_bw_indivi_cols_ind)+1){
        print('Names dont add up chief')
        paste('match numbas', length(match_NetN_scaleK_bw_indivi_cols_ind), length(match_NetN_scaleK_bw_indivi_cols_names))
        paste('unmatch numbas', length(unmatch_NetN_scaleK_bw_indivi_cols_ind), length(unmatch_NetN_scaleK_bw_indivi_cols_names))
        stopifnot(length(tmclasses_thisScale)==length(match_NetN_scaleK_bw_indivi_cols_ind)+length(unmatch_NetN_scaleK_bw_indivi_cols_ind)+1)
      }
      
      # if it does not match the modality of the grandparent loop, we wish go assay its connections to opposite-modality networks
    # get average bw network connectivty age correlation for this network at this scale
      both=cbind(masterdf[,match_NetN_scaleK_bw_indivi_cols_ind],masterdf[,unmatch_NetN_scaleK_bw_indivi_cols_ind, drop=F])
      avg_bw=rowMeans(both)
      # for bw-based gams later - convert all b/w cons for a net to avg b/w for each subj
      bwAvgCon[,Nind]=avg_bw
    }
  }
  
}


```

```{r}
# calculate EF effects - equivalent except testing EF instead of Age using functions up top


# set covariates formula for iterating over in the loop
covariates=" ~s(Age,k=3)+Sex+Motion"


# initialize output vectors
minAgeEst<-rep(0,length=length(masterdf[,indiv_nsegcols_ind]))
maxAgeEst<-rep(0,length=length(masterdf[,indiv_nsegcols_ind]))
SplineP<-rep(0,length=length(masterdf[,indiv_nsegcols_ind]))
avg_bw_deltaR2<-rep(0,length=length(masterdf[,indiv_nsegcols_ind]))
avg_bw_deltaP<-rep(0,length=length(masterdf[,indiv_nsegcols_ind]))
EFDR2vec=rep(0,length=length(masterdf[,indiv_nsegcols_ind]))
EFDR2Pvec=rep(0,length=length(masterdf[,indiv_nsegcols_ind]))

# adding other factor scores
SocDR2vec=rep(0,length=length(masterdf[,indiv_nsegcols_ind]))
SocDR2Pvec=rep(0,length=length(masterdf[,indiv_nsegcols_ind]))
MemDR2vec=rep(0,length=length(masterdf[,indiv_nsegcols_ind]))
MemDR2Pvec=rep(0,length=length(masterdf[,indiv_nsegcols_ind]))

# borrowing colnames from indiv_nsegcols to keep network/scale ordering/mappings
colnames(bwAvgCon)<-gsub("_seg_","_avgBw_",colnames(masterdf[,indiv_nsegcols_ind]))
bwAvgCondf<-data.frame(bwAvgCon)

#add on covariate columns
bwAvgCondf$Age<-masterdf$Age
bwAvgCondf$Sex<-masterdf$Sex
bwAvgCondf$Motion<-masterdf$Motion

#for i in 464, -3 because age sex motion columns sit at the end
for (i in 1:(length(bwAvgCondf)-3)){
  # borrowing colnames from indiv_nsegcols to keep network mappings
  x<-colnames(bwAvgCondf[i])
  # EF delta R squared
  EFDR2vec[i]<-EFDeltaR2EstVec(bwAvgCondf[i])
  # EF p-value
  EFDR2Pvec[i]<-EFDeltaPEstVec(bwAvgCondf[i])
  # Soc delta R squared
  SocDR2vec[i]<-EFDeltaR2EstVec_Soc(bwAvgCondf[i])
  # Soc p-value
  SocDR2Pvec[i]<-EFDeltaPEstVec_Soc(bwAvgCondf[i])
  # Mem delta R squared
  MemDR2vec[i]<-EFDeltaR2EstVec_Mem(bwAvgCondf[i])
  # Mem p-value
  MemDR2Pvec[i]<-EFDeltaPEstVec_Mem(bwAvgCondf[i])
}

# fdr EF P's
corrected<-p.adjust(EFDR2Pvec,method='fdr')

# network-level sig vector
NL_sigVec<-logical(464)
NL_sigVec[corrected<0.05]<-TRUE

# bring it all together
bwdf<-data.frame(tmvec,scalesvec,domnetvec,domnetvec17,netpropvec,EFDR2vec,avg_bw_deltaP,SocDR2vec,SocDR2Pvec,MemDR2vec,MemDR2Pvec)
```

```{r}
######## test whether or not network-level EF Effects vary as a function of network Transmodality
# i.e., second-order effects

# in this chunk, prepare normative coefficients for central estimate

# Port EF into the average between-network FC DF
bwAvgCondf$F1_Exec_Comp_Cog_Accuracy<-masteref$F1_Exec_Comp_Cog_Accuracy


bwAvgCondf$F2_Social_Cog_Accuracy<-masteref$F2_Social_Cog_Accuracy
bwAvgCondf$F3_Memory_Accuracy-masteref$F3_Memory_Accuracy

#### LINEAR + QUADRATIC

#OG coefs. 
avg_bw_deltaR2<-rep(0,464)
avg_bw_deltaP<-rep(0,464)
avg_bw_deltaR2_Soc<-rep(0,464)
avg_bw_deltaR2_Mem<-rep(0,464)

for (n in 1:464){
  # first 464 columns are network-level connectivity values. test each.
  # this is a function that return full vs. reduced model comparisons (Age included vs. age excluded, controls for sex + motion).
  avg_bw_deltaR2[n]<-EFDeltaR2EstVec(bwAvgCondf[n])
  avg_bw_deltaR2_Soc[n]<-EFDeltaR2EstVec_Soc(bwAvgCondf[n])
  avg_bw_deltaR2_Mem[n]<-EFDeltaR2EstVec_Mem(bwAvgCondf[n])
}

# create network-level dataframe from subject-level results: tmvec is just a vector of transmodality values for each network
NL_bwdf<-data.frame(tmvec,avg_bw_deltaR2)
# fit full model
OG_EFEff_by_transmodality_model<-lm(avg_bw_deltaR2~poly(tmvec,2),data=NL_bwdf)
# Extract Linear coef.
OG_EFEff_by_transmodality_model_LIN<-summary(OG_EFEff_by_transmodality_model)$coefficients['poly(tmvec, 2)1',]
OG_EFEff_by_transmodality_model_LIN_beta<-OG_EFEff_by_transmodality_model_LIN['Estimate']
# Extract quadratic coef.
OG_EFEff_by_transmodality_model_QUADR<-summary(OG_EFEff_by_transmodality_model)$coefficients['poly(tmvec, 2)2',]
OG_EFEff_by_transmodality_model_QUADR_beta<-OG_EFEff_by_transmodality_model_QUADR['Estimate']

#### Soc
NL_bwdf<-data.frame(tmvec,avg_bw_deltaR2_Soc)
# fit full model
OG_EFEff_by_transmodality_model_Soc<-lm(avg_bw_deltaR2_Soc~poly(tmvec,2),data=NL_bwdf)
# Extract Linear coef.
OG_EFEff_by_transmodality_model_LIN_Soc<-summary(OG_EFEff_by_transmodality_model_Soc)$coefficients['poly(tmvec, 2)1',]
OG_EFEff_by_transmodality_model_LIN_beta_Soc<-OG_EFEff_by_transmodality_model_LIN_Soc['Estimate']
# Extract quadratic coef.
OG_EFEff_by_transmodality_model_QUADR_Soc<-summary(OG_EFEff_by_transmodality_model_Soc)$coefficients['poly(tmvec, 2)2',]
OG_EFEff_by_transmodality_model_QUADR_beta_Soc<-OG_EFEff_by_transmodality_model_QUADR_Soc['Estimate']

#### Mem
NL_bwdf<-data.frame(tmvec,avg_bw_deltaR2_Mem)
# fit full model
OG_EFEff_by_transmodality_model_Mem<-lm(avg_bw_deltaR2_Mem~poly(tmvec,2),data=NL_bwdf)
# Extract Linear coef.
OG_EFEff_by_transmodality_model_LIN_Mem<-summary(OG_EFEff_by_transmodality_model_Mem)$coefficients['poly(tmvec, 2)1',]
OG_EFEff_by_transmodality_model_LIN_beta_Mem<-OG_EFEff_by_transmodality_model_LIN_Mem['Estimate']
# Extract quadratic coef.
OG_EFEff_by_transmodality_model_QUADR_Mem<-summary(OG_EFEff_by_transmodality_model_Mem)$coefficients['poly(tmvec, 2)2',]
OG_EFEff_by_transmodality_model_QUADR_beta_Mem<-OG_EFEff_by_transmodality_model_QUADR_Mem['Estimate']


```

```{r}
### Load in bootstrapped values

# read in bootstrapped values (calculated on PMACS)
bootstrapRDS<-readRDS('~/multiscale/EF_NetLevel_bootInfo.rds')


# for linear Age Effect ~ Transmodality - significance
CI_LIN=quantile(bootstrapRDS$lm_testStatLIN,c(0.025,0.975)) 

# discrete p calculation (https://www.bmj.com/content/343/bmj.d2304 as source)
SE=(CI_LIN[2]-CI_LIN[1])/(2*1.96)
z=OG_EFEff_by_transmodality_model_LIN_beta/SE
z=abs(z)
pLIN<-exp((-0.717*z)-(0.416*(z^2)))

# print confidence interval and significance of linear fit of transmodality to EF effects (Delta R^2)
print(CI_LIN)
print(pLIN)

# aaaaand quadratic Age Effect ~ Transmodality - significance
CI_QUAD=quantile(bootstrapRDS$lm_testStatQUADR,c(0.025,0.975)) 

# discrete p calculation (https://www.bmj.com/content/343/bmj.d2304 as source)
SE=(CI_QUAD[2]-CI_QUAD[1])/(2*1.96)
z=OG_EFEff_by_transmodality_model_QUADR_beta/SE
z=abs(z)
pQUAD<-exp((-0.717*z)-(0.416*(z^2)))

# print confidence interval and significance of quadratic fit of transmodality to EF effects (Delta R^2)
print(CI_QUAD)
print(pQUAD)

### repeat both with Social Cog
CI_LIN=quantile(bootstrapRDS$lm_testStatLIN_Soc,c(0.025,0.975)) 

# discrete p calculation (https://www.bmj.com/content/343/bmj.d2304 as source)
SE=(CI_LIN[2]-CI_LIN[1])/(2*1.96)
z=OG_EFEff_by_transmodality_model_LIN_beta_Soc/SE
z=abs(z)
pLIN<-exp((-0.717*z)-(0.416*(z^2)))

# print confidence interval and significance of linear fit of transmodality to EF effects (Delta R^2)
print(CI_LIN)
print(pLIN)

# aaaaand quadratic Age Effect ~ Transmodality - significance
CI_QUAD=quantile(bootstrapRDS$lm_testStatQUADR_Soc,c(0.025,0.975)) 

# discrete p calculation (https://www.bmj.com/content/343/bmj.d2304 as source)
SE=(CI_QUAD[2]-CI_QUAD[1])/(2*1.96)
z=OG_EFEff_by_transmodality_model_QUADR_beta_Soc/SE
z=abs(z)
pQUAD<-exp((-0.717*z)-(0.416*(z^2)))

# print confidence interval and significance of quadratic fit of transmodality to EF effects (Delta R^2)
print(CI_QUAD)
print(pQUAD)

### and memory
# for linear Age Effect ~ Transmodality - significance
CI_LIN=quantile(bootstrapRDS$lm_testStatLIN_Mem,c(0.025,0.975)) 

# discrete p calculation (https://www.bmj.com/content/343/bmj.d2304 as source)
SE=(CI_LIN[2]-CI_LIN[1])/(2*1.96)
z=OG_EFEff_by_transmodality_model_LIN_beta_Mem/SE
z=abs(z)
pLIN<-exp((-0.717*z)-(0.416*(z^2)))

# print confidence interval and significance of linear fit of transmodality to EF effects (Delta R^2)
print(CI_LIN)
print(pLIN)

# aaaaand quadratic Age Effect ~ Transmodality - significance
CI_QUAD=quantile(bootstrapRDS$lm_testStatQUADR_Mem,c(0.025,0.975)) 

# discrete p calculation (https://www.bmj.com/content/343/bmj.d2304 as source)
SE=(CI_QUAD[2]-CI_QUAD[1])/(2*1.96)
z=OG_EFEff_by_transmodality_model_QUADR_beta_Mem/SE
z=abs(z)
pQUAD<-exp((-0.717*z)-(0.416*(z^2)))

# print confidence interval and significance of quadratic fit of transmodality to EF effects (Delta R^2)
print(CI_QUAD)
print(pQUAD)
```

```{r}
# EF * Transmodality - final setup - FIGURE 6A
# Map nonsig to grey
bwdf$domnetvecSig<-'NonSig'
# sig where CL_vec indicates
bwdf$domnetvecSig[NL_sigVec]<-as.character(bwdf$domnetvec[NL_sigVec])
# order for plot legend
bwdf$domnetvecSig<-as.factor(bwdf$domnetvecSig)
bwdf$domnetvecSig<-factor(bwdf$domnetvecSig,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig"),labels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig."))

# stats for fig-gam
EF_net_gam<-gam(EFDR2vec~s(tmvec,k=3),data=bwdf)
EF_net_gam_Sigonly<-gam(EFDR2vec~s(tmvec,k=3),data=bwdf[NL_sigVec,])
```

```{r, fig.width=11,fig.height=11}
ggplot(bwdf,aes(tmvec,EFDR2vec)) + geom_point(size=4,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80')) + xlab("Functional Hierarchy") + ylab(expression(paste('EF Effect (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 25) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=2.2,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.32,-.275),legend.direction = "horizontal",legend.title=element_text(size=17),legend.text=element_text(size=17))+geom_smooth(method='lm',formula = y~poly(x,2),color='black')

```

```{r}
# equiv for social
# fdr EF P's
corrected<-p.adjust(SocDR2Pvec,method='fdr')
# network-level sig vector
NL_sigVec<-logical(464)
NL_sigVec[corrected<0.05]<-TRUE
# Map nonsig to grey
bwdf$domnetvecSig<-'NonSig'
# sig where CL_vec indicates
bwdf$domnetvecSig[NL_sigVec]<-as.character(bwdf$domnetvec[NL_sigVec])
# order for plot legend
bwdf$domnetvecSig<-as.factor(bwdf$domnetvecSig)
bwdf$domnetvecSig<-factor(bwdf$domnetvecSig,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig"),labels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig."))
# stats for fig-gam
EF_net_gam<-gam(SocDR2vec~s(tmvec,k=3),data=bwdf)
EF_net_gam_Sigonly<-gam(SocDR2vec~s(tmvec,k=3),data=bwdf[NL_sigVec,])
```

```{r, fig.width=11,fig.height=11}
ggplot(bwdf,aes(tmvec,SocDR2vec)) + geom_point(size=4,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80')) + xlab("Functional Hierarchy") + ylab(expression(paste('Social EF Effect (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 25) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=2.2,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.32,-.275),legend.direction = "horizontal",legend.title=element_text(size=17),legend.text=element_text(size=17))+geom_smooth(method='lm',formula = y~poly(x,2),color='black')
```

```{r}
# equiv for memory
# fdr EF P's
corrected<-p.adjust(MemDR2Pvec,method='fdr')
# network-level sig vector
NL_sigVec<-logical(464)
NL_sigVec[corrected<0.05]<-TRUE
# Map nonsig to grey
bwdf$domnetvecSig<-'NonSig'
# sig where CL_vec indicates
bwdf$domnetvecSig[NL_sigVec]<-as.character(bwdf$domnetvec[NL_sigVec])
# order for plot legend
bwdf$domnetvecSig<-as.factor(bwdf$domnetvecSig)
bwdf$domnetvecSig<-factor(bwdf$domnetvecSig,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig"),labels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig."))
# stats for fig-gam
EF_net_gam<-gam(MemDR2vec~s(tmvec,k=3),data=bwdf)
EF_net_gam_Sigonly<-gam(MemDR2vec~s(tmvec,k=3),data=bwdf[NL_sigVec,])
```

```{r, fig.width=11,fig.height=11}
ggplot(bwdf,aes(tmvec,MemDR2vec)) + geom_point(size=4,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80')) + xlab("Functional Hierarchy") + ylab(expression(paste('Memory EF Effect (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 25) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=2.2,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.32,-.275),legend.direction = "horizontal",legend.title=element_text(size=17),legend.text=element_text(size=17))+geom_smooth(method='lm',formula = y~poly(x,2),color='black')
```

```{r}
# FIGURE 6D - EF Effect * Scale * Transmodality
# gams for stats
SMA_gam<-gam(EFDR2vec~s(scalesvec,k=3),data=bwdf[bwdf$domnetvec17=='Somatomotor A',])
DMB_gam<-gam(EFDR2vec~s(scalesvec,k=3),data=bwdf[bwdf$domnetvec17=='DM_B',])
summary(SMA_gam)
summary(DMB_gam)

# convert yeo17 membership to vector capturing only sig. yeo17 networks, graying out nonsig.
domnetSig17<-domnetvec17
levels(domnetSig17)<-c(levels(domnetSig17),'zNonSig_DM','zNonSig_Mot')
bwdf$domnetvec17Sig<-as.character(domnetvec17)
# set nonsigs to de-saturated version of colors
bwdf$domnetvec17Sig[NL_sigVec==FALSE & bwdf$domnetvec17Sig == 'Somatomotor A']='zNonSig_Mot'
bwdf$domnetvec17Sig[NL_sigVec==FALSE & bwdf$domnetvec17Sig == 'DM_B']='zNonSig_DM'
```

```{r, fig.width=9,fig.height=9}
ggplot(bwdf,aes(scalesvec,EFDR2vec)) + xlab("# of Networks") + ylab(expression(paste('EF Effect (',Delta,R^2[adj],')'))) +theme_classic(base_size = 25) +guides(alpha=FALSE,color=guide_legend(title="Yeo 17 Overlap"))+theme(legend.position=c(.35,-.27),legend.direction = "horizontal",legend.text = element_text(size=15),legend.title = element_text(size=15))+
geom_smooth(data=subset(bwdf,domnetvec17=='Somatomotor A'),method='gam',formula = y~s(x,k=3),aes(color=domnetvec17),fill="gray72")+geom_smooth(data=subset(bwdf,domnetvec17=='DM_B'),method='gam',formula = y~s(x,k=3),aes(color=domnetvec17),fill="gray88")+scale_color_manual(values=c('#bc0943','#4183a8'))+geom_point(data=subset(bwdf,domnetvec17=='Somatomotor A'),aes(color=domnetvec17Sig),size=4)+geom_point(data=subset(bwdf,domnetvec17=='DM_B'),aes(color=domnetvec17Sig),size=4)+scale_color_manual(values=c('#bc0943','#4183a8','#ebbecc','#b7d9ed'),labels=c('DM B','SM A','n.s. DM B','n.s. SM A'))+scale_x_continuous(breaks=c(4,10,16,22,28))+theme(plot.margin=unit(c(.9,.6,2,.6),"cm"))
```