---
title: "ExampleVerts"
author: "Adam"
date: "9/2/2020"
output: github_document
---

```{r}
library(rmarkdown)
library(reshape)
library(ggplot2)
library(ggpubr)
library(sjPlot)
# load in demographic data
demo<-read.csv('/cbica/projects/pinesParcels/data/pnc_demo.csv')
ageSex<-data.frame(demo$ageAtScan1,as.factor(demo$sex),demo$scanid,demo$bblid)
colnames(ageSex)[4]<-'bblid'
colnames(ageSex)[1]<-'Age'
#### MOTION METRIC ###
# Load in motion data
Rest_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_RestQAData_20170714.csv")
NBack_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_NBACKQAData_20181001.csv")
Idemo_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_idemo_FinalQA_092817.csv")

# Merge in motion data, average of relRMS for each scan for interpretation
motmerge<-merge(Rest_Motion_Data,NBack_Motion_Data,by='bblid')
motmerge<-merge(motmerge,Idemo_Motion_Data,by='bblid')
motmerge$Motion <- (motmerge$restRelMeanRMSMotion + motmerge$nbackRelMeanRMSMotion + motmerge$idemoRelMeanRMSMotion)/3;
motiondf<-data.frame(motmerge$bblid,motmerge$Motion)
colnames(motiondf)<-c('bblid','Motion')
colnames(subjects)<-c("scanid")
colnames(ageSex)<-c("Age","Sex","scanid","bblid")
df<-merge(subjects,ageSex,by="scanid")
df<-merge(df,motiondf,by='bblid')


SupVisVert<-read.csv('/cbica/projects/pinesParcels/results/exampleVertVisbw.csv')
MotVert<-read.csv('/cbica/projects/pinesParcels/results/exampleVertMotbw.csv')
PFCVert<-read.csv('/cbica/projects/pinesParcels/results/exampleVertPFCbw.csv')

colnames(SupVisVert)[30]<-'bblid'
colnames(MotVert)[30]<-'bblid'
colnames(PFCVert)[30]<-'bblid'

df_SupVisVert<-merge(df,SupVisVert,by="bblid")
df_MotVert<-merge(df,MotVert,by="bblid")
df_PFCVert<-merge(df,PFCVert,by="bblid")
mdf_SupVisVert<-melt(df_SupVisVert,id=c(1,2,3,4,5))
mdf_MotVert<-melt(df_MotVert,id=c(1,2,3,4,5))
mdf_PFCVert<-melt(df_PFCVert,id=c(1,2,3,4,5))
# no scanid in indgloBw, no id var 5

### NEED ACCESS TO indglobBw from MASTER multiscale_statsnfigs OR BwRqCent
mdf_globalVerts<-melt(indglobBw,id=c(1,2,3,4))


# create plots
visplot<-ggplot(data=mdf_SupVisVert,aes(x=variable,y=value,group=bblid,color=Age)) +geom_line(alpha = 0.3,size=1)+ scale_color_gradient2(low = "green", mid = 'green', high = "red") + theme_minimal()+labs(title="Avg B/w Con over scales - Single Vertex - Superior Visual Cortex")


motplot<-ggplot(data=mdf_MotVert,aes(x=variable,y=value,group=bblid,color=Age)) +geom_line(alpha = 0.3,size=1)+ scale_color_gradient2(low = "green", mid = 'green', high = "red") + theme_minimal()+labs(title="Avg B/w Con over scales - Single Vertex - Motor Cortex")

pfcplot<-ggplot(data=mdf_PFCVert,aes(x=variable,y=value,group=bblid,color=Age)) +geom_line(alpha = 0.3,size=1)+ scale_color_gradient2(low = "green", mid = 'green', high = "red") + theme_minimal()+labs(title="Avg B/w Con over scales - Single Vertex - PFC ")

ggarrange(visplot,motplot,pfcplot,ncol=1,nrow=3)

write.csv(mdf_SupVisVert,'~/Desktop/multiscale/long_upperVisVert.csv')
write.csv(mdf_MotVert,'~/Desktop/multiscale/long_MotVert.csv')
write.csv(mdf_PFCVert,'~/Desktop/multiscale/long_PFCVert.csv')

####### LAST PLOT REQUIRES MASTER RMD TO HAVE RAN THRU CORRESPONDING SECTION
BwAll<-ggplot(data=mgroglobbw,aes(x=as.numeric(as.character(variable)),y=value,group=bblid,color=Age)) +geom_line(alpha = 0.12)+scale_color_gradientn(colors=c("yellow","purple")) + theme_minimal(base_size = 28)+labs(title="M/S-Regressed Glob. Bw - Individ. Partitions") + scale_x_continuous(name ="# of Communitites",  breaks=seq(2, 30, 4))+ylab("Global Between")


ggarrange(BwAll,visplot,motplot,pfcplot,ncol=1,nrow=4)



```


```{r}
# fit logscale random effects - goal is one for each vertex, (out of community con ~ 1+logRE(scale)|subj)+Motion+Sex+s(age))
library(lme4)
library(gamm4)
library(visreg)

# setting scale to integer was key
mdf_MotVert$bblid<-as.factor(mdf_MotVert$bblid)
#colnames(mdf_MotVert)[1]<-c('id')
colnames(mdf_MotVert)[6]<-c('Scale')
mdf_MotVert$Scale<-as.integer(mdf_MotVert$Scale)
mdf_MotVert$Age<-as.numeric(mdf_MotVert$Age)

# best fit so far
model=glmer(value~Age*log(Scale)+Motion+Sex+(1 + log(Scale)|bblid),data=mdf_MotVert)
model_ageout=glmer(value~Motion+Sex+(1 + log(Scale)|bblid),data=mdf_MotVert)

#visreg random effects
v<-visreg(model,"Scale",by="bblid",re.form=~(log(Scale)|bblid),plot=F)


# more plotting
modelsum<-summary(model)
a=rep(seq(2:30),each=693)
a=data.frame(modelsum$residuals,a,seq(1:20097))
motvert<-ggplot(a,aes(x=seq.1.20097.,y=modelsum.residuals,col=a))+geom_point()+scale_color_gradientn(colours = rainbow(5))+theme_classic2()

######## with PFC now

# setting scale to integer was key
mdf_PFCVert$bblid<-as.factor(mdf_PFCVert$bblid)
#colnames(mdf_MotVert)[1]<-c('id')
colnames(mdf_PFCVert)[6]<-c('Scale')
mdf_PFCVert$Scale<-as.integer(mdf_PFCVert$Scale)
mdf_PFCVert$Age<-as.numeric(mdf_PFCVert$Age)

# best fit so far
model=glmer(value~Age*log(Scale)+Motion+Sex+(1 + log(Scale)|bblid),data=mdf_PFCVert)
model_ageout=glmer(value~Motion+Scale+Sex+(1 + log(Scale)|bblid),data=mdf_PFCVert)
#visreg random effects
###v<-visreg(model,"Scale",by="bblid",re.form=~(1 + log(Scale)|bblid),plot=F)
# more plotting
modelsum<-summary(model)
a=rep(seq(2:30),each=693)
a=data.frame(modelsum$residuals,a,seq(1:20097))
PFCvert<-ggplot(a,aes(x=seq.1.20097.,y=modelsum.residuals,col=a))+geom_point()+scale_color_gradientn(colours = rainbow(5))+theme_classic2()
#plot_model(model,type="int")

tab_model(model)



### with sup vis now
# setting scale to integer was key
mdf_SupVisVert$bblid<-as.factor(mdf_SupVisVert$bblid)
#colnames(mdf_MotVert)[1]<-c('id')
colnames(mdf_SupVisVert)[6]<-c('Scale')
mdf_SupVisVert$Scale<-as.integer(mdf_SupVisVert$Scale)
mdf_SupVisVert$Age<-as.numeric(mdf_SupVisVert$Age)

# best fit so far
model=glmer(value~Age*log(Scale)+Motion+Sex+(1 + log(Scale)|bblid),data=mdf_SupVisVert)
#visreg random effects
###v<-visreg(model,"Scale",by="bblid",re.form=~(1 + log(Scale)|bblid),plot=F)



```

```{r}
# more plotting
modelsum<-summary(model)
a=rep(seq(2:30),each=693)
a=data.frame(modelsum$residuals,a,seq(1:20097))
SVISvert<-ggplot(a,aes(x=seq.1.20097.,y=modelsum.residuals,col=a))+geom_point()+scale_color_gradientn(colours = rainbow(5))+theme_classic2()

#### on avg. real quick
mdf_globalVerts$bblid<-as.factor(mdf_globalVerts$bblid)
colnames(mdf_globalVerts)[5]<-c('Scale')
mdf_globalVerts$Scale<-as.integer(mdf_globalVerts$Scale)
mdf_globalVerts$Age<-as.numeric(mdf_globalVerts$Age)

model=glmer(value~Age*log(Scale)+Motion+Sex+(1|bblid),data=mdf_globalVerts)
modelsum<-summary(model)
a=rep(seq(2:30),each=693)
a=data.frame(modelsum$residuals,a,seq(1:20097))
AvgVert<-ggplot(a,aes(x=seq.1.20097.,y=modelsum.residuals,col=a))+geom_point()+scale_color_gradientn(colours = rainbow(5))+theme_classic2()

# using many splines
model=gamm(value~ti(Age) + ti(Scale) + ti(Age,Scale) + Motion + Sex,random=list(bblid=~1),data=mdf_globalVerts)

### using link function
#model=glmer((value+1)~Motion+Age*Scale+(1+Scale|bblid),data=mdf_globalVerts,family = Gamma(link = "log"))
#tab_model(model)

# fit as linear model
model=lm(value~Motion+log(Scale),data=mdf_globalVerts)

### more immediately, fit model on average b.w.
# setting scale to integer was key
mdf_globalVerts$bblid<-as.factor(mdf_globalVerts$bblid)
colnames(mdf_globalVerts)[5]<-c('Scale')
mdf_globalVerts$Scale<-as.integer(mdf_globalVerts$Scale)
mdf_globalVerts$Age<-as.numeric(mdf_globalVerts$Age)

model=glmer(value~Motion+log(Scale)+(1 + log(Scale)|bblid),data=mdf_globalVerts)
model1rslopes=ranef(model)$bblid['log(Scale)']
###v<-visreg(model,"Scale",by="bblid",re.form=~(1 + log(Scale)|bblid),plot=F)
model2=glmer(value~Age*log(Scale)+Motion+Sex+log(Scale)+(1 + log(Scale)|bblid),data=mdf_globalVerts)
model2slopes=ranef(model2)$bblid['log(Scale)']
```

```{r}
# look at previous version on github (prior to 9/9/20) for cubic filepaths
library(reshape2)
library(lme4)
demo<-read.csv('~/pnc_demo.csv')
subjects<-read.csv('~/participants.txt',header = F)
ageSex<-data.frame(demo$ageAtScan1,as.factor(demo$sex),demo$scanid,demo$bblid)
colnames(ageSex)[4]<-'bblid'
colnames(ageSex)[1]<-'Age'
Rest_Motion_Data <- read.csv("~/n1601_RestQAData_20170714.csv")
NBack_Motion_Data <- read.csv("~/n1601_NBACKQAData_20181001.csv")
Idemo_Motion_Data <- read.csv("~/n1601_idemo_FinalQA_092817.csv")
motmerge<-merge(Rest_Motion_Data,NBack_Motion_Data,by='bblid')
motmerge<-merge(motmerge,Idemo_Motion_Data,by='bblid')
motmerge$Motion <- (motmerge$restRelMeanRMSMotion + motmerge$nbackRelMeanRMSMotion + motmerge$idemoRelMeanRMSMotion)/3;
motiondf<-data.frame(motmerge$bblid,motmerge$Motion)
colnames(motiondf)<-c('bblid','Motion')
colnames(subjects)<-c("scanid")
colnames(ageSex)<-c("Age","Sex","scanid","bblid")
df<-merge(subjects,ageSex,by="scanid")
df<-merge(df,motiondf,by='bblid')

outputcolnames=c('avgSlope','avgInt','ageSlope','ageInt','MotionFixedEF')
outarray=matrix(1,nrow=1,ncol=5)
colnames(outarray)=outputcolnames
for (v in 1:17734){
  print(v)
  vFP=paste('~/mixedEffectModels/v',v,'_bwVals_overScales.csv',sep='')
  verts=read.csv(vFP)
  colnames(verts)[30]<-'bblid'
  df_verts<-merge(df,verts,by="bblid")
  mdf_verts<-melt(df_verts,id=c(1,2,3,4,5))
  mdf_verts$bblid<-as.factor(mdf_verts$bblid)
  colnames(mdf_verts)[6]<-c('Scale')
  mdf_verts$Scale<-as.integer(mdf_verts$Scale)
  mdf_verts$Age<-as.numeric(mdf_verts$Age)
  model=glmer(value~Motion+log(Scale)+(1 + log(Scale)|bblid),data=mdf_verts)
  fe=fixef(model)
  re=ranef(model)
  re=re$bblid
  avgSlope=fe['log(Scale)']
  avgInt=fe['(Intercept)']
  avgMot=fe['Motion']
  ageSlope=cor.test(re$`log(Scale)`,df$Age,method='spearman')$estimate
  ageInt=cor.test(re$`(Intercept)`,df$Age,method='spearman')$estimate
  outarray[1]=avgSlope
  outarray[2]=avgInt
  outarray[3]=ageSlope
  outarray[4]=ageInt
  outarray[5]=avgMot
  write.table(outarray,file=paste('~/mixedEffectModels/Modeled_fS_fI_raS_raI_fM_v',v,'_bwVals_overScales.csv',sep=''),sep=',',row.names=F,quote=F)
}
```

```{r}
# residuals grouped by subject for a few example areas (last is average)
m1 <- lmer(value ~ log(Scale)*Age + (1|bblid),mdf_MotVert) 
model1_data<-m1@frame
model1_data$resids = resid(m1)
motor<-ggplot(model1_data,aes(y=resids,x=`log(Scale)`,group=bblid,color=bblid))+geom_point(alpha=.1,show.legend=F)+geom_line(alpha=.5,show.legend=F)+ggtitle('motor')

p1 <- lmer(value ~ log(Scale)*Age + (1|bblid),mdf_PFCVert) 
model1_data<-p1@frame
model1_data$resids = resid(p1)
pfc<-ggplot(model1_data,aes(y=resids,x=`log(Scale)`,group=bblid,color=bblid))+geom_point(alpha=.1,show.legend=F)+geom_line(alpha=.5,show.legend=F)+ggtitle('pfc')

o1 <- lmer(value ~ log(Scale)*Age + (1|bblid),mdf_SupVisVert) 
model1_data<-o1@frame
model1_data$resids = resid(o1)
occip<-ggplot(model1_data,aes(y=resids,x=`log(Scale)`,group=bblid,color=bblid))+geom_point(alpha=.1,show.legend=F)+geom_line(alpha=.5,show.legend=F)+ggtitle('occip.')

avg1 <- lmer(value ~ log(Scale)*Age + (1|bblid),mdf_globalVerts) 
model1_data<-avg1@frame
model1_data$resids = resid(avg1)
avg<-ggplot(model1_data,aes(y=resids,x=`log(Scale)`,group=bblid,color=bblid))+geom_point(alpha=.1,show.legend=F)+geom_line(alpha=.5,show.legend=F)+ggtitle('avg.')

ggarrange(avg,pfc,motor,occip)
```


